### ISSUE TITLE
Paging Issue - URL rendered incorrectly

### ISSUE THREAD

**Issue by rtaixghealth** [ewoutkramer/fhir-net-api#100]
My code snippet:
![9-22-2015 10-21-58 am](https://cloud.githubusercontent.com/assets/13961469/10025961/e64567ca-6113-11e5-8989-bf853a8e3245.png)
If there's a next link, I will continue retrieving the data.

It was working fine until we hit a next buttons with date range queries.

Below are additional snippets:
![9-22-2015 7-25-49 am](https://cloud.githubusercontent.com/assets/13961469/10026091/a11b3890-6114-11e5-9497-842816a9bfa1.png)
![9-22-2015 7-26-05 am](https://cloud.githubusercontent.com/assets/13961469/10026096/a71a5af0-6114-11e5-9518-a2f30438e7ca.png)

The actual query that eventually gets sent to the server is:  https://fhir.sandboxcernerpowerchart.com/may2015/d075cf8b-3261-481d-97e5-ba6c48d3b41f/MedicationPrescription?patient=1316024&status=completed%2Cstopped&_count=25&scheduledtiming-bounds-end=<%3F2014-09-08T18:42:02.000Z&context=14187710&_format=json.

We're trying to understand why "=" would be translated into %3F?  We are expecting %3D.  

Their open server is:
First query: https://fhir.sandboxcernerpowerchart.com/may2015/open/d075cf8b-3261-481d-97e5-ba6c48d3b41f/MedicationPrescription?patient=1316024&status=completed%2Cstopped&_format=json
Next query: https://fhir.sandboxcernerpowerchart.com/may2015/open/d075cf8b-3261-481d-97e5-ba6c48d3b41f/MedicationPrescription?patient=1316024&status=completed%2Cstopped&_count=25&scheduledtiming-bounds-end=%3C=2014-09-08T18%3A42%3A02.000Z&context=14187710&_format=json

Thanks!

-rubes

**Comment by ewoutkramer** [comment]
I'll look into this.

**Comment by ewoutkramer** [comment]
Why it became %3F (a question mark!): A bug. When a parameter has two "=", I would support this, just use the first "=" to split key/value. However, the algorithm to do this, rejoined the unused parts by "?" instead of "=".  

Note, that because of this issues, in DSTU2 we have changed the syntax of the =<= etc into =lt.
