### ISSUE TITLE
Not able to load sample Observation JSON using latest Hl7.Fhir.Core package from NeGet

### ISSUE THREAD

**Issue by aniketnitj** [ewoutkramer/fhir-net-api#101]
Hi, I am trying to load sample Observation JSON using latest Hl7.Fhir.Core package from NeGet.
I am getting "An unhandled exception of type 'System.FormatException' occurred in Hl7.Fhir.Core.dll
Additional information: At line 4, pos 12: Encountered unknown member 'fhir_comments' while deserializing"
Library is not able to deserilize this Json to Object.

Code: var obs = FhirParser.ParseResourceFromJson(File.ReadAllText(@"C:\Users\examples-json\observation-example.json"));

Am I missing something?

![image](https://cloud.githubusercontent.com/assets/13367381/10108395/497f7d4a-63de-11e5-9094-67caf8bab67a.png)

**Comment by aniketnitj** [comment]
Taking latest package from nuget (using command Install-Package Hl7.Fhir) is not able to deserilize json. I took the latest code from git and it worked

**Comment by ewoutkramer** [comment]
Currently, the DSTU2 package is released as a "beta" package, to install it using Install-Package, add the switch -IncludePrelease to the command. This will install 0.90-beta1 for you, which will be able to read the examples. If you dont include this switch, you will get an older release, which predates dstu2!
