### ISSUE TITLE
Resource list properties can be set to null but never return null as their value

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#102]
```
public List<Hl7.Fhir.Model.Observation.ObservationRelatedComponent> Related
{
    get { if(_Related==null) _Related = new List<Hl7.Fhir.Model.Observation.ObservationRelatedComponent>(); return _Related; }
    set { _Related = value; OnPropertyChanged("Related"); }
}
```

Setting a property to something and then having it return a different value is not very nice

**Comment by ewoutkramer** [comment]
This design decision was made after extensive discussions with the .NET FHIR community during connectathons and also aligns with the most popular Java FHIR library HAPI.  Also, in FHIR's logical model, there is no difference between no element and an empty list of elements, in the sense that an element that has an empty list as value does not get serialized. So, "on the wire" there will not be any difference.  CAn you tell me whether this gives you any specific problems while working with the library?

**Comment by michelemottini** [comment]
The specific problem is that a bunch of unit tests that worked with the previous (DSTU 1) version of the library stopped working - so it is not really a problem, we can just change the tests - but it seems pretty weird to set a property and then have it return a different value - finding what was causing the unit tests problem took a while.

If this is the design decision close the issue and we'll fix our tests.

**Comment by ewoutkramer** [comment]
Ok! thanks, yes please fix your tests!
