### ISSUE TITLE
Parameters.GetSingleValue should return Element 

### ISSUE THREAD

**Issue by yunwwang** [ewoutkramer/fhir-net-api#103]
Current method signature is:
public T GetSingleValue<T>(string name, bool matchPrefix = false) where T : Primitive

But ParametersParameterComponent.Value is declared Element. So I cannot use this function to get value which is not Primitive, such as Coding.

Suggest to change the signature to 

public T GetSingleValue<T>(string name, bool matchPrefix = false) where T : Element

**Comment by ewoutkramer** [comment]
Yes, this is incorrect, will fix as discussed in Atlanta!

**Comment by brianpos** [comment]
I think this one is fixed.
Can you please confirm that this is good?

**Comment by ewoutkramer** [comment]
I have fixed this, but it will appear in the open issues list as long as it is not merged to master...
