### ISSUE TITLE
Implement static string property FhirTypeName on all FHIR types

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#104]
Convenient shortcut to ModelInfo.GetFhirTypeForType(typeof(...))
e.g. Patient.FhirTypeName => ModelInfo.GetFhirTypeForType(typeof(Patient)) => "Patient"

**Comment by brianpos** [comment]
We do have a virtual override which returns this from an instance of the class
`if (patResource.TypeName == "Patient") { ... }`
Just not a static one.

**Comment by ewoutkramer** [comment]
Yeah, but that does not work if you don't have an instance, so that's something I'd like to change, have this static property available on generated classes as well!

**Comment by brianpos** [comment]
Ok, will generate it...

**Comment by brianpos** [comment]
If I don't have an instance of a class, what do I have?
What am I calling the method on, or what is the parameter I'm passing?

**Comment by ewoutkramer** [comment]
I was thinking Patient.FhirTypeName?   Mostly, C# type = FHIR type, but this is not necessarily the case, so FhirDecimal.FhirTypeName = "decimal" for example....

We already have a instance-level *property* TypeName, so we need to have yet another const in the class called FhirTypeName. It's not really the cleanest solution, but I cannot think of another right now.

**Comment by brianpos** [comment]
Michel implemented ModelInfo.GetFhirTypeNameForType(Type type) does that cover these use cases?
Without polluting the debug/type experience?

**Comment by brianpos** [comment]
Can we close this now?

**Comment by wmrutten** [comment]
ModelInfo.GetFhirTypeNameForType(Type type) works fine, all good.
