### ISSUE TITLE
Implement ModelInfo.IsDomainResource

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#105]
Most FHIR resources are derived from DomainResource, except Binary, Bundle & Parameters.
To prevent clients from hardcoding these types, the API could expose a utility method IsDomainResource(string typeName) that indicates if the specified type is derived from DomainResource.

**Comment by ewoutkramer** [comment]
I guess this would be handy on a static-class level (given a name...), with instances you can just use the "is" operator of course.

**Comment by yunwwang** [comment]
In which situation such static method is called instead of using "is" operator on instance?

**Comment by brianpos** [comment]
If you;re at the class level, then you will be using reflection on the types, so you could use the type.isderivedfrom(typeof(DomainResource)) // or whatever that routine is called.
