### ISSUE TITLE
Move model generation to C# 

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#109]
(from the Atlanta WGM)

Currently, the C# classes are generated by the publication tooling and are writting in Java, based on an internal eCore representation. For maintainability, we'd like to move this to a t4 template approach. Which means we could maintain the code generation without the need to install Eclipse, ecore tooling, be able to run the build etc. etc. As well, this would enable the java build to become lighter and remove the eCore support.

**Comment by brianpos** [comment]
This is in progress in the ft-t4-generation branch
