### ISSUE TITLE
Research the "code-first" approach

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#110]
(from the Atlanta WGM)

Also considering if the code first approach will work and be possible
What do we need to add to the classes and attributes?

Code-first would allow you to create classes, enrich them with attributes and then extract profiling information from these attributes. General cases are easy to do, but slices and extensions are harder. Coordinate with James to see if we can align with HAPI.

**Comment by brianpos** [comment]
Still want to keep this one around?

**Comment by ewoutkramer** [comment]
It's still in my mind anyway, so I don't mind keeping it here for now.

**Comment by ewoutkramer** [comment]
I am not going to pursue this anymore. Closing this unless someone else has an urgent need and offers help.
