### ISSUE TITLE
New _summary feature on Conformance

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#112]
(Discussed during the Atlanta WGM)

Some conformance statements are huge (e.g. Grahame's > 1MB).  So, polling done by the client to verify server compatibilty can be truely costly (esp. in a mobile context).

Suggestion is to add a new server feature (adding _summary) and build support for this in the client.

**Comment by brianpos** [comment]
Will add the parameter using Hl7.Fhir.Rest.SummaryType as the type

**Comment by brianpos** [comment]
Now implemented using the SummaryType enum parameter type (optional)
complete with unit tests
