### ISSUE TITLE
Add logging support

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#113]
(discussed during the Atlanta WGM)

Logging support (specification library). Use log4net as default, but permit delegating to other destinations if developer desires it.

Problem is that baking in support for 1 kind of provider is problematic if you integrate this library into your own software and you use a different library.

Maybe look at a facade solution like https://slf.codeplex.com/?

**Comment by richardschneider** [comment]
I've used Common.Logging for a logging facade.  It's a well accepted solution.

https://github.com/net-commons/common-logging

**Comment by ewoutkramer** [comment]
In the 1.0 release, we have added the notion of `IExceptionSource` to components of the API that support generating log messages.  Logging can then be done by invoking any of the logging blocks based on the callbacks from `IExceptionSource`.

We will expand the use of `IExceptionSource` gradually, so more and more parts of the API can be logged.
