### ISSUE TITLE
Continue parsing a Bundle on error

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#114]
(from the Atlanta WGM)

Bundle parsing now stops completely when finding parser errors (unless these are unknown element issues, which are recoverable).

Multiple requests have come in to be able to partially parse a Bundle when this happens. This would require Bundle-specific code in the parser.

Questions are: would the invalid resource still be present in the parsed Bundle?  How would you know it was invalid? Is it “safe” to do this in production to ignore these types of data issues?

Some have configured the parsers to handle this as a “debug” setting so that diagnostics can be done during experimentation. Will need to do some research into the options in the parser so that potentially others can handle this situation themselves.

**Comment by yunwwang** [comment]
I think the parser could take an enum parameter with values like (stopOnError, reportErrorAndContinue, ignoreError, ...). And the value of the enum parameter is either set in configuration or as a request parameter from client.

**Comment by ewoutkramer** [comment]
I am proposing a totally different approach, one that we are currently already using on the large Bundles that make up the core zip:  we have lower-level (non-POCO based) readers for Bundles - these avoid reading a whole bundle in memory, and basically present the entries of a Bundle entry for entry to the client so you can parse the entries one by one into a POCO.  This way, when one poco fails parsing, you can just continue with the next entry.

We will have to look at the classes we created for this (JsonFileConformanceScanner in the Specification library) (specifically the `streamResources` method) and see whether we can make these generally available - maybe in a "event" based model where the caller gets an event every time the scanner finds a new entry to parse.

**Comment by brianpos** [comment]
Sounds like a good idea

**Comment by ewoutkramer** [comment]
These classes mentioned are now public and called `XmlNavigatorStream` and `JsonNavigatorStream`. You can parse them into POCOs, but also inspect them using FhirPath or navigating into the properties in a DOM/XPath like traverse (data.Children("identifier").Children("use").First()).  Also, the POCO parser will now allow illegal enums if you tell it to.  This should be enough to cover most of the usecases.
