### ISSUE TITLE
Modifier should be made optional for "_sort" parameter in SearchParams parsing

### ISSUE THREAD

**Issue by sunvenu** [ewoutkramer/fhir-net-api#115]
The url, if specified as ".../Patient?family=smith&_sort:=birthdate" should get parsed to have the default ascending sort.

**Comment by ewoutkramer** [comment]
I agree it should be able to parse _sort=birthdate (and fall back to the default), but "_sort:" would still be wrong. But currently, it does not accept either ;-)
