### ISSUE TITLE
EntryToHttpExtensions.ToHttpRequest - Prefer header is no always consider

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#119]
Why do we only set the Prefer header if the client specified Prefer.ReturnMinimal. Shouldn't we also allow the clients to specifically request for a representation?

**Comment by ewoutkramer** [comment]
```
if (bodyPreference == Prefer.ReturnMinimal)
                    request.Headers["Prefer"] = bodyPreference == Prefer.ReturnMinimal ? "return=minimal" : "return=representation";
```

That looks incorrect, the assignment already supports both cases. Indeed, why the if?
