### ISSUE TITLE
IConformanceResource common interface should expose xxxElement members

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#121]
The IConformanceResource interface defines all properties that are common for conformance resources. However the interface does not expose the associated "Element" type properties that are available on concrete classes, e.g. UrlElement, NameElement etc. This diminishes the usability of the common interface.

Suggestion: extend the IConformanceResource interface by exposing Element members for all relevant properties, i.e. UrlElement, NameElement, PublisherElement, StatusElement, ExperimentalElement.

**Comment by ewoutkramer** [comment]
Agree.
