### ISSUE TITLE
Markdown attribute values must encode newline & tab characters to preserve formatting

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#122]
The W3C XML standard specifies that an Xml reader should normalize whitespace in attribute values, i.e. translate newlines and tabs to spaces and collapse repeated spaces. However whitespace encoded as numerical entities (e.g. &#08; &#10; &#13; &#32;) is not normalized and deserialized as-is.

For FHIR Markdown values, whitespace is significant and should be kept as-is. To prevent whitespace normalization, the API should implement special serialization for Markdown values and explicitly encode all whitespace (tabs, spaces, newlines) to numerical entities.

**Comment by richardschneider** [comment]
What about using [xml:space](http://www.w3.org/TR/xml/#sec-white-space) attribute?

     <md xml:space="preserve">some     markdown     text.</md>

**Comment by ewoutkramer** [comment]
No, we should not.  The system that puts the markdown into the FHIR class model should escape any newlines, because only this editor knows where the author really meant to put a newline, and where it is just formatting of the xml (to prevent lines from getting too long for example).

**Comment by ewoutkramer** [comment]
Mmmmm....on second thoughts, when you fill out the class model, you don't know whether it would be serialized to xml or json

**Comment by brianpos** [comment]
This seems like could be a FHIR standard issue for the XML/json representation of newlines in strings/markdown rather than a FHIR client lib issue.
