### ISSUE TITLE
Identifier.Assigner may not be text

### ISSUE THREAD

**Issue by Illivion** [ewoutkramer/fhir-net-api#124]
Identifier.Assigner may be ResourceReference or text, according to http://hl7.org/fhir/datatypes.html#Identifier, but in current implementation (90.2) it may be only ResourceReference.

**Comment by ewoutkramer** [comment]
The "assigner" element is defined as a Reference(Organization), which means that the type in the C# class is indeed just "ResourceReference".  Where the spec says "Organization that issued id (may be just text)", this refers to ResourceReference.Display, so you do not have to set ResourceReference.reference, but can just set Display.

**Comment by ewoutkramer** [comment]
By the way, this is pretty unclear, I will file a change request for the spec to say "this may be just text in Reference.display"

**Comment by ewoutkramer** [comment]
Done, see http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemBrowse&feedback=Successfully+added+%5B%238979%5D&tracker_id=677
