### ISSUE TITLE
FhirSerializer.SerializeResourceToXml(medicationOrder, true) emits a resource with essentially no summary

### ISSUE THREAD

**Issue by wdebeau1** [ewoutkramer/fhir-net-api#126]
No matter what data is present in the MedicationOrder, only the id, meta/versionId, and meta/lastUpdated show up in the output

**Comment by wdebeau1** [comment]
Looks like Condition has a similar issue

**Comment by ewoutkramer** [comment]
Bill also found: Observation works, Condition doesn't

**Comment by brianpos** [comment]
This probably same issue with the child component summary stuff is in new t4 template code.
I'm this my today.
