### ISSUE TITLE
Create a Binary Resource returns wrong type.

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#128]
When creating a binary object on the server and the server returns the XML or JSON structure, then the ToBundleEntry incorrectly processes this content.

Also, while i'm here, if the server does return the binary data back, it should at least populate the VersionID and ID in the fabricated instance.
 if (IsBinaryResponse(response.ResponseUri.OriginalString))
                    result.Resource = makeBinaryResource(body, contentType);
                else
                {

**Comment by ewoutkramer** [comment]
So, we've learned that the server should not return xml/json, it would return the original binary content, not wrapped in xml/json. Then again, this original binary content could be xml/json of course, but that's another matter.

**Comment by ewoutkramer** [comment]
We should really follow up on this, since at the WGM there were others unsure of what the "correct" behaviour is. As well, our Spark test-suite also currently fails because of this.

**Comment by ewoutkramer** [comment]
This issue was discussed and documented here: http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=9258&start=0.

We should adapt the client to implement this resolution.

**Comment by marcovisserFurore** [comment]
The issue, which is  documented on gforce, is more an issue for the server builders. The client handles correctly.

Also the initial issue created by Brian was already solved by the API. So the Id and Version are set when we receive the data back in binary mode. I've created an unittest for it to prove it.
