### ISSUE TITLE
The _elements parameter should also be able to be specified in place of the _summary

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#133]
Include a capability to include the _elements for searching (and get) operations
as defined in the spec here: http://hl7.org/fhir/search.html#elements

**Comment by ewoutkramer** [comment]
You can have _elements, using the SearchParams class and overloads!

**Comment by brianpos** [comment]
I got so excited when i saw this, i thought you'd implemented the serializer part. I will get to that some day.

**Comment by ewoutkramer** [comment]
Ah, then I have good news for you ;-)  My colleague Emanuel is working on this right now! It turns out he needed to refactor the serializer quite a bit.  Haven't seen his PR yet, but he is close!
