### ISSUE TITLE
Make possible to pass extra headers for http requests perfromed by the FHIR client 

### ISSUE THREAD

**Issue by ramescuo** [ewoutkramer/fhir-net-api#134]
One example where this is needed is to pass the authorization token to access the resources. This is normally archived by adding an "Authorize" header with the token as content. The current FHIR client implementation does not support passing extra header or to set the Authorize header. This can be a property of the FHIR client class or the extra headers could be passed in an overloaded constructor of the FhirClient.

**Comment by brianpos** [comment]
There is a handler on the client to do this.
BeforeRequest (or something like that)
We have used it for exactly this purpose.

**Comment by ramescuo** [comment]
Thanks for the quick response! Indeed, I can add headers using OnBeforeRequest. Then I think that fulfills this need.

Thanks!
