### ISSUE TITLE
The FhirClient does not support conditional read

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#135]
As stated in the FHIR specification "Servers can return 304 Not Modified where content is unchanged since the If-Modified-Since date-time or the If-None-Match ETag specified or they can return the full content as normal. ", but currently the FHIRClient does not support this:
System.NotSupportedException: Server returned a status code '304', which is not supported by the FhirClient

**Comment by brianpos** [comment]
What would you like the fhirclient to do?
It doesn't have the resource to return.
Returning null could be problematic if not handled correctly.
(just as we were going to do for return minimal on a create where the server returns operation outcome on success instead of resource that was created.)

**Comment by CorinaCiocanea** [comment]
Yes, You have a point there. Mybae we should have an non-generic overload that would just return a resource that could be explicitly used by the client (the client app using FhirClient) in these cases?

**Comment by ewoutkramer** [comment]
I am thinking of a system we build on top of FhirClient that can hold an cache data (we need this for resolution of structdefs by a validator - no need to request them every time), but that would require more thinking.

**Comment by ewoutkramer** [comment]
Alternatively, the Fhirclient could return a specific exception that you can catch and then have your own caching strategy.

**Comment by angusmillar** [comment]
I just ran into the same problem. 
Maybe you could use and enhance the Refresh method you already have . 

`PatientOne = clientFhir.Refresh<Patient>(PatientOne)`

So if the user supplies the Resource the client API  gets the 'Meta.LastUpdated' and the VersionId from that resource and makes the ConditionalRead call. If the server returns [304 - Not Modified] then the client API just returns the resource they supplied unchanged, and if the server returns a resource, the changed resource, then you return this to the user. You could also give parameters to override 'Meta.LastUpdated' and the VersionId.
It does have the downside that the client user must have the full resource to make the call, but that is kind of the point in making this Conditional read. It's not perfect but it seems to be an option.

**Comment by ewoutkramer** [comment]
So, in the end I have changed the behaviour: the client will now process th 304 and throw a FhirOperationException (which has the status code), so you can handle it any way you like by having a conditional catch!

**Comment by tstolker** [comment]
Thanks, Ewout!
