### ISSUE TITLE
Json serialization looses precision for decimal values

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#136]
Hl7.Fhir.Serialization.FhirSerializer uses Newtonsoft.Json serialization. By default Newtonsoft.Json serializes both decimal value 6 and 6.0 as 6.0. These values might mean different things in certain cases.  See also furore-fhir/spark#22

Scenario for testing: Create an Observation with a Quantity of 6. Use FhirClient to send a "Create" request to a fhir server. specifying the   Client.PreferredFormat as json. Check the actual send json (the actual value of the quantity will be 6.0)

Newtonsoft.Json supports customization for how it serializes values, so that would probably be a good option for solving this.

**Comment by ewoutkramer** [comment]
Do you mean using this?

http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_ToString_1.htm

**Comment by ewoutkramer** [comment]
Actually, no, I am constructing a JObject with a JValue that has the correct value 6, but then probably the JsonWriter is messing this up. Have to find out how to change the behaviour for the JsonWriter...

**Comment by ewoutkramer** [comment]
Need to do this: http://www.newtonsoft.com/json/help/html/CustomJsonWriter.htm

**Comment by ewoutkramer** [comment]
Consider it done.
