### ISSUE TITLE
Incorrect text for FHIR_Comment element

### ISSUE THREAD

**Issue by cdaapi** [ewoutkramer/fhir-net-api#137]
![image](https://cloud.githubusercontent.com/assets/2333405/11560409/1eb7ce22-99b8-11e5-91dd-1b5272bd504a.png)

**Comment by ewoutkramer** [comment]
Funny. Will fix!

**Comment by brianpos** [comment]
Update code comments to:
"A Comment recorded against this element in the FHIR Resource"
