### ISSUE TITLE
DataContractAttribute or SerializableAttribute missing at Hl7.Fhir.Model.Id

### ISSUE THREAD

**Issue by jokkis0** [ewoutkramer/fhir-net-api#140]
Type 'Hl7.Fhir.Model.Id' cannot inherit from a type that is not marked with DataContractAttribute or SerializableAttribute.  Consider marking the base type 'Hl7.Fhir.Model.Primitive`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' with DataContractAttribute or SerializableAttribute, or removing them from the derived type.

**Comment by brianpos** [comment]
The other WebAPI FHIR servers do not use the standard serializers, instead use the serializers that are provided with this assembly.

**Comment by jokkis0** [comment]
ok, could you please add some more information how to resolve this?

**Comment by ewoutkramer** [comment]
I answered about a comparable problem here on StackOverflow:
http://stackoverflow.com/questions/21117815/hl7-fhir-serialisation-to-json-in-asp-net-web-api/21137069#21137069

**Comment by ewoutkramer** [comment]
Other than that, if only for consistency, I think we should add that attribte?
