### ISSUE TITLE
Missing target resource type in ModelInfo.SearchParameters for MedicationAdministration.medication

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#143]
`new SearchParamDefinition() { Resource = "MedicationAdministration", Name = "medication", Description = @"Return administrations of this medication resource", Type = SearchParamType.Reference, Path = new string[] { "MedicationAdministration.medicationReference", }, Target = new ResourceType[] { } }, ` - should be `...new ResourceTy[] { Medication }`

**Comment by ewoutkramer** [comment]
That's probably an error in the spec source file. Brian is rebuilding this part and is discovering errors in these files. So, we're working on this!

**Comment by michelemottini** [comment]
OK, thanks

The workaround was easy, so it is nothing urgent

**Comment by brianpos** [comment]
Glad I saw this now, Means I shouldn't expect that the comparison with the old one to be 100% matching as there are issues...

**Comment by ewoutkramer** [comment]
Indeed!

**Comment by brianpos** [comment]
This issue is also in the validation.xml.zip file too.

**Comment by brianpos** [comment]
Now resolved in the t4 template stream (haven't updated the validation.xml.zip file though)

**Comment by michelemottini** [comment]
There appear to be the same problem for `QuestionnaireResponse.subject` - the [specs](http://www.hl7.org/implement/standards/fhir/questionnaireresponse.html#search) say 'Any' but I'd say that't wrong, it should be `Patient` (?)

**Comment by ewoutkramer** [comment]
I can confirm that the newly generated ModelInfo.cs is now correctly generated and fixes both errors. Indeed the spec says Any, and this is what now gets generated.  There will have been good reasons for the O&O workgroup to have made this Any (I hope ;-), but that's beyond our scope!  You'd need to log a change request at http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemAdd&tracker_id=677 if you'd like to change this!

**Comment by michelemottini** [comment]
Thanks. Yes, i opened a ticket for that: http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=9174&start=0
