### ISSUE TITLE
FhirParser.ParseResourceFromXml allows for a resource to have multiple resources in the same <contained> tag

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#144]
`FhirParser.ParseResourceFromXml` allows parsing a resource with multiple resources in the same `contained` tag. It just takes the first one adn ignores all others.

After debugging this, the problem appears to be in the `XmlDomFhirReader.GetMembers()` method. Here for parsing an XElement we just take the `value = (XElement)elem.FirstNode;` and ignore any other nodes. We should probably check here the `Elements()` collection and throw an exception if there are multiple elements in it.

See also furore-fhir/spark#20

**Comment by ewoutkramer** [comment]
Yes, we should do that indeed.

**Comment by brianpos** [comment]
Is the expected fix for this to handle the invalid content as a collection, or to throw an exception?

**Comment by grahamegrieve** [comment]
It would be invalid. But you could choose to handle it...

I'd prefer an exception

Grahame

**Comment by ewoutkramer** [comment]
@CorinaCiocanea wants us to throw an exception, and I agree with that....

**Comment by ewoutkramer** [comment]
Will be fixed when basing the POCO parser on the new IElementNav based parsers - see #385 and #356

**Comment by ewoutkramer** [comment]
Fixed by PR #646
