### ISSUE TITLE
DeepCopy fails on Careplan f201

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#146]
It results in an exception: 

System.InvalidCastException: Unable to cast object of type 'Hl7.Fhir.Model.Quantity' to type 'Hl7.Fhir.Model.SimpleQuantity'.

I created a unittest for it in commit b2285d74b89aff0dea3b631b9dc0b9826b7bb3b2.

**Comment by ewoutkramer** [comment]
We'll have to change the code generation for the DeepCopy() method to handle the subclasses of Quantity properly. We can do this once @brianpos has finished writing the C# T4 template generation,

**Comment by brianpos** [comment]
Found the issue and verified a fix.
Changes will be in the t4generation stream till they get merged in.

**Comment by PBernhardt** [comment]
Brian or Ewout, is there an eta on getting an update with this fix published to nuget?

**Comment by ewoutkramer** [comment]
Well, yes, you can use the FHIR serializers too, but that's SLOW!  That's why I have added these. It's a work-around for now I guess. I probably won't be able to fix it before the WGM

**Comment by ewoutkramer** [comment]
Well, serialization + deserialization is how I did this before, but it's slow!  We are planning to release an update before the WGM, and it seems @brianpos found the issue.

**Comment by brianpos** [comment]
The updated generated code corerctly implements the DeepCopy routine
