### ISSUE TITLE
Problem searching for effective in Observation

### ISSUE THREAD

**Issue by jokkis0** [ewoutkramer/fhir-net-api#147]
Hi, 
I trying to search for a observation by effective (DateTime). 
I have tried this:
http://spark.furore.com/fhir/Observation?subject.identifier=12345&effectiveDateTime=2012-09-17
This does not give me any result. 
Could you please help me how the best way is to search for effective(period og dateTime)?

Thanks

**Comment by ewoutkramer** [comment]
Hi Joachim,

This is really a question for the Spark team, I am forwarding this question to them!

  Ewout


-----Original Message-----

**Comment by jokkis0** [comment]
Ok, thanks again. 
One other thinh regarding searching. I see at the code here on github, that that client have methods like "searchAsync" but in visual studio I cannot see that method at FhirClient. I am using DSTU 2.

**Comment by ewoutkramer** [comment]
These methods are only compiled in the Portable Class Library version. Correct, @brianpos ?

**Comment by brianpos** [comment]
The async stuff was too much maintenance while updating, so wasn't included.
You can however use the native async keyword and task.run to simulate this. Which I have done in a utility class for the pcl stuff. I could put this on for all.
