### ISSUE TITLE
Question: What is the correct way to do validation on a JSON serialized FHIR message?

### ISSUE THREAD

**Issue by davishoudek** [ewoutkramer/fhir-net-api#151]
XML validation seems to be straightforward but is there a good approach to validating a message serialized with JSON?

**Comment by ewoutkramer** [comment]
Actually, XSD validation is only the first step, the FHIR StructureDefinition for each resource (e.g. http://hl7.org/fhir/patient.profile.xml.html, skip the human readable HTML), which contains additional constraints not specified in the XSD.  The Java has a validator that is able to use these StructureDefinitions to validate xml and json, but this is not yet available for .NET..  For now you could use the library to convert json -> xml and then run your schematrons + xsd.

**Comment by dhcgn** [comment]
@ewoutkramer any suggestion for doing a schematron validation with .NET? At the moment I use Saxon-HE but this runs under IKVM.NET and is not .NET Core compatible.

**Comment by brianpos** [comment]
If you're validating FHIR content, you should really be using the FHIR validator that works on both XML and json and covers way more of the validation rules than the schematron/XSD or json schema can do.

**Comment by dhcgn** [comment]
Could I valdiate a HL7 CDA document with the FHIR validator?

The is part of my ClinicalDocument I want to valdiate:

        <ClinicalDocument xmlns="urn:hl7-org:v3">
          <realmCode code="DE" />
          <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040" />
          <templateId root="1.2.276.0.76.10.1020" />
          <id root="1.2.276.0.76.3645.239" extension="di-b02e97c1-3cea-4ed4-80cd-5d8a7386cee2" />
          <code code="11490-0" codeSystem="2.16.840.1.113883.6.1" displayName="Consultation note" />

**Comment by brianpos** [comment]
It really only validates FHIR resources, not HL7v2 or CDA
