### ISSUE TITLE
The WholeSystemOperation() and TypeOperation() overloads with a single parameter do not work

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#157]
Calling `fhirClient.WholeSystemOperation( "operation", new FhirModel.Parameters() )` works correctly, but calling `fhirClient.WholeSystemOperation( "operation" )` (that should be the same thing I presume) results in a `FormatException` 

Same thing for `TypeOperation()`

**Comment by ewoutkramer** [comment]
Ah, I changed the code (during the connectathon) so calls with no parameters will be changed into a call with an empty new Parameters() resource, but obviously, this needs to be done in other places as well.

**Comment by brianpos** [comment]
When we fix this one must remember to add a unit test for it too.

**Comment by ewoutkramer** [comment]
I see Brian reverted this change after I did this:

E.g.

            // Brian: Not sure why we would create this parameters object as empty.
            //        I would imagine that a null parameters object is different to an empty one?
            // if (parameters == null)
            //    parameters = new Parameters();

The only alternative would be to post an empty body - and sounds like a problem, so I changed it into an empty Parameters resource....

**Comment by ewoutkramer** [comment]
Fixed in 3c3605af36749bc33f2e13470eb80379d348c541, but will re-open if Zulip discussion leads to other conclusion
