### ISSUE TITLE
There appear to be no client method to get a specific version of a resource

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#158]
The equivalent of a [vread](http://www.hl7.org/implement/standards/fhir/http.html#vread)

(Very minor)

**Comment by ewoutkramer** [comment]
Well, I had them, but they are basically the same as Read(), it's perfectly allowable to pass Read() a location which contains /_history/xxx!

**Comment by ewoutkramer** [comment]
This will work perfectly fine:

```csharp
var loc2 = client.Read<Location>(ResourceIdentity.Build("Location", "1", "v2");
```

**Comment by ewoutkramer** [comment]
I see I even documented that explicitly in the <summary> xml documentation.

**Comment by michelemottini** [comment]
Got it, thanks!
