### ISSUE TITLE
There appear to be no client method to call version-specific operations

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#159]
I.E. the last item listed [here](http://www.hl7.org/implement/standards/fhir/operations.html#executing)

Very minor.

**Comment by ewoutkramer** [comment]
As far as I know, there are no version specific operations, except those working on tags, and even those are very well hidden in the spec ;-)   Did I overlook something?

**Comment by michelemottini** [comment]
I don't think there are standard version-specific operations, but from the [specs](http://www.hl7.org/implement/standards/fhir/operations.html#executing) it appears that a server can define those:

> Operations can be invoked on four types of FHIR endpoints.....A specific version of a resource instance (http://fhir.someserver.org/fhir/Patient/1/_history/4):

and so the client could need to call them. 

This is all super-minor of course. 

I came across this writing tests for our server: I wanted to try to call a version-specific operation to see if I got back the expected error ...

**Comment by ewoutkramer** [comment]
Mmmm...yes, agree. If the API allows you to call a version-specific meta operation, it should also allow the user to call any version-specific operation, and the meta operations should be built on top of that call, instead of doing a one-off.

Will review.

**Comment by marcovisserFurore** [comment]
To call a version specific meta operation you could try this:
```
newMeta = new Meta(); // create here your own meta data
fhirClient client = new FhirClient(testEndpoint);
var loc = ResourceIdentity.Build("Patient", "1", "v5");

client.AddMeta(loc, newMeta);
````

This works only for meta operations, which is also correct, because the specs says: 

> These operations involve only a specific version of a single instance of a FHIR Resource and exists **only to allow manipulation of profile and tag metadata of past versions**

But the API also provides version-specific operation calls in the FhirClient class:
```
newMeta = new Meta(); // create here your own meta data
fhirClient client = new FhirClient(testEndpoint);
var loc = ResourceIdentity.Build("Patient", "1", "v5");
var par = new Parameters().Add("meta", newMeta);

client.InstanceOperation(loc, "meta-add", par);
````
So the method InstanceOperation() is also capable of version-specific operations.

Hopefully this answers your issue.
