### ISSUE TITLE
Contradictions on CLS compliance?

### ISSUE THREAD

**Issue by tiloc** [ewoutkramer/fhir-net-api#161]
The AssemblyInfo.cs states: [assembly: CLSCompliant(**true**)]

However, the project suppresses compiler warnings CS3015 and CS3016 which indicate non-compliance. Removing the warning suppression reveals that the constructor for ReferencesAttribute and AllowedTypesAttribute is not CLS compliant, as it expects an array of strings.

**Comment by ewoutkramer** [comment]
Yep, I cannot fix those. So I removed the CLS compliancy, and then Brian re-enabled it again (I think). Then I just left it as is ;-)

The ReferencesAttribute is a problem, and I did not see an easy way to find alternatives for it... suggestions?

**Comment by tiloc** [comment]
I think in this day and age you can easily forego on CLS compliance. It used to be important until a few years ago to build libraries that could be consumed by C# and Visual Basic. Neither C# nor Visual Basic requires it anymore.
Achieving true CLS compliance for ReferencesAttribute and AllowedTypesAttribute is very trivial, but would require unrolling their public constructor into multiple constructors with 1,2,3... parameters. For ReferencesAttribute it would be 13 constructors, for AllowedTypesAttribute it would be 33 constructors :-)
I have proposed a pull request which consistently declares that the Assembly is not CLS compliant and thus also makes the suppressed warnings obsolete.

**Comment by ewoutkramer** [comment]
Ok, I don't mind removing it, will integrate your pull request

**Comment by brianpos** [comment]
One of the issues in the past was some properties that had the same name and different case.
VB can't handle that.
Just nervous that we introduce issues for VB...

**Comment by tiloc** [comment]
I see your point, dug out the Visual Basic, set up a mixed C# and VB project and VB really doesn't like case ambiguity much :-)
PR #164 amends PR #162 to keep future generations of contributors safe from breaking VB compatibility again.
BTW: Is there anybody outside of the Hl7.Fhir.Core package expected to attach the ReferencesAttribute or the AllowedTypesAttribute to their classes? If not, one might be able to make the constructor "internal" instead of "public". Then everything would be fully CLS compliant without any need to suppress warnings.

**Comment by ewoutkramer** [comment]
"BTW: Is there anybody outside of the Hl7.Fhir.Core package expected to attach the ReferencesAttribute or the AllowedTypesAttribute to their classes? If not, one might be able to make the constructor "internal" instead of "public". Then everything would be fully CLS compliant without any need to suppress warnings."

The intention was that you could write your own Resource, put these attributes on and then use the serializers. In which case they would necessarily be public....

**Comment by tiloc** [comment]
Weird, I had deleted the "BTW" part of my comment last night already. Don't worry, it is not possible and as I learn now also not desirable :-)
PR #164 does not contain such a change, only the VB fixes discussed above with Brian.

**Comment by ewoutkramer** [comment]
Oh, hahaha,  I pasted it from the mails I get when you add a comment ;-)
