### ISSUE TITLE
Missing "Required" property in ParticipantComponent when "RequiredElement" is also populated

### ISSUE THREAD

**Issue by anthonyyott** [ewoutkramer/fhir-net-api#179]
Hello, I'm new to FHIR (and HL7) and was trying to use your API to create an Appointment and serialize it to JSON. My goal was to match the example at (http://hl7.org/fhir/appointment-example-request.json.html) exactly. I noticed however that when I populated both the "Required" and "RequiredElement" properties respectively that the "Required" was not being serialized. The code that I'm using is below along with the results. Is this a bug or did I do something wrong setting up the Appointment? 

var appointment = new Appointment
                {
                    Id = "examplereq",
                    Text = new Narrative { Status = Narrative.NarrativeStatus.Generated, Div = "<div>Brian MRI results discussion</div>" },
                    Identifier = new List<Identifier> { new Identifier { System = "http://example.org/sampleappointment-identifier", Value = "123" } },
                    Status = Appointment.AppointmentStatus.Proposed,
                    Type = new CodeableConcept { Coding = new List<Coding> { new Coding { Code = "52", Display = "General Discussion"} } },
                    Reason = new CodeableConcept { Text = "Clinical Review" },
                    Priority = 5,
                    Description = "Discussion on the results of your recent MRI",
                    MinutesDuration = 15,
                    Slot = new List<ResourceReference> { new ResourceReference { Reference = "Slot/example" } },
                    Comment = "Further expand on the results of the MRI and determine the next actions that may be appropriate.",
                    Participant = new List<Appointment.ParticipantComponent>
                    {
                        new Appointment.ParticipantComponent
                        {
                            Actor = new ResourceReference { Reference = "Patient/example", Display = "Peter James Chalmers" },
                            Required = Appointment.ParticipantRequired.Required,
                            Status = Appointment.ParticipationStatus.NeedsAction
                        },
                        new Appointment.ParticipantComponent
                        {
                            Type = new List<CodeableConcept> { new CodeableConcept { Coding = new List<Coding> { new Coding { Code = "attending" } } } },
                            Required = Appointment.ParticipantRequired.Required,
                            Status = Appointment.ParticipationStatus.NeedsAction
                        },
                        new Appointment.ParticipantComponent
                        {
                            Actor = new ResourceReference { Reference = "Location/1", Display = "South Wing, second floor" },
                            // This field doesn't get serialized
                            Required = Appointment.ParticipantRequired.Required,
                            RequiredElement = new Code<Appointment.ParticipantRequired> { FhirComments = new List<string> { "  This resource auto accepts, so doesn't need negotiation  " } },
                            Status = Appointment.ParticipationStatus.Accepted
                        },
                    }
                };

                var data = FhirSerializer.SerializeResourceToJson(appointment);
                File.WriteAllText("FHIR Appointment.txt", data);

Here are the results:
{
    "resourceType": "Appointment",
    "id": "examplereq",
    "text": {
        "status": "generated",
        "div": "<div>Brian MRI results discussion</div>"
    },
    "identifier": [
        {
            "system": "http://example.org/sampleappointment-identifier",
            "value": "123"
        }
    ],
    "status": "proposed",
    "type": {
        "coding": [
            {
                "code": "52",
                "display": "General Discussion"
            }
        ]
    },
    "reason": { "text": "Clinical Review" },
    "priority": 5,
    "description": "Discussion on the results of your recent MRI",
    "minutesDuration": 15,
    "slot": [ { "reference": "Slot/example" } ],
    "comment": "Further expand on the results of the MRI and determine the next actions that may be appropriate.",
    "participant": [
        {
            "actor": {
                "reference": "Patient/example",
                "display": "Peter James Chalmers"
            },
            "required": "required",
            "status": "needs-action"
        },
        {
            "type": [ { "coding": [ { "code": "attending" } ] } ],
            "required": "required",
            "status": "needs-action"
        },
        {
            "actor": {
                "reference": "Location/1",
                "display": "South Wing, second floor"
            },
            //This is missing: "required": "required",
            "_required": { "fhir_comments": [ "  This resource auto accepts, so doesn't need negotiation  " ] },
            "status": "accepted"
        }
    ]
}

**Comment by mbaltus** [comment]
Required and RequiredElement both point to the same internal object. You would usually use just Required, since that works with a standard .Net datatype (a code from an enum in this case), whereas for RequiredElement you need to put your data into the FHIR datatype (an Hl7.Fhir.Model.Code).
So in your code you overwrite the value when you assign a code to RequiredElement.

**Comment by anthonyyott** [comment]
Mirjam your explanation makes perfect sense. However, in one of the FHIR examples it contains both as seen below. Is that a mistake in the example? 

`     "required": "required",
      "_required": {
        "fhir_comments": [
          "  This resource auto accepts, so doesn't need negotiation  "
        ]
      },
      "status": "accepted"`

**Comment by brianpos** [comment]
The reason for having the fhir type is so we can have extensions on that property. And we have the native type for convenience with existing things, such as data binding.
