### ISSUE TITLE
Not possible to specify reverse includes in the Search<> method

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#183]

**Comment by brianpos** [comment]
This works:
`
var b = clientFhir.Search<Practitioner>(new string[] { "_id=prac1", "_revinclude=Patient:careprovider:Practitioner" }, null, 3);
`

**Comment by ewoutkramer** [comment]
Yet another parameter and more overloads ;-) This is why I created the Query object, so you can fluently construct it, and then use it. Double check whether Query actually does _revinclude etc. and if the impact is small - also add it to the non-Query calls.

**Comment by ewoutkramer** [comment]
Added to all overloads. Fixed in b3f68860fa696d0e3da864fe1c182a9c14c557a2
