### ISSUE TITLE
Omitting _summary parameter from search calls

### ISSUE THREAD

**Issue by mbaltus** [ewoutkramer/fhir-net-api#184]
The API adds _summary=false to each search with FhirClient.Search. Although that is allowed and servers should ignore the parameter if they don't understand it, there have been cases where this has posed a problem. Could the API perhaps just omit the parameter from the call if it hasn't been set in the client?

**Comment by ewoutkramer** [comment]
Seems like a good change, otherwise you cannot talk to servers that do not support _summary indeed.

**Comment by ewoutkramer** [comment]
Did this back in september 2016 in 1c930903
