### ISSUE TITLE
Patient JSON not binding in POST service

### ISSUE THREAD

**Issue by shwetaskatdare** [ewoutkramer/fhir-net-api#186]
I am using a Patient JSON example from https://www.hl7.org/fhir/patient-example-f001-pieter.json.html,
it seems like when using that object in a POST service, I see a null reference exception on the 'Identifier' element.

**Comment by brianpos** [comment]
Posting to which server?
The unit tests for the library do a round trip on all resources to ensure they can dialogs to and from xml and json. And my fhir server has the same unit test that populates all samples into it.
(my server uses the client on for serialisation)

**Comment by shwetaskatdare** [comment]
Well I am a beginner trying to write a translation service to convert Fhir Patient object into a custom object.

**Comment by ewoutkramer** [comment]
You mean you are trying to convert the xml/json into a custom object, or you are translating an object from the FHIR .NET library into a custom object?

**Comment by shwetaskatdare** [comment]
Yes I am trying to convert the json into a custom object. 
void Post (Patient patient) {  /*do the conversion here */}

**Comment by Keathley3M** [comment]
Are you using WebApi and is that an action on a controller?
To ensure proper deserialization, you will need to create a MediaTypeFormatter for handling translating the json using the FhirSerializer from the FHIR .Net library.

Something like: https://github.com/furore-fhir/spark/blob/master/src/Spark.Engine/Formatters/FhirMediaTypeFormatter.cs

**Comment by sangwanvikas** [comment]
Hi @shwetaskatdare , Could you fix this issue? Would you like to share you solution? I am stuck with it.

**Comment by ewoutkramer** [comment]
Maybe this helps too: http://stackoverflow.com/questions/21117815/hl7-fhir-serialisation-to-json-in-asp-net-web-api/21137069#21137069

**Comment by brianpos** [comment]
or there is this article that is more recent
http://stackoverflow.com/questions/36499889/hl7-fhir-routing-with-advanced-search-and-modifiers-in-net/36569974#36569974

**Comment by shwetaskatdare** [comment]
I was able to fix this with a custom Json converter and using Fhir Parser to serialize Fhir resources. This allows me to have multiple fhir resources in a custom object. Thanks for your help.
