### ISSUE TITLE
MedicationOrder.Medication - Both a codedable concept and a reference?

### ISSUE THREAD

**Issue by Keathley3M** [ewoutkramer/fhir-net-api#187]
The type for MedicationOrder.Medication is of the generic type Element.
According to the FHIR specification, it can be either a reference to a Medication or a CodeableConcept http://www.hl7.org/fhir/medicationorder-definitions.html#MedicationOrder.medication_x_.

How should we discover the actual type within C#?

Thanks!

**Comment by Keathley3M** [comment]
This relates to the larger polymorphic types in general, not just MedicationOrder.
http://www.hl7.org/fhir/formats.html#choice

It seems that casting to each type may work (though for some things, it is a lot of casting).  If there is a better built-in way to handle this, please let me know.

**Comment by brianpos** [comment]
Not at present there isn't unfortunately.
