### ISSUE TITLE
Check vulnerability for XXE processing

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#190]
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

(as reported here for HAPI: https://github.com/jamesagnew/hapi-fhir/issues/339)

**Comment by brianpos** [comment]
Think we are good with this, the xmlreader days to ignore processing instructions.

**Comment by ewoutkramer** [comment]
James wrote a unit-test to test this:
https://github.com/jamesagnew/hapi-fhir/blob/3a0de6e6f81c8469d3ba0d4af291268721ef59a9/hapi-fhir-structures-dstu3/src/test/java/ca/uhn/fhir/parser/XmlParserDstu3Test.java#L2545

**Comment by ewoutkramer** [comment]
Verified by adding a new unit test. No vulnerability to report.
