### ISSUE TITLE
JSON input to XML output renders empty xmlns attributes in narrative

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#193]
Originally mentioned as [issue #81 on Spark](https://github.com/furore-fhir/spark/issues/81). See there for an example.

**Comment by angusmillar** [comment]
I'm seeing much the same problem but I'm not using Spark, I'm only using the FHIR API (STU3 May2016) creating a ValueSet and setting the narrative with a very simple table like so: 
```
        StringBuilder NarrativeString = new StringBuilder();
        NarrativeString.Append("<div>");        
          NarrativeString.Append("<p>This is some explanatory text</p>");
          NarrativeString.Append("<table>");
          NarrativeString.Append("<tr>");
              NarrativeString.Append("<td>");
                NarrativeString.Append("<span>Cell1</span>");
              NarrativeString.Append("</td>");
              NarrativeString.Append("<td>");
                NarrativeString.Append("<span>Cell1</span>");
              NarrativeString.Append("</td>");
          NarrativeString.Append("</tr>");
          NarrativeString.Append("</table>");
        NarrativeString.Append("</div>");
        Resource.Text = new Narrative();
        Resource.Text.Div = NarrativeString.ToString();
```

What comes out after seriaizing to XML is this narative element :
```
  <text>
    <div xmlns="http://www.w3.org/1999/xhtml">
      <p xmlns="">This is some explanatory text</p>
      <table xmlns="">
        <tr>
          <td>
            <span>Cell1</span>
          </td>
          <td>
            <span>Cell1</span>
          </td>
        </tr>
      </table>
    </div>
  </text>
```

**Comment by brianpos** [comment]
I note that your div element that you are putting into the structure doesn't have the namespace already declared. I believe you should be putting this into the content when you create it.
Are you expecting that the dotnet fhir client should detect that you didn't put it there and do it for you?
I would have expected that you code should have looked like this:
``NarrativeString.AppendLine("<div xmlns=\"http://www.w3.org/1999/xhtml\">");``

This is what I have in all my Narratives that I generate in sqlonfhir.

**Comment by angusmillar** [comment]
Thanks, Brian that worked a treat! I guess, given that without me specifying the namespace the fact that it did add the correct namespace to the first element lead me to believe that it was trying to do it for me, yet had a bug. Although now I know the trick all is good. Thanks again for you help.

**Comment by brianpos** [comment]
Maybe we could include some validation that throws an exception if you don't provide it, or at least a trace message and debugger break to slap the developer (that wont happen without a debugger attached)

**Comment by ewoutkramer** [comment]
I think the behaviour will become unpredictable if we do that, so I'd rather no do too much magic...
