### ISSUE TITLE
Add necessary functionality to Fhir Client to handle Smart On Fhir authorization tokens

### ISSUE THREAD

**Issue by Gjoll** [ewoutkramer/fhir-net-api#195]
The Smart on Fhir protocol requires http fhir messages to be sent with an http header["Authorization"]  value that is returned from the smart on fhir server during oauth2 initialization.

There is no way that I can see to add the authorization token to the fhir client so that it is sent with the http request, and hence no way that I can see to use the fhir client with smart on fhir.

**Comment by brianpos** [comment]
This is the code from my Bearer authorize unit test...
```
FhirClient validationFhirClient = new FhirClient("https://sqlonfhir-dstu2.azurewebsites.net/fhir/");
            validationFhirClient.OnBeforeRequest += (object sender, BeforeRequestEventArgs e) =>
            {
                // Replace with a valid bearer token for this server
                e.RawRequest.Headers.Add("Authorization", "Bearer XXXXXXX");
            };
```
Then you can just use the API as normal.

**Comment by Gjoll** [comment]
Brian - Many thx. That looks like what I am looking for.
