### ISSUE TITLE
JSON vs XML serialization differences

### ISSUE THREAD

**Issue by bnantz** [ewoutkramer/fhir-net-api#196]
There seems to be a performance difference between XML and JSON serialization that I do not understand.  See attached unit test which shows anecdotally that JSON is about 10x slower.  The Hl7.Fhir.Core.Serialization.ComplexTypeWriter code at line 98 seems to serialize things in JSON differently to support extensions?

Any guidance would be great as we are using this in active development now.  We would be happy to investigate or help with this if we can.

[FhirSerializationLoadTest.zip](https://github.com/ewoutkramer/fhir-net-api/files/247712/FhirSerializationLoadTest.zip)

**Comment by ewoutkramer** [comment]
I will soon rewrite the serializer, based on the new IElementNavigator interface, which will probably fix this. Stay tuned!

**Comment by ewoutkramer** [comment]
Fixed as part of #356 (PR #646).
