### ISSUE TITLE
Specialized Bundle Serializers

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#197]
Change the operation of the Bundle serializers to better handle the streaming of large bundles, permitting the inclusion of an event hook to be fired when time to serialize the actual entries in/out.

This is so that for large bundles don't have to have the entire bundle stream in memory, and can just immediately transmit the stream.
My use case will be to permit search bundles to not have to deserialize the content which is already in the bytestream ready to send (no need to parse then serialize to the wire).
This should improve the performance of the server in retrieval as reduces the amount of handling the content.
(I'm really just seeing if others had any thoughts on this operation and if they would use this if it was there)

**Comment by ewoutkramer** [comment]
The `JsonNavigatorStream` and `XmlNavigatorStream` where added to the API to support this usecase!  Heavily undocumented, but they do exactly what you ask for - a forward stream of data that you can either traverse without parsing, or parse per-entry!  Has resulted in substantial speed-ups in Forge.
