### ISSUE TITLE
Access to HTTP header

### ISSUE THREAD

**Issue by ArnieTeres** [ewoutkramer/fhir-net-api#198]
I need to add an Authorization label to the HTTP header but I do not see any public methods to do this. Do you have any advice on how to get an Authorization label into the header?

**Comment by tiloc** [comment]
Hi Annie, 
See closed issue #195 for example code. 
Tilo

**Comment by ArnieTeres** [comment]
Thanks Tilo.

_____________________________________________________
SIEMENS           Medical Solutions - Health Services
Arnold Teres Architect
syngo Development
Siemens Medical Solutions USA, Inc.
40 Liberty Boulevard
Mail Code: 65-3
Malvern, PA 19355-9998, USA
Phone:                                                   +01 (610) 448-6167
Mobile:                                                  +01 (610) 761-3334
mailto: arnold.teres@siemens.com <mailto:arnold.teres@siemens.com>
_______________________________________________________
