### ISSUE TITLE
Update parser to comply to DSTU2 technical update about entities

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#200]
Grahame posted this:

> A technical correction will be posted to DSTU2 tomorrow morning US time. The technical correction makes 2 changes to the published DSTU:
> - add a note encouraging implementers not to use XML entities (and referencing description of XXE attack on OWASP) 
> - update the validator included in DSTU2 to reject entities in XML (the real reason for the release)

We have code in the parser to explicitly _allow_ entities (but convert them to the unicode equivalent). This was done mostly because some of the examples had entities in them. Should we disable this code based on this TC?

**Comment by brianpos** [comment]
Is there anything more to do here?
I think we already validated this didn't we?

**Comment by ewoutkramer** [comment]
We still have the code in place to replace entities by their unicode equivalent. It seems we need to remove this?

**Comment by ewoutkramer** [comment]
So, we double checked that the vulnerability does not exist, and I think we're helping the user by replacing the entities by their unicode equivalent then?  I'll close this until someone complains.
