### ISSUE TITLE
Implement STU3 serialization changes

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#202]
[Grahame Grieve]
I am doing task 9168 now. This is the first time we've actively used inheritance in the data types. I'm finding many consequences in the reference implementations
- Check POCO generation for support for inheritance
- Make sure this leads to e.g. SimpleQuantity being serialized as SimpleQuantity, not Quantity

**Comment by aws-na-ss-usplu** [comment]
How can we assist to validate the generated POCO models can be used with [EF ](https://msdn.microsoft.com/en-us/library/dd456853(v=vs.100).aspx) and [WCF](https://msdn.microsoft.com/en-us/library/ms730035(v=vs.110).aspx)?

Raised my concerns in issues #210 and #73.

**Comment by ewoutkramer** [comment]
@aws-na-ss-usplu, if you could indicate how to add attributes/serialization methods to the POCO's to make them work with the native serializers, we'll be happy to look into that and change the POCO generators!

**Comment by aws-na-ss-usplu** [comment]
Hi @ewoutkramer,
What we are seeking may not be plausible, and just starting to research the possibility.  We will pull the source, and performs some investigation.  We currently can allocate a few hours (2-4) a week, and will keep you posted.
We are new to FHIR, and looking forward to participating in the upcoming developer training provided by HL7.
What is the recommended next steps if we want to be a contributor?

**Comment by ewoutkramer** [comment]
What I would do is this:
* Alter the generated .cs files that contain the POCO classes to make the standard .NET serialization work (if possible)
* Fork the repository, and try to change the macro's (like Template-Model.tt) to generate the POCO classes so they have these changes
* Do a Pull Request

Would that work?

**Comment by brianpos** [comment]
Or copy the loco and make changes till it works, then let us know and we can assist with the t4 templates. Then you can complete it and make a pull request

**Comment by aws-na-ss-usplu** [comment]
Hi @ewoutkramer and @brianpos, 

Our team was thinking the same, and we plan to start working on it over the next few days.  Thanks for the suggestions.  We will follow up early next week.

**Comment by brianpos** [comment]
When you are considering this there are a couple of things that you'll want to consider that the FHIR serializer/parser handles:

- support extensions
- filtering properties based on the summary_type enumeration
- multiple datatype properties (value[x] which must be serialized as valueString or valueDecimal... as defined by the resource)
- profiled datatypes? (changes in STU3 - Duration is a profile on Quantity)

**Comment by brianpos** [comment]
Now that we have the Sept 2016 Connectathon branch working for all examples and published as a NuGetPackage, can we close this issue?

**Comment by ewoutkramer** [comment]
What did we do with summarytype?

I guess we did the rest if we have a succesful roundtrip test ;-)
