### ISSUE TITLE
Gracefully handle unknown enumeration values

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#203]
Currently, the parser will signal a formatting error when it encounters an unknown enumeration value in a coded FHIR element.

Add a "lenient" or "less strict" mode to the parser to allow these values:
* Add a "RawValue" property to the base Code<T> class
* Set the value of "RawValue" to the value as read by the parser from the original data
* On error, set the (primitive) enumeration property to null

**Comment by ewoutkramer** [comment]
While discussing this enhancement, some other options were discussed:
* Add a special "InError" value to each enumeration to explicitly mark the error (it just being null being too subtle, and may not always be caught by the developer)
* Add a special "NotSet" vlaue to each enumeration, and make all enumeration properties non-nullable
(idem)

We have chosen to align with the HAPI Java designchoices here. As well, we think the "lenient" mode is useful just for some tools (i.e. editors or validators who want to be able to read a POCO and point out the errors), in which case the developer will be very much aware of the fact that he/she needs to check for the condition.

**Comment by ewoutkramer** [comment]
While implementing this feature, I realized we already had a natural place for the "original" string value: Primitive.ObjectValue (inherited by Code<T>), so you can now get/set this value, and it will represent the "raw" string as it was parsed/will be serialized.

**Comment by brianpos** [comment]
Maybe a code comment on it could help some too.
