### ISSUE TITLE
Feature request: expose display categories for resource types

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#208]
The official FHIR website groups resources into functional categories, e.g. on the resource list page:
http://hl7.org/implement/standards/fhir/resourcelist.html
It would be convenient if the API would expose these official display categories, so a client can display a (selection) list of resource types grouped by category. This would provide a familiar grouping to the user.
Note that the resource categories do not seem to be encoded in profile-resources.xml, so I guess this is currently hard-coded in the build tool. Alternatively, FHIR could define an official extension on StructureDefinition for this.
[Edit] Grahame Grieves confirmed on Zulip: "core team is ok with it, as long as teh definition of the extension is suitability minimal"

**Comment by ewoutkramer** [comment]
Don't think this is an API feature...if provided using an extension, the API will allow you to read it using an extension?  Do you need any specific API functionality for this?

**Comment by wmrutten** [comment]
I submitted a proposal for a new official extension on StructureDefinition:
http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=10076
If this will be be accepted and implemented, the API doesn't need to change at all.
