### ISSUE TITLE
Expose global mappings via code generation from MappingSpaces.xml

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#217]
FHIR defines a global set of mapping systems, via the file Svn\FHIR\build\source\mappingSpaces.xml.
It would be convenient if the API exposes a user-friendly (read-only) collection that represents the information in this file, by generating code from the underlying XML file. Also the API could include mappingSpaces.xml into validation.zip.

**Comment by ewoutkramer** [comment]
I don't really understand what's in this information?  Are these NamingSystem resources in disguise?  Or are these the mapping ids used in the ElementDefinitions, listed as used by core?

**Comment by wmrutten** [comment]
IIRC from discussion with Lloyd, this file defines all the available mapping systems for use in StructureDefinitions. This also implies that StructureDefinitions cannot introduce new global mapping systems, other than the ones officially defined in mappingSpaces.xml.
Lloyd suggested to implement a specialized mapping grid view in Forge, with structural elements listed vertically and all mapping systems listed horizontally, as defined by mappingSpaces.xml. I could implement the parsing logic into Forge itself, but it seemed to be a logical addition to the API based on code generation (as mappingSpaces.xml is fixed for specific FHIR release and won't change frequently). I already did some of the work (in local branch), but haven't had time to complete it due to other priorities.

**Comment by grahamegrieve** [comment]
>
> IIRC from discussion with Lloyd, this file defines all the available
> mapping systems for use in StructureDefinitions. This also implies that
> StructureDefinitions cannot introduce new global mapping systems, other
> than the ones officially defined in mappingSpaces.xml.
>
no that's not true. The build tool does require that everything goes in
mappingSpaces.xml, but this is a build tool restriction,

You can define any that you want. It's better if you reuse the mapping
spaces codes where they are defined, but even that it not necessary. You
SHOULD use the URLs where they are defined.


Grahame

**Comment by wmrutten** [comment]
Thanks for the clarification, Grahame.

**Comment by ewoutkramer** [comment]
Too specialized to add to the API - please parse it yourself if necessary.
