### ISSUE TITLE
Add Allowed Types to PropertyMapping

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#223]
PropertyMapping in Hl7.Fhir.Introspection tells me the ChoiceType, but not what the choices are. This is useful knowledge when dealing with value[x] items in searchparameters.

**Comment by brianpos** [comment]
In my implementations I'm starting to consider how the fluentpath stuff will help with this.

**Comment by brianpos** [comment]
In the current versions of the library, the SearchParameter objects created in the ModelInfo class have the actual binding information included, including the choice type selected.
(can you give a specific example so I can re-verify this)

**Comment by brianpos** [comment]
Any update on this before I close it?

**Comment by ewoutkramer** [comment]
The current generator actually does split out the allowed types in the metadata attribute:

E.g. Observation.Value:

[AllowedTypes(typeof(Quantity),typeof(Hl7.Fhir.Model.CodeableConcept),typeof(Hl7.Fhir.Model.FhirString),typeof(Hl7.Fhir.Model.FhirBoolean),typeof(Hl7.Fhir.Model.Range),typeof(Hl7.Fhir.Model.Ratio),typeof(Hl7.Fhir.Model.SampledData),typeof(Hl7.Fhir.Model.Attachment),typeof(Hl7.Fhir.Model.Time),typeof(Hl7.Fhir.Model.FhirDateTime),typeof(Hl7.Fhir.Model.Period))]
