### ISSUE TITLE
8 Unit tests failing or bad in Develop branch?

### ISSUE THREAD

**Issue by wpostma** [ewoutkramer/fhir-net-api#225]
In develop branch it seems there are 29 skipped (disabled) tests, and 8 failing tests, some of which seem to depend on external internet servers.  

Test Name:	FetchConformance
Test FullName:	Hl7.Fhir.Tests.Rest.FhirClientTests.FetchConformance
Test Source:	D:\dev\fhir-net-api\src\Hl7.Fhir.Core.Tests\Rest\FhirClientTests.cs : line 49
Test Outcome:	Failed

It seems in this case, in several places in the tests, this .au url is used:

http://fhir-dev.healthintersections.com.au/open

Should this be expected? Is the test bad or is the server bad?

Other failing tests, like FhirVersionIsChecked seem to be failing for similar reasons.
FhirClientTests.Search  appears broken on each of the available public test server urls:

Assert.AreEqual(2, result.Entry.Count);  // should have subject too

Fails, because result.Entry.Count == 1.

SerializeUnknownEnums appears to use some on-disk test data, which is being polluted during the test, but the assertion looking for the polluted data is failing. So whatever feature this test is covering has a regression, or the test is bad?

```

        [TestMethod]
        public void SerializeUnknownEnums()
        {
            string xml = File.ReadAllText(@"TestData\TestPatient.xml");
            var pser = new FhirXmlParser();
            var p = pser.Parse<Patient>(xml);
            string outp = FhirSerializer.SerializeResourceToXml(p);
            Assert.IsTrue(outp.Contains("\"male\""));

            // Pollute the data with an incorrect administrative gender
            p.GenderElement.ObjectValue = "superman";

            outp = FhirSerializer.SerializeResourceToXml(p);
            Assert.IsFalse(outp.Contains("\"male\""));
            Assert.IsTrue(outp.Contains("\"superman\""));
        }
```

**Comment by brianpos** [comment]
I'm actively working on these to get the develop build back into working order.
Made some progress last night, but more to do still.

**Comment by ewoutkramer** [comment]
All fixed now. Working on the release of the new version.
