### ISSUE TITLE
deceased[x] field not populated

### ISSUE THREAD

**Issue by schmidtaa** [ewoutkramer/fhir-net-api#232]
According to the FHIR spec at https://www.hl7.org/fhir/patient.html the following is the definition of deceased field:

. deceased[x]	?! Σ	0..1		Indicates if the individual is deceased or not
.... deceasedBoolean			boolean	
.... deceasedDateTime			dateTime	

Further, https://www.hl7.org/fhir/formats.html#choice

Choice of Data Types 
A few elements have a choice of more than one data type for their content. All such elements have a name that takes the form nnn[x]. The "nnn" part of the name is constant, and the "[x]" is replaced with the title-cased name of the type that is actually used.

Currently, FHIR.NET has patient serializing/deserializing field as deceased without suffix, i.e. deceasedBoolean or deceasedDateTime, which is looks like a bug.

**Comment by brianpos** [comment]
Which version of the library are you using that you believe is doing this?
This is an example from sqlonfhir which serializes using the DSTU2 .net FHIR client
http://sqlonfhir-dstu2.azurewebsites.net/fhir/Patient/pat4

**Comment by schmidtaa** [comment]
Hl7.Fhir.DSTU2.Core 0.90.4.20849

**Comment by ewoutkramer** [comment]
I see two issues here:

* About Deceased[DateTime/Boolean]: In the C# model, the field is called simply Deceased, and depending on the actual type (DateTime or Boolean), the correct field is output in the xml or json.
* Roundtripping is generally well-tested in our unit-tests so it would be interesting to see what is going wrong. If you want, you can attach the json file and I'll look into it.

**Comment by schmidtaa** [comment]
Looked again through sample JSON and mappings, turned out our mapping layer was introducing the data loss. Hence closing this issue.

**Comment by ewoutkramer** [comment]
No problem, thanks!
