### ISSUE TITLE
Cannot create Condition resource with onsetQuantity or abatementQuantity properties

### ISSUE THREAD

**Issue by povazhny** [ewoutkramer/fhir-net-api#234]
Cannot create **Condition** resource with `onsetQuantity` or `abatementQuantity` properties assigned.
The error message is: "Value is of type Hl7.Fhir.Model.SimpleQuantity, which is not an allowed choice". By the specification it has to be of type Hl7.Fhir.Model.Age.
I use `condition-example-f202-malignancy.json` file for testing. Where `onsetQuantity` is assigned to the following value:
```javascript
"onsetQuantity": {
    "value": 52,
    "unit": "years",
    "system": "http://snomed.info/sct",
    "code": "258707000"
  }
```
Hl7.Fhir.DSTU2 -Version 0.90.4

**Comment by ewoutkramer** [comment]
We did rewrite handling of Quantities in the parser in 0.90.5, but I think you might have found an issue here. The generated class indeed demands a Model.Age instance, but all we parse now is Quantity (onsetAge does not exist), so this validation rule should probably be disabled in the parser. @brianpos do you know more about this?

**Comment by brianpos** [comment]
I'll have to look into it.

**Comment by ewoutkramer** [comment]
We have fixed this ;-)  See #145 !

**Comment by ewoutkramer** [comment]
So, upgrading to 0.90.5 should help you out. Can you check?

**Comment by povazhny** [comment]
Thank you. I will check and inform you.
