### ISSUE TITLE
Support client certificates in FhirClient

### ISSUE THREAD

**Issue by magohl** [ewoutkramer/fhir-net-api#237]
I have a scenario where client certificates, as part of the SSL handshake, are used to authenticate the calling client to the server. This is probably more common in server-server scenarios such as Fhir Messaging.

_Suggestion:_
Add support for optionally specifying an X509Certificate2 in the FhirClient constructor that will be set in the underlying Requester HttpWebRequest using the ClientCertificates.Add(X509Certificate) method.

I made a simple test and it works fine.

Or is there a better extension point where i can set a client certificate to the HttpWebRequest?

**Comment by wmrutten** [comment]
I've implemented a simple certificate handler in Forge by overriding the default FhirClient. We can probably move this into the API.

**Comment by ewoutkramer** [comment]
Yes, @magohl, there are both events (e.g. OnBeforeRequest) and equivalent overrideable members in the FhirClient that provide hooks where you can alter the body and headers before the data leaves the client.

**Comment by magohl** [comment]
Perfect. I will override OnBeforeRequest and add the certificate to the HttpWebRequest. Thanks :)
