### ISSUE TITLE
Primitive.ToString() crashes when ObjectValue is null

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#244]
That seems wrong, because null is a valid value for various of the Primitive-derived classes (like FhirString for example)

**Comment by brianpos** [comment]
It shouldn't crash, but it isn't a valid case, the object should be null, not the value. It is not valid to have an empty/null string.
All attributes in Fhir must have a non empty value

**Comment by michelemottini** [comment]
Nothing prevents you to do `new FhirString(null)` - that is how I found the problem. Maybe the `FhirString` constructor should have a check preventing a null value then

**Comment by brianpos** [comment]
like I said, it shouldn't crash, but also isn't valid fhir, so at some point will get an exception.
Even if it is only when you try to save it with that and it gets validated.
Don't think we should stop it, but should pick the correct place for it to be validated.

**Comment by ewoutkramer** [comment]
I seemed to have fixed this already. Have added a unit-test just to make sure. See 9e5997c.
