### ISSUE TITLE
Implement full support for Xhtml DataType

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#257]
The API should provide full support for the Xhtml data type, similar to Markdown.

Currently the API lacks proper support for the Xhtml data type, e.g.
- FhirTypeToCsType dictionary does not contain an entry for "Xhtml" data type
- ModelInfo.IsPrimitive() returns false for Xhtml data type
- Xhtml class is not a proper data type representation but merely a static helper class; does not implement IStringValue (like Markdown data type)
- ...?

**Comment by brianpos** [comment]
I think this is already different in STU3, might want to check there

**Comment by ewoutkramer** [comment]
That's because in the end, XHtml was never used, I think the Narrative datatype just uses string in the end instead of XHtml. I am keeping this issue open, since I'd like to decide what to do with it. Stay or Go?

**Comment by ewoutkramer** [comment]
XHtml had been removed in DSTU2, but it is still present in STU3.  The difference with, say, Markdown is that Markdown is actually a FHIR datatype - it is used in elements that can have extensions etc. xhtml is only used in Narrative.div, which is actually a string (it's represented as an XML Text node). It's really an exception - and I think we should remove it from STU3 too.

**Comment by ewoutkramer** [comment]
Removed Xhtml in 0caed850a7b6e358ebac3aa933034b33878cebec.

**Comment by wmrutten** [comment]
OK, thanks for the background info.
