### ISSUE TITLE
Correct way to represent a list of resources.

### ISSUE THREAD

**Issue by Karrakunga** [ewoutkramer/fhir-net-api#260]
We're in the process of transferring our custom custom hl7 fhir objects to use fhir-net-api objects but have hit a small problem. We have an endpoint that returns a list of appointments rather than a single appointment resource. Our endpoints are using the FhirSerializer to SerializeToJson before sending to the client and I can't see any clear way of allowing the serializer to take a list.

Is there a recommended way of doing this?

**Comment by brianpos** [comment]
That is a bundle resource you need there.
It is the api array results, with support for paging information in it.

**Comment by Karrakunga** [comment]
Aha, looks just what I was looking for. Thanks!
