### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by oddbjornkvalsund** [ewoutkramer/fhir-net-api#263]
When adding "Hl7.Fhir.DSTU21": "0.90.6-alpha8" to my project.json I get the error message:

> error: Unable to resolve 'Hl7.Fhir.DSTU21 (>= 0.90.6-alpha8)' for '.NETCoreApp,Version=v1.0'.

Any plans for publishing a version compatible with .NET Core?

**Comment by ewoutkramer** [comment]
Yes, but see #178.

Also, there's no supported DSTU21 library, the 0.90.6-alpha8 was made for DSTU2 and STU3!

**Comment by wpostma** [comment]
Now that .net core 1.1 previews are starting to appear maybe we'll all have some success working on #178
