### ISSUE TITLE
Optimize DebuggerDisplay attributes

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#264]
Jared Par wrote an interesting blog about the DebuggerDisplayAttribute:

http://blog.paranoidcoding.com/2011/03/18/debuggerdisplay-attribute-best-practices.html

Apparently the debugger is quite slow to resolve and parse the format string arguments. Also the syntax is language-dependent, which could cause visualizers to fail when consuming the library from VB/F#. Jared therefore suggests to implement a single (private) method DebuggerDisplay that returns the formatted string.

**Comment by brianpos** [comment]
I thought I'd been doing that.
Where a more complex expression is produced is always the private DebuggeraDisplay prop. Others are just the variable string.
The exceptions I try and keep handled or avoided through if tests.
Mutating stuff, that sucks, and our collection auto initializers are exactly like this.

**Comment by brianpos** [comment]
Any updates on proposed changes, or can we close this now?
