### ISSUE TITLE
Nuget package failed to serialize resource

### ISSUE THREAD

**Issue by yunwwang** [ewoutkramer/fhir-net-api#270]
I am using Nuget package Hl7.Fhir.STU3 0.90.6-alpha7 and Hl7.FluentPath v0.4.0-alpha3. I get error when serialize resource to json/xml using FhirSerializer.SerializeResource(resource, writer);

Here is the exception:

An exception of type 'System.TypeLoadException' occurred in mscorlib.dll but was not handled in user code

Additional information: Could not load type 'Hl7.ElementModel.IValueProvider' from assembly 'Hl7.FluentPath, Version=0.4.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'.

**Comment by yunwwang** [comment]
correction the FluentPath version is v0.4.0-alpha3

**Comment by ewoutkramer** [comment]
Yes, I updated the FluentPath library after releasing the .NET API, and something is not right with the version bindings in that NuGet. I'll publish another NuGet drop later today, but you can fix it for now by installing a version 0.3.x of FluentPath instead of the 0.4.x version.
