### ISSUE TITLE
ConditionCreate incorrectly setting If-None-Exist header value

### ISSUE THREAD

**Issue by angusmillar** [ewoutkramer/fhir-net-api#272]
When performing a Conditional Create the API does not set the HL7 defined extension header "If-None-Exist"correctly. It does set it, just not with the correct value.

For instance, I see the "If-None-Exist" header set as:
`If-None-Exist: http://localhost:8888/test/stu3/fhir/Patient?identifier=5`
Yet according to the FHIR specification, I should see it set as:
`If-None-Exist: identifier=5`

I'm running STU3 Sept 2016 V0.90.6-alpha7

**Comment by brianpos** [comment]
Thanks for logging it. The sept branch is not likely to get updated, but will review this issue for the Jan build that will likely be done in a week or 2.

**Comment by brianpos** [comment]
Still an issue Angus?

**Comment by angusmillar** [comment]
Just tested again, it has not changed, I still get a header of: `If-None-Exist: http://localhost:8888/test/stu3/fhir/Patient?identifier=5`
here is the simple test case to set it up:
`
      // Prepare test patient
      Patient PatientOne = new Patient();
      PatientOne.Name.Add(HumanName.ForFamily("FhirMan").WithGiven("Sam"));
      PatientOne.BirthDateElement = new Date("1970-01");
      PatientOne.Identifier.Add(new Identifier(StaticTestData.TestIdentiferSystem, "5"));

      SearchParams SearchParams = new SearchParams().Where("identifier=5");
      try
      {
        var ResultOne = clientFhir.Create(PatientOne, SearchParams);
        TempResourceId = ResultOne.Id;
        TempResourceVersion = ResultOne.VersionId;
      }
      catch (FhirOperationException execOper)
      {
        Assert.Fail("Exception was thrown on Condition Create, message was: " + execOper.Message);
      }
`

**Comment by angusmillar** [comment]
Has not changed still the same problem, I updated the GitHub issue.

 

Angus Millar

Health Integration Specialist

Pyro Health
Mobile: 0481 059 995
 <mailto:angusmillar@iinet.net.au> angusmillar@iinet.net.au

 <http://pyrohealth.net/> PyroHealth.net

**Comment by ewoutkramer** [comment]
Fixed in 52519aeff36a299b20d67c33818e004496566f3c
