### ISSUE TITLE
Possible error in resolution of choice element names?

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#274]
dotnet > polymorph member validation error

Sean McIlvenna: I am getting an error "Encountered polymorph member patient, but is does not specify the type used". Can someone explain this to me?

Sean McIlvenna: ok... it seems to be related to Claim.patient

Sean McIlvenna: After I removed "patient" from claim, it parsed by fhir-net-api just fine

Sean McIlvenna: Debugging the code a bit, it seems that it thinks Claim.patient is a choice data type

Sean McIlvenna: And is looking for it to be something like "patientReference" instead of "patient"

Sean McIlvenna: I believe "patient" is correct, though... The spec shows it should be "patient" and always should be a data-type of "reference"

Sean McIlvenna: so I think this *might* be a bug in the fhir-net-api

Sean McIlvenna: @Ewout Kramer , can you comment when you get a chance?

Sean McIlvenna: perhaps it is just that I am using the wrong branch? I am using the ft-connectathon-sep2016 branch

Sean McIlvenna: should I switch branches to the ft-connectathon-jan2017 branch?

Sean McIlvenna: it seems there are some very recent commits to that branch, maybe it matches the build.fhir.org spec more than sep2016?

**Comment by brianpos** [comment]
The jan2017 branch is the one for the connectathon in San Antionio and is different to the build branch.
And it is also different to the Baltimore Sept2016 branch.

**Comment by brianpos** [comment]
No updates on the issue, so I'm going to close it. If you have more details, please provide them and re-open the issue.
