### ISSUE TITLE
InvalidOperationException: Nullable object must have a value

### ISSUE THREAD

**Issue by farax** [ewoutkramer/fhir-net-api#275]
I am trying to pass in a patient resource with an invalid date: 

`<birthDate value="1973-22-22" />`
 
The response is **InvalidOperationException: Nullable object must have a value**. Is there a way to make this response more specific?

**Comment by ewoutkramer** [comment]
Hi @farax, what do you mean by "to pass in", is this to the parser/serializer directly or are you doing a RESTful call on a server with this invalid data?

**Comment by brianpos** [comment]
Faraz works with me, I've got the details and will try and fix it.
The serializer gives this null message when parsing an invalid date value.

**Comment by ewoutkramer** [comment]
Great. Let me know if you have a reproduction test, we will build a new package in 5 hours from now, so we can still incorporate that change.

**Comment by ewoutkramer** [comment]
Any progress on this, @brianpos?

**Comment by brianpos** [comment]
I haven't got back to it yet. But will get to it sometime.

**Comment by ewoutkramer** [comment]
Can you make it in the july 2017 timeframe?  If not, we should remove it from that milestone...

**Comment by ewoutkramer** [comment]
I think the rewritten parsers will have fixed this issue by now. Hearing no feedback from @brianpos, I am closing this issue.
