### ISSUE TITLE
Validator not thread-safe

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#280]
Jon-Vidar Schneider said on chat.fhir.org:
We are using the new c# validation functionality. It seems that the code is not threadsafe. It started when we got some random errors. When running a test running 100000 tasks in parallell we are getting some random errors as well. To improve the performance in our service I have set the Validator object as static. I have attached the output.threadrun.xml

It works fine if I put a lock around validator.Validate(someXmlReader), that ofcourse reduces the performance.

The code for setting up the validator looks like this:
```csharp
var profilePath = Path.Combine(directoryInfo.FullName) + @"\Definitions";
var coreSource = new CachedResolver(ZipSource.CreateValidationSource());
var cachedResolver = new CachedResolver(
    new DirectorySource(profilePath, includeSubdirectories: true));
var combinedSource = new MultiResolver(cachedResolver, coreSource);
var settings = ValidationSettings.Default;
settings.EnableXsdValidation = validateXsd;
settings.GenerateSnapshot = true;
settings.Trace = showTrace;
settings.ResourceResolver = combinedSource;
_validator = new Validator(settings);
```

**Comment by ewoutkramer** [comment]
No, it's not threadsafe, and it won't be ;-)  The validator is built to validate one instance at a time, scaling out should be done by creating multiple instances.
