### ISSUE TITLE
XML Serialisation Issue

### ISSUE THREAD

**Issue by clarotech** [ewoutkramer/fhir-net-api#281]
When serialising resources that have plain text in the **text.div** element then the serialiser throws an exception. It would be helpful if a more meaningful exception was thrown to aid developers finding the issue.

See discussion here : https://chat.fhir.org/#narrow/stream/dotnet/topic/XML.20Serialise.20Error

**Comment by ewoutkramer** [comment]
Fixed in the new serializers that are part of 1.0.
