### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by svandelaarschot** [ewoutkramer/fhir-net-api#283]
Hello Ewout Kramer,

I have a question is there something like a Sandbox to test the FHIR API with something like
a test database with fake data ?

I'm asking this because we planning to support FHIR in our company.

Kind Regards.

**Comment by mbaltus** [comment]
You could use one of the [publicly available test servers](http://wiki.hl7.org/index.php?title=Publicly_Available_FHIR_Servers_for_testing). Or if you want to test locally, you could download and install the [Spark server](https://github.com/furore-fhir/spark) on your own system (see http://docs.simplifier.net/projects/spark-docs/en/latest/ for some installation guidelines).

**Comment by svandelaarschot** [comment]
Thank you very much !
