### ISSUE TITLE
query all patients

### ISSUE THREAD

**Issue by svandelaarschot** [ewoutkramer/fhir-net-api#284]
Is it possible to Query a list of patients not just like 1?

Trying to use something like:
```

var client = new FhirClient("http://spark.furore.com/fhir");
var Pat = client.Read<List<Patient>>("Patients");
```

**Comment by brianpos** [comment]
Please review the Fhir spec at http://hl7.org/fhir/search.html
This os for the DSTU2 version.

There is also the documentation for this lib here http://ewoutkramer.github.io/fhir-net-api/client-search.html

**Comment by mbaltus** [comment]
If you want to retrieve multiple results, that's basically a search, so you would use the client.Search method. Next to the documentation Brian pointed you to, you can also browse for information and ask these kind of questions on the [Google group for the FHIR .Net API](https://groups.google.com/forum/#!forum/fhir-dotnet).

**Comment by svandelaarschot** [comment]
Is sandbox.hspconsortium.org also supported ?

**Comment by brianpos** [comment]
This is not a bug with the FHIR client, so closing the issue
