### ISSUE TITLE
 Type 'SerializationUtil' exists in both Furore.Fhir.ElementsRendering and Hl7.Fhir.DSTU2 packages in the same namespace

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#288]
Referencing both packages and trying to use the SerializationUtil will throw an exception:

The type 'SerializationUtil' exists in both 'HL7.Fhir.FluentPath, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Hl7.Fhir.DSTU2.Core, Version=0.90.5.2, Culture=neutral, PublicKeyToken=d706911480550fc3'

**Comment by ewoutkramer** [comment]
This was cleaned up when moving to netstandard, so the (current) netstandard DSTU2 + STU3 packages will not have this duplicated anymore.
