### ISSUE TITLE
Improve error message for missing namespace on XML root element

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#289]
[Reported by Gunther Meyer from Allscripts]
An XML FHIR resource root element should always have the FHIR namespace declaration.
Currently, if the namespace is missing, then the XmlFhirDomReader.GetMembers() method throws an exception on the first child element (e.g. id). The generated exception message is confusing to the end user.
Suggestion for improvement: XmlFhirDomReader.GetMembers() should first check the root element for proper namespace declaration and throw a helpful error message if the root element is invalid.

**Comment by ewoutkramer** [comment]
Now the parser has been replaced with the IElementNavigator based parsers, this has been turned into an explicit unit-test and should work now.

Fixed in e873ab4436882ebf7c3e9204d666330d01911adc
