### ISSUE TITLE
ASP.net Core error  System.Private.CoreLib.ni.dll

### ISSUE THREAD

**Issue by nherzalla2017** [ewoutkramer/fhir-net-api#291]
When trying to run this code I receive the error below in asp.net core 1.0 👍 

 var client = new FhirClient("http://spark.furore.com/fhir");

            var pat = client.Read<Patient>("Patient/1");
            

Error :
An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code

**Comment by ewoutkramer** [comment]
Hi nherzalla, we have not yet tried to make the library work under asp.net core, so it is well possible this happens. @mharthoorn @cknaap @brianpos - is this correct?

**Comment by nherzalla2017** [comment]
When you think it would be available for asp.net Core.

Regards,
Nabeel.

**Comment by mharthoorn** [comment]
Could System.IO.FileNotFoundException not be the translation of 404?

**Comment by brianpos** [comment]
Note that we now have a branch on dotnetcore that we are working towards with VS 2017RC.
Feel free to grab that branch and test things out for yourself (DSTU2 only) and let us know.

**Comment by ewoutkramer** [comment]
Yes, check out the ft-develop-netstandard branche, we've used the 2017 stuff that came out last week. We're still working on it, so update often ;-)
