### ISSUE TITLE
Provide full symmetric support for JSON & XML

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#292]
Currently not all API features support both XML and JSON.
For example, DirectoryResolver only supports XML files.
Would be convenient if the API implements full symmetric support for both serialization formats.
Currently, this prevents API consumers such as Forge to fully support both serialization formats.

Nasty: need to gracefully handle duplicate resource instances with the same (canonical) url.
For example, folder could contain both XML as well as JSON representations of the same profile.
The DirectoryResolver should be able to handle this gracefully/transparently, e.g. by means of a configurable preferred format.

Note: not even mentioning RDF ...

**Comment by ewoutkramer** [comment]
Done!

**Comment by vadi2** [comment]
:+1:
