### ISSUE TITLE
DirectoryResolver should be more resilient to invalid input

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#301]
The DirectoryResolver may throw exceptions when encountering xml files in the target folder (or subfolder) that cannot be deserialized. The resolver should always try to complete the scan. Maybe the resolver can aggregate exceptions while scanning and expose them afterwards via a separate public Errors property, so a client application can inform the user?

**Comment by ewoutkramer** [comment]
Fixed by Michel's PR.
