### ISSUE TITLE
Missing Portable.DataAnnotations reference

### ISSUE THREAD

**Issue by n8allan** [ewoutkramer/fhir-net-api#303]
At least on .NET Core, unless Portable.DataAnnotations is explicitly references by the assembly, said assembly is reported missing at runtime.  The dependency probably needs to be made explicit.

Repro: new ASP.NET Core project, import the Hl7.Fhir.DSTU2 package, attempt to (de)serialize an object.

**Comment by ewoutkramer** [comment]
Hi n8allan, we're piloting a "true" netstandard version of the API for DSTU2. Would you like to test it to see whether the problem has been resolved?  Just reply here and I'll send it to you....

**Comment by n8allan** [comment]
Sure we'd be happy to.

**Comment by ewoutkramer** [comment]
Hi n8allan, I just published a 0.92.0-alpha version on NuGet, which is based on netstandard. Could you see whether this fixes your problem?
