### ISSUE TITLE
Port template generation from T4 to more future-proof system

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#306]
Including the comments from @jaime-olivares, @wpostma here, before these get los in the .NET core-issue (#178)

jaime-olivares commented on 11 Jan
@ewoutkramer , node is almost mandatory nowadays, as there is a clear trend to use it directly or via Gulp for scripting during development. Also, it is a key component when developing with Visual Studio Code. So, if you want to be truly cross-platform, I suggest to use it for replacing T4.
 @wpostma
     
wpostma commented on 11 Jan
As part of moving dot net core back to the .csproj xml msbuild project format, I believe the existing T4 tooling will start to "just work" again inside the IDE, but T4 is a pain even to support for regular .net framework users, because it never worked properly in continuous integration, as it was an IDE plugin originally and not part of even the classic .net msbuild world.

Moving to Node.JS based tooling would be an improvement because when it doesn't work or do what you want, you can fix it. T4 is a giant pile of legacy hurt. I no longer work at a place that uses fhir but since I've studied this, I thought I'd stop in and drop my two cents in.

Thanks so much to everyone who has worked on FHIR libraries for .net. The future of healthcare software interop is FHIR, and I'm sure this project will be the premier go-to library for .net FHIR.

**Comment by ewoutkramer** [comment]
I would personally love to move to something that's less dependent on VS features and that can be run as part of the build process. Right now, since we're not running the T4 templates and using a single input, bugs can creep in when running the templates again after a few months - common bitrot.  But re-doing the generation is quite time consuming, and I really need someone to step up and do this then.....

**Comment by ewoutkramer** [comment]
@wpostma, did you take this any further? I'd love to discuss progressing on this one...

**Comment by ewoutkramer** [comment]
No progress, closing this.

**Comment by BradBarnich** [comment]
We use a csharp script in our fork: https://github.com/CareEvolution/fhir-net-api/blob/multiversions/src/Hl7.Fhir.Core/Model/Generate.csx

**Comment by ewoutkramer** [comment]
Yes, I think @michelemottini showed me!  Since we only run it a few times per release & Brian has recently refactored it for R4, I have no impetus to change anything....
