### ISSUE TITLE
Stage 3: ONC-certified API

### ISSUE THREAD

**Issue by wahmedswl** [ewoutkramer/fhir-net-api#312]
Hi,

Meaningful Use Stage 3: ONC-certified API for your health care application, is this FHIR support this?

https://medium.com/@pavelsmirnov/meaningful-use-stage-3-onc-certified-api-for-your-health-care-application-bce9843eab01#.769ckf66o

Thanks

**Comment by ewoutkramer** [comment]
Yes, see the link you posted, FHIR is mentioned explicitly.
