### ISSUE TITLE
Support for STU3 ?

### ISSUE THREAD

**Issue by leo9223** [ewoutkramer/fhir-net-api#314]
When the support for stu3 is coming?

**Comment by ewoutkramer** [comment]
It's there, we published it just last friday:  https://www.nuget.org/packages/Hl7.Fhir.STU3

**Comment by leo9223** [comment]
Would you update the source code too?  On github

**Comment by brianpos** [comment]
It already is, on the develop-stu3 branch where it has been for a few weeks.
