### ISSUE TITLE
C-CDA to FHIR

### ISSUE THREAD

**Issue by wahmedswl** [ewoutkramer/fhir-net-api#315]
Hi, C-CDA to FHIR and FHIR to C-CDA mapping can be done? Any help would be appreciated.

Thanks

**Comment by tstolker** [comment]
Hi,

On the last Connectathon the guys from Lantana Consulting did a great demo of their progress on this subject. I believe it was a XSLT-based approach to transform from C-CDA to FHIR Composition.
Please check out http://www.lantanagroup.com/profile/rick-geimer/

Kindest regards,

Theo
