### ISSUE TITLE
Use a different namespace for the STU3 and the DSTU2 versions of the library

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#316]
E.g. `Hl7.Fhir2` and `Hl7.Fhir3` - so that they can be used side by side by code that must use both standards

**Comment by brianpos** [comment]
You can use namespace aliases as I have done with the fhirpathtester project which does use both.
Although this capability hasn't moved into dotnetcore, hoping it will soon.

**Comment by michelemottini** [comment]
I see, thanks

**Comment by ewoutkramer** [comment]
Is there something I need to add to the build to make this work?
