### ISSUE TITLE
Patient Resource - some Extentions are missing

### ISSUE THREAD

**Issue by sandeepac** [ewoutkramer/fhir-net-api#323]
"url": "http://varian.com/fhir/StructureDefinition/patient-status",
            "url": "http://varian.com/fhir/StructureDefinition/patient-patientType",
            "url": "http://varian.com/fhir/StructureDefinition/patient-isInPatient",
            "url": "http://varian.com/fhir/StructureDefinition/patient-patientTimeStamp",
I a m able to see the above extensions in extension list array

            "url": "http://varian.com/fhir/StructureDefinition/patient-complaints",
I a m not able to see the above extension in the extension list array

**Comment by mbaltus** [comment]
Can you give some more details about what you're trying to do, for example which API methods you are using, so we can investigate the issue?

**Comment by ewoutkramer** [comment]
Closing this issue, as we have not heard from the author again and we cannot reproduce based on the current comment.
