### ISSUE TITLE
Latest NuGet fails to install

### ISSUE THREAD

**Issue by babelshift** [ewoutkramer/fhir-net-api#332]
The following occurs when installing the latest STU3 or DSTU2 packages:

```
install-package Hl7.Fhir.STU3
Unable to find a version of 'Hl7.FhirPath' that is compatible with 'Hl7.Fhir.STU3 0.93.0 constraint: Hl7.FhirPath (>= 0.4.2)'.

install-package Hl7.Fhir.DSTU2
Unable to find a version of 'Hl7.FhirPath' that is compatible with 'Hl7.Fhir.DSTU2 0.92.0 constraint: Hl7.FhirPath (>= 0.4.2)'.
```

Looking at nuget.org reveals that `Hl7.FhirPath` 0.4.2 has not been published.

**Comment by ewoutkramer** [comment]
Hi Justin!  My mistake, I noticed it last night and pushed the latest version so it should be alright now!  Thanks for notifying me & let me know if you still encounter problems.

**Comment by babelshift** [comment]
It worked. Thanks.
