### ISSUE TITLE
Make it possible to disable certification validation

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#335]
I am using of Hl7.Fhir.Rest.FhirClient and wanted to check if it will be possible to add a callback to ignore certificate errors in FHIRClient? Similar to 
 
``` 
_httpclient = new HttpClient(new WebRequestHandler() {ServerCertificateValidationCallback = ValidateServerCertificate}); 
  
private bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslpolicyerrors) 
{ 
            return true; 
} 
```

This will help us ignore certificate errors in development environment.

**Comment by brianpos** [comment]
The code that I use for this is as below. But suggest can be safer if you don't just return true, but check that its your dev env case, then not as bad if it does sneak into production.
``            System.Net.ServicePointManager.ServerCertificateValidationCallback += (sender2, cert2, chain, sslPolicyErrors) => true;
