### ISSUE TITLE
Custom Resource

### ISSUE THREAD

**Issue by sandeepac** [ewoutkramer/fhir-net-api#337]
How to access the Custom Resource using the .net client?

**Comment by sandeepac** [comment]
More Info: Department resource is a custom resource. Inherited from domain resource.

**Comment by ewoutkramer** [comment]
Hi @sandeepac, the only way to handle custom resources currently is to create a StructureDefinition for it, add it to the profiles-resources.xml file in the Model/Generated/Source directory, and rerun the T4 templates - you'll get your own version of the .NET library, with a POCO for your own resources....

**Comment by sandeepac** [comment]
Thanks @ewoutkramer , We will try the solution.

**Comment by sandeepac** [comment]
Hi @ewoutkramer, I have tried to rerun the Template-Model.tt by right click-> Run custom tool. I am getting the error(as attached). This is with the original profiles-resources.xml file. Is there any sequence in which the T4 templates need to be re-run or Is there any tool that we can use the run the T4 templates. 
I have opened the solution in VS 2017 and .Net framework is 4.5. 
![image](https://user-images.githubusercontent.com/27281649/29766107-4758f70c-8bfb-11e7-9619-a11c711774fd.png)

**Comment by ewoutkramer** [comment]
Hi @sandeepac, you're doing the same thing I am doing & using the same tools ;-)    What branch are you using?

**Comment by ewoutkramer** [comment]
This may help too: Make sure you never accidentally run the TemplateFileManagerV2.1.ttinclude file separately. If so, just remove the associated .cs file and try again.

**Comment by sandeepac** [comment]
There was a newline character at the end of TemplateFileManagerV2.1.ttinclude file, removed that. It is working now. Thanks.

**Comment by ewoutkramer** [comment]
Yes, I think adding this to .csproj will avoid some of this trouble:

    <None Update="Model\Generated\TemplateFileManagerV2.1.ttinclude"> 
      <Generator>TextTemplatingFileGenerator</Generator> 
      <LastGenOutput>TemplateFileManagerV2.1.cs</LastGenOutput> 
    </None> 

since this stuff is literally included in the other .tt files, it should never be compiled all by itself.

**Comment by mzocco** [comment]
Hi to everyone; I have a problem in deserializing a custom class containing some fhir object in it.

For example a CustomClass extending the DomainResource and containing as class variable a Patient instance and other variables (booleans, string...).

Does exist a way to register a custom resource type in C# using the FHIR C# library (without modifying the profiles-resources.xml file) and to deserialize it in a Contoller?

Thanks in advance.
Matteo
