### ISSUE TITLE
ListCopyExtensions.DeepCopy is not consistent with DeepCopy() semantics

### ISSUE THREAD

**Issue by mattiasflodin** [ewoutkramer/fhir-net-api#338]
The behavior when calling `DeepCopy()` on a `List<Resource>` (i.e. by using `ListCopyExtensions.DeepCopy`) violates the principle of least surprise and could lead to bugs, because it does not actually create a copy of the list.

**Comment by wmrutten** [comment]
Could you describe how the current implementation could lead to unforeseen issues?
ListCopyExtensions.DeepCopy uses LINQ Select to return an IEnumerable sequence of list item copies. This prevents the caller from modifying the original, underlying List instance. And calling e.g. ToList() on the result returns a new List instance, separate from the original.

**Comment by mattiasflodin** [comment]
It's still possible for the original list to be modified though, and in doing so the copy will also be modified.

**Comment by ewoutkramer** [comment]
Yes, if you modify the original before you have enumerated all the copies, this may happen. 

I'd say we should put a .ToList() at the end then?

            return source.Select(item => item != null ? (T)item.DeepCopy() : default(T)).ToList();

**Comment by mattiasflodin** [comment]
Yeah that would be a good solution.

**Comment by ewoutkramer** [comment]
Fixed in 28541122717bc961cf586d3d93c6ae7ccd2d2eae
