### ISSUE TITLE
Annotation.Author is in invalidate date type?

### ISSUE THREAD

**Issue by u8621011** [ewoutkramer/fhir-net-api#342]
in annotation spec: https://www.hl7.org/fhir/DSTU2/datatypes.html#Annotation

author seems should be type of reference but the implemtation is type of element.

**Comment by mbaltus** [comment]
Annotaion.author is a choice data type. You can choose either a reference, or a string to be filled in for this field. To accommodate for this choice, the api uses the parent data type Element. You will have to make sure that your implementation chooses one of the valid derived types - in this case string or reference.

**Comment by u8621011** [comment]
@mbaltus Do you mean, the red box in fhir spec is "choice data type" ? eg, i can use as authorReference or authorString?
![image](https://cloud.githubusercontent.com/assets/271116/26091782/ec773428-3a3f-11e7-9075-dee2f9d59db8.png)

**Comment by brianpos** [comment]
Yes, that means it can be either a FhirString, or a ResourceReference

**Comment by wmrutten** [comment]
@Brian, interesting suggestion. This would require some work on the T4 templates in order to generate the required validation logic from the available type choices (unless any type is valid). Templates currently already perform the work of generating the AllowedTypes annotation, so it wouldn't be that much effort.

**Comment by brianpos** [comment]
If others are happy with the thought, i can implement it.
(yes t4 template update)

**Comment by ewoutkramer** [comment]
I am hesitant to add validation to the POCOs. For a few reasons:
* Validation is another concern that is done by validators, not the POCO models
* Where would we stop?  We don't run the regex patterns on the values of primitives either.
* Many of these elements will be profiled to smaller sets, so you'd need to run the validation anyway...
