### ISSUE TITLE
FhirClient Async Methods in .NET Standard

### ISSUE THREAD

**Issue by jlbeard84** [ewoutkramer/fhir-net-api#343]
Are there any plans to again support async methods with FHIRClient?

**Comment by brianpos** [comment]
Not immediately but might consider it.
What's your particular usage

**Comment by jlbeard84** [comment]
I have a web app with a data layer that is calling out to a FHIR api. I'm going to have to aggregate a couple calls and ideally this would happen asynchronously.

**Comment by ewoutkramer** [comment]
Two weeks ago, I received an email from a .NET API user who is now working on it. I'll ask him to reply to this thread.

**Comment by ricardopinedathen** [comment]
Hello! I am working with implementing async methods on the client API. I should have something ready in a couple weeks or less. This involves adding new async methods to all regular FHIR calls.

Here's an example of how you would make multiple calls and wait for all of them asynchronously:

`[Test]
        public async Task SearchMultiple_NeoDeckServer_SearchReturned()
        {
            var client = new FhirClient("https://api4.hspconsortium.org/neodeck/open");
            client.PreferredFormat = ResourceFormat.Json;
            client.ReturnFullResource = true;

            var srch1 = new SearchParams()
                .Where("name=Daniel")
                .LimitTo(10)
                .SummaryOnly()
                .OrderBy("birthdate",
                    SortOrder.Descending);
            var srch2 = new SearchParams()
                .Where("name=Daniel")
                .LimitTo(10)
                .SummaryOnly()
                .OrderBy("birthdate",
                    SortOrder.Descending);
            var srch3 = new SearchParams()
                .Where("name=Daniel")
                .LimitTo(10)
                .SummaryOnly()
                .OrderBy("birthdate",
                    SortOrder.Descending);
            
            var task1 = client.SearchAsync<Patient>(srch1);
            var task2 = client.SearchAsync<Patient>(srch2);
            var task3 = client.SearchAsync<Patient>(srch3);

            await Task.WhenAll(task1, task2, task3);
            var result1 = task1.Result;
            while (result1 != null)
            {
                foreach (var e in result1.Entry)
                {
                    Patient p = (Patient)e.Resource;
                    Console.WriteLine(
                        $"NAME: {p.Name[0].Given.FirstOrDefault()} {p.Name[0].Family.FirstOrDefault()}");
                }
                result1 = client.Continue(result1, PageDirection.Next);
            }

            Console.WriteLine("Test Completed");
        }`

**Comment by jlbeard84** [comment]
Great! This is exactly what I'm doing already with some non-fhir web calls, so this will fit in perfectly. Please let me know if you need any help with code or testing. I was about to start writing this for a pull request. :)

**Comment by ricardopinedathen** [comment]
Will do!

**Comment by brianpos** [comment]
I had it implemented this using extension methods (which is not ideal, but works fine)

**Comment by ricardopinedathen** [comment]
I'm almost done with all async methods, if interested please take a look at:

https://github.com/ricardopinedathen/fhir-net-api

The integration tests on the project were not working correctly because of the servers, so I've been creating new ones for the things I'm adding/changing, if anyone likes to create integration tests let me know!

**Comment by ewoutkramer** [comment]
Yes, integration tests are a problem in this regard - it's worthwhile testing against real servers, but these are not always stable. I have excluded these tests in the CI build anyway.

**Comment by ewoutkramer** [comment]
@ricardopinedathen Thanks for picking this up!

**Comment by ricardopinedathen** [comment]
Just finished FhirClientOperations.cs tonight, my own tests are working fine, but I need more tests to make sure everything works correctly, will be doing that this week.

@jlbeard84 can you do some testing with your client to see if it works for you?
https://github.com/ricardopinedathen/fhir-net-api  /develop branch

Sample test:

````cs

public class OperationTests
    {
        private string _endpoint = "https://api.hspconsortium.org/rpineda/open";
        [Test]
        public async Task InvokeTestPatientGetEverything()
        {
            var client = new FhirClient(_endpoint);
            var start = new FhirDateTime(2014, 11, 1);
            var end = new FhirDateTime(2020, 1, 1);
            var par = new Parameters().Add("start", start).Add("end", end);

            var bundleTask = client.InstanceOperationAsync(ResourceIdentity.Build("Patient", "SMART-1288992"), "everything", par);
            var bundle2Task = client.FetchPatientRecordAsync(ResourceIdentity.Build("Patient", "SMART-1288992"), start, end);

            await Task.WhenAll(bundleTask, bundle2Task);

            var bundle = (Bundle) bundleTask.Result;
            Assert.IsTrue(bundle.Entry.Any());

            var bundle2 = (Bundle)bundle2Task.Result;
            Assert.IsTrue(bundle2.Entry.Any());
        }
    }`

**Comment by jlbeard84** [comment]
@ricardopinedathen Sorry, I've been swamped this week and haven't been able to work on any tests. I'll pull this into my project tomorrow and give it a shot. Thanks!

**Comment by ewoutkramer** [comment]
I will have time this week to merge your PR, if you are ok with it!

**Comment by ricardopinedathen** [comment]
Sounds great! Let me know if you have any issues. @jlbeard84  were you able to test this with your project?

**Comment by ewoutkramer** [comment]
I have pulled this PR into dstu2, will soon port it to STU3 too.....
