### ISSUE TITLE
Bundle extensions

### ISSUE THREAD

**Issue by babelshift** [ewoutkramer/fhir-net-api#344]
Since a Bundle is a Resource, shouldn't it support extensions? There is currently no property on the Bundle object (STU3) to access a Bundle's extensions.

**Comment by mbaltus** [comment]
Bundle is a Resource, not a DomainResource. Only DomainResources have the extension property.
So it is correct the Bundle cannot have extensions on the top level, but the Bundle properties can be extended.

**Comment by wmrutten** [comment]
Note: Bundle elements are derived from Element and they have extensions.
But as Mirjam explains, you cannot extend the Bundle root element, as defined by the FHIR spec.

**Comment by babelshift** [comment]
Thanks all. I understand now.
