### ISSUE TITLE
Update model to latest 3.0.1 version

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#346]
For the sake of stability, we have not yet updated the generated models to 3.0.1.

**Comment by brianpos** [comment]
Yes it has. NuGet package hasn't been released though 
I did that at the start of the connectathon.

**Comment by brianpos** [comment]
It's already done and pushed back in Madrid.

**Comment by brianpos** [comment]
I left it open till the NuGet package is pushed.

**Comment by ewoutkramer** [comment]
Ok, so I've added it to the July 2017 milestone, I'll close it now.
