### ISSUE TITLE
Use of expansions.xml

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#347]
* Verify whether our current in-mem term expander can handle all expansions in the core spec
* If not, consider using the expansions.xml version of these valuesets instead (manually including them?)

**Comment by brianpos** [comment]
That file isn't a complete set, but i guess is better than nothing.

**Comment by ewoutkramer** [comment]
I have had no questions or requests about this ever since, so I am closing this until an urgent usecase comes up.
