### ISSUE TITLE
Remove use of Seek() from SerializationUtil.cs

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#348]
This function should not be responsible for doing this + not all streams support Seek(), even though SupportsSeek() suggests otherwise....

**Comment by ewoutkramer** [comment]
Ok (he said to himself), but I am pretty sure this will have other side effects. Try this and see what happens with the unit-tests

**Comment by brianpos** [comment]
Thanks, then can use zipstreams directly.

**Comment by ewoutkramer** [comment]
Fixed in f931edb
