### ISSUE TITLE
API generates invalid XML/Json on empty values

### ISSUE THREAD

**Issue by mbaltus** [ewoutkramer/fhir-net-api#354]
When you set a (string) value to an empty string, and then send the resource to a server with the FhirClient.Create method, the resource sent has empty elements in it.
For example I set `patient.Id = ""` in my code, resulting in `<id value="" />` in the XML. 
I know I shouldn't put empty strings in resource values, but perhaps the API could check that for me and just not generate the element, or throw an error before sending?

**Comment by ewoutkramer** [comment]
Mmmmmm..... FHIR indeed does not have the notion of empty strings.

I could chose to not serialize elements with an empty string - unless they have extensions, but in that case the `value` attribute should still not be present.

**Comment by ewoutkramer** [comment]
Fixed as part of PR #646.
