### ISSUE TITLE
Deserializing a profiled resource fails

### ISSUE THREAD

**Issue by kennethmyhra** [ewoutkramer/fhir-net-api#359]
Hi,

I have created an implementation of [SDF-Questionnaire](https://simplifier.net/Digitaleskjema/SDF-QuestionnaireResponse), using the fhir-net-api, which is extending Questionnaire, see https://github.com/kennethmyhra/fhirplayground/blob/master/SDFQuestionnaire.cs.

I have changed the cardinality of a few of the properties and added some extensions. I can serialize it to [JSON](https://pastebin.com/JvJTPXHT) without problem.

When trying to deserialize the ModelInspector cannot find the FHIR type SDF-Questionnaire, which when reviewing the code is as expected since [the ModelInspector is only populated with FHIR types from Hl7.Fhir.Model](https://github.com/ewoutkramer/fhir-net-api/blob/develop-stu3/src/Hl7.Fhir.Core/Serialization/FhirParser.cs#L166).

I am not sure if there is another way of getting hold of the ModelInspector than exposing it as a public property via BaseFhirParser, see the following commit: https://github.com/kennethmyhra/fhir-net-api/commit/bbba38f8249ff0caca1efb608d25ccd42766a147

With the previous change I can then import the needed types in various ways, for example:
- `BaseFhirParser.Inspector.Import(Assembly.GetExecutingAssembly());`
or
- `BaseFhirParser.Inspector.ImportType(typeof(SDFQuestionnaire));`

This works, but it doesn't look very intuitive or elegant. Is there a different way of registering my own FHIR types which I am missing?

**Comment by kennethmyhra** [comment]
@ewoutkramer Would appreciate if you could help me out with this one.

I guess my question could be rephrased to, how do I represent a profiled resource using the Hl7.Fhir.Api.

**Comment by mbaltus** [comment]
Should the FhirType for your SDFQuestionnaire not just be Questionnaire? The SDFQuestionnaire will always still be a Questionnaire resource when you send it, so it should serialize to that. Unless you want to introduce your own resource types of course, but then you would not be FHIR compliant nor very interoperable anymore.

**Comment by kennethmyhra** [comment]
Thanks @mbaltus, I was looking at the test cases in ClassMappingTest.cs and ModelInspectorTest.cs and got a bit confused. One question though, am I not supposed to make my own class implementation of our custom profile and instead rely on the Model classes, i.e: Questionnaire, etc, that comes with the API?

**Comment by kennethmyhra** [comment]
Closing this issue as it was obviously a misunderstanding on my part.

**Comment by ewoutkramer** [comment]
@kennethmyhra - you have taken a good look at the code ;-)  There is indeed a mechanism in there for a future version to parse data into a profiled resource, but that's still on the roadmap!

**Comment by kennethmyhra** [comment]
@ewoutkramer thanks for the feedback. I tried finding a link to the roadmap, but couldn't find it, is it possible to share it somehow? :)

**Comment by ewoutkramer** [comment]
Hi Kenneth, the roadmap is -unfortunately- buried deep in my head. So, I cannot provide a link ;-)

**Comment by tstolker** [comment]
And I just thought deep-linking was a standard feature these days…

**Comment by kennethmyhra** [comment]
@ewoutkramer - I can relate to that :)

**Comment by ewoutkramer** [comment]
But you did give me an idea here, I think I'll write a blog on thefhirplace.com about my plans!

**Comment by kennethmyhra** [comment]
Great, that will be interesting and useful for us to know.
