### ISSUE TITLE
Validator does not support bindings on value[x] when the instance has a non-bindable type

### ISSUE THREAD

**Issue by mmsmits** [ewoutkramer/fhir-net-api#366]
Location: ``QuestionnaireResponse.item.answer.value[x]`` has an example binding. However when validating an instance that has a ``valueReference`` , the validator throws a warning:

> A binding is given ('http://hl7.org/fhir/ValueSet/questionnaire-answers'), but the instance data is of type 'Reference', which is not [bindeable.]

For details see [simplifier](https://simplifier.net/ui/$validate?publicationId=23911.)

**Comment by ewoutkramer** [comment]
Fixed in c3af04a8383c7310697686e65084e4f6c6e7548a
