### ISSUE TITLE
FhirClient.update breaks when refresh=true if the server pointed at doesn't provide version information

### ISSUE THREAD

**Issue by wdebeau1** [ewoutkramer/fhir-net-api#37]
I've played around with this some, what seems to be happening is:
If a FHIR server returns a location with history information (i.e. http://fhirtest.uhn.ca/base/Observation/4041/_history/4) after an update, everything works great.
If a FHIR server returns a location that doesn't have history information (i.e. http://fhirstorm.dyndns.org:8080/FhirStorm/fhir/Observation/1), this snippet (FhirClient.cs, 338)
				if (reqId.VersionId != null)
					updated.SelfLink = reqId;

prevents SelfLink from being set.
Later, when the refresh occurs, FhirClient.cs 351 says:
            if (refresh) updated = Refresh(updated, versionSpecific: true);
which causes the read to happen on SelfLink, which is null, so an exception is thrown.

It seems like either SelfLink should be set regardless of the version information being present, or the update code should set versionSpecific based on whether the version information is present.

**Comment by ewoutkramer** [comment]
This issue has disappeared because this data is not part of the DSTU2 "meta" data within a resource, and so is always available!
