### ISSUE TITLE
It does not allow to mock FhirClient

### ISSUE THREAD

**Issue by sudanthahm** [ewoutkramer/fhir-net-api#372]
It does not allow to mock FhirClient when It needed to write unit tests

**Comment by ewoutkramer** [comment]
Would that be solved if I also include a IFhirClient with the same methods/signatures?

**Comment by sudanthahm** [comment]
Hi Ewout Kramer,

Yes you are correct if you provide that interface we can create our own
fhir client and use it for unit tests

**Comment by ewoutkramer** [comment]
Ok. Consider it done.
