### ISSUE TITLE
Where did Hl7.Fhir.Search go?

### ISSUE THREAD

**Issue by jugg1es** [ewoutkramer/fhir-net-api#374]
the documentation here: http://ewoutkramer.github.io/fhir-net-api/assemblies-overview.html 
mentions Hl7.Fhir.Search as a namespace but I can't seem to find it anymore.

**Comment by ewoutkramer** [comment]
Hi Peter, it was/is present in the DSTU1 version of the library, but not in the DSTU2 and STU3 versions of the library.  It's probably better to remove the reference from the site, since I don't think DSTU1 is in use anymore....
