### ISSUE TITLE
Database entities?

### ISSUE THREAD

**Issue by jaime-olivares** [ewoutkramer/fhir-net-api#375]
Hi there,
I would like to store the generated resource classes into a database, but the classes seem to be too complex to be mapped to database entities (i.e. Entity Framework). Is there any facility for use truly POCO classes?

**Comment by ewoutkramer** [comment]
Hi Jaime, yes - the FHIR classes are pretty complex (in the sense of many repeating properties, complex data types etc, extensies).  People have a few approaches for dealing with this:

* Extend the database to support FHIR types (see http://fhirbase.github.io/)
* Simplify the model to just what you need - which is generally way less complex and easier to map
* Use a document-oriented database (like Mongo or Couch)
* Store the xml or json as a blob in a relational database, with the indexed fields as separate columns

Finally, I think there are some people who are looking at creating a one-size-fits-all-FHIR relational schema (which would be your first step).  That's what you'll need before you can start mapping the POCO classes using -say- Entity Framework.

Best though, would be to ask at the Zulip channel (chat.fhir.org) - in one of the more general streams.  If you don't find anything there, I can bring you into contact with some specific people who might know more.....

**Comment by jaime-olivares** [comment]
Thanks Ewout,
Thanks for your answer.
After attempting to create POCO classes, I realized there are very few properties that can be mapped to SQL primitives, but have either to be disaggregated again or stored as json fragments. 
So, I am going for a mixed approach: storing the ID and entire json in a main table, plus parsing the json object and storing all ResourceReferences in a separated relationship table.

**Comment by ewoutkramer** [comment]
Right, that sounds like a reasonable approach....
