### ISSUE TITLE
Conditional read can't deal with 304 Not modified 

### ISSUE THREAD

**Issue by tstolker** [ewoutkramer/fhir-net-api#376]
When I make the following call:

            string ifNoneMatch = "2017-06-26T15:12:34:477.3440";
            DateTimeOffset modified = DateTimeOffset.Parse("2017/06/26 15:12:34");

            Patient p = client.Read<Patient>("Patient/40", ifNoneMatch, modified);

And the server returns a 304 Not Modified status code as documented in https://www.hl7.org/fhir/http.html#cread:
Clients may use the If-Modified-Since, or If-None-Match HTTP header on a read request. If so, they SHALL accept either a 304 Not Modified as a valid status code on the response (which means that the content is unchanged since that date) or full content (either the content has changed, or the server does not support conditional request).

The exception thrown by the FhirClient is: "Server returned a status code 'NotModified', which is not supported by the FhirClient". Based on the spec, that seems wrong.

In a more general sense, please return any error in the 300 and 400 ranges to the caller in a transparant way, e.g. through a dedicated exception.

**Comment by ewoutkramer** [comment]
Mmmm....I had support for this in the DSTU1 version of the client - wonder where it went....

I any case, I will create a dedicated exception instead.

**Comment by brianpos** [comment]
I'm sure there is a dedicated exception that we use. FhirException or FhirOperationException, don't recall which it is.

**Comment by ewoutkramer** [comment]
Will do. 400 and 500 errors already had a dedicated exception (FhirOperationException), which I will now also throw for 1xx and 3xx. This exception has a dedicated "status" and "operationoutcome" to figure out what went wrong. Fixed in 885e369f741ff1d139146bd3e3c299e112ac8a6d

**Comment by tstolker** [comment]
@ewoutkramer, I tested this and it works like a charm. One tiny little thing could be better, the exception message now is: 
   Operation resulted in an redirection response (NotModified). Body has no content.

The correct English spelling is 
    Operation resulted in **a** redirection response (NotModified). Body has no content.

**Comment by ewoutkramer** [comment]
Fixed in 0.93.6 release!
