### ISSUE TITLE
ConditionalCreate never sets If-Match header 

### ISSUE THREAD

**Issue by tstolker** [ewoutkramer/fhir-net-api#377]
Despite the presence of a boolean flag versionAware in the conditional update request, it never seems to send the "If-Match" header. The "normal" update method does send that header.

            SearchParams condition = new SearchParams();
            condition.Add("identifier", HttpUtility.UrlEncode(BSNSystem) + "|" + BSNValue2);
            Patient curesult = client.Update<Patient>(patient2, condition, true);

Is this a bug, or am I missing something?

**Comment by ewoutkramer** [comment]
Sounds like a bug to me, and it has been reported before. Will fix.

**Comment by ewoutkramer** [comment]
Yep, simple omission - fixed in 7db5dc8a075d8d52738386e6a5f6d03c06bbea8c
