### ISSUE TITLE
How to set header Prefer: handling=strict

### ISSUE THREAD

**Issue by tstolker** [ewoutkramer/fhir-net-api#379]
https://www.hl7.org/fhir/search.html#errors describes the use of the Prefer header to request the server to handle parameters in a struct way:

> Prefer: handling=strict: Client requests that the server return an error for any unknown or unsupported parameter

Can I enable this via the FhirClient?

**Comment by ewoutkramer** [comment]
We might have skipped over this when doing the STU3 port for the FhirClient. Will add...

**Comment by ewoutkramer** [comment]
Fixed in 018ddd514b5cca8daa8def9c9ba020889b84f735
