### ISSUE TITLE
Create console-based version of the validator

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#383]
It is now possible to create a netstandard/Core console validator that could run on multiple platforms in a CI context. This is really useful.

[Maybe the start of a new separate tool?]

**Comment by mvdzel** [comment]
I would say a console tool is useful anyhow. I started an initial tool called FhirConsole. Just for my own and for testing the RDF roundtrips. But I now also use it to generate the snapshot versions of StructureDefinitions.

**Comment by ewoutkramer** [comment]
Michael, is integrating the validator into that tool feasible for you to do?  Did you create a .NET core application so it runs on other platforms too?

**Comment by ewoutkramer** [comment]
We are creating a new tool called Torinox that does exactly this.... there will be a beta in Cologne

**Comment by brianpos** [comment]
I was going to add it as an option in my fhirpath tester tool, but never got there.
Keen to get the specification.zip thing sorted first.
(otherwise just use the web based resolvers - which might even be a better answer for my usage anyway)
