### ISSUE TITLE
Add json support to DirectorySource 

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#384]
Currently, DirectorySource only searches for conformance files ending with .xml.

Add support for .json files.

**Comment by wmrutten** [comment]
Actually, this is the main reason that Forge does not yet support JSON.
Challenging how to deal with duplicates, e.g. if a folder contains multiple representations (XML + JSON + RDF) of the same profile with the same canonical url. Maybe introduce some kind of option/configuration flags for resolving strategy, cf. snapshot generator and validator?

**Comment by ewoutkramer** [comment]
Fixed in aad0c94
