### ISSUE TITLE
(DSTU2, STU3?) In a snapshot, the binding.reference seems to disappear

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#387]
When creating a slice on QuestionnaireResponse.group, giving the slice-entry several children with constraints (e.g. QuestionnaireReponse.qroup.question.linkId), the snapshotted slice-entry will get an incorrect QR.group.question.anwers.value binding - the binding itself is present, but the reference to the (example) valueset merged in from the core base will disappear.

**Comment by ewoutkramer** [comment]
For an example, see this StructureDefinition:
[ADW-Questionnaire-Response-1.StructureDefinition.zip](https://github.com/ewoutkramer/fhir-net-api/files/1124397/ADW-Questionnaire-Response-1.StructureDefinition.zip)

**Comment by ewoutkramer** [comment]
The binding at line 1372 has no reference to a valueset anymore, while the base has it.

**Comment by wmrutten** [comment]
The DSTU2 core definition for QuestionnaireResponse (from profiles-resources.xml) specifies an example binding for the "QuestionnaireResponse.group.question.answer.value[x]" element, but without an actual valueset reference:
```
    <element>
      <path value="QuestionnaireResponse.group.question.answer.value[x]"/>
      <!-- ... -->
      <binding>
        <strength value="example"/>
        <description value="Code indicating the response provided for a question."/>
      </binding>
      <!-- ... -->
    </element>
```

**Comment by wmrutten** [comment]
Also, there is no element binding at line 1372 in the attached profile....?

**Comment by wmrutten** [comment]
Seems to be an invalid bug report - I suggest we close this one.

**Comment by ewoutkramer** [comment]
The binding is missing in DSTU2, but not in STU3. The validator was correct to signal this as a problem and the snapshot generator correct to not make up one that is missing from the base ;-)

**Comment by wmrutten** [comment]
Works as designed! ;p
