### ISSUE TITLE
Goal target details code and unit

### ISSUE THREAD

**Issue by brillox** [ewoutkramer/fhir-net-api#388]
Hi,
I am populating the goal target details in this way:
`if (Decimal.TryParse(myGoal.GoalValue, out GoalOutValue))
                  {
                     GoalValue = new Quantity(GoalOutValue, myGoal.GoalMeasure, "My Diabetes My Way");
                     myFhirGoal.Target.Detail = GoalValue;
                  }`

after that the detail unit and code both displays the same  myGoal.GoalMeasure value which is the Unit of Measure I am passing through. Is this duplication due to FHIR specifications or I am doing something wrong? Below the snippet of the produced goal resource where you can see that "unit" and "code" have the same value of "Kg"

`{
      "fullUrl": "http://localhost/mdmwapi/amackie",
      "resource": {
        "resourceType": "Goal",
        "id": "WEIGHT_GOAL",
        "status": "in-progress",
        "description": {
          "text": "70 kg (11st 1lb)  by 08/05/2016"
        },
        "target": {
          "detailQuantity": {
            "value": 70,
            "unit": "kg",
            "system": "My Diabetes My Way",
            "code": "kg"
          },
          "dueDateTime": "05/08/2016"
        },
        "note": [
          {
            "text": "test min and max value validation"
          }
        ]
      }
    },
`

**Comment by mbaltus** [comment]
The initializer for the Quantity sets the unit and the code to the same value. IMHO this is done on purpose, since the specification states that Quantity.code is a "Coded form of the unit". But perhaps the behaviour of the initializer should be reconsidered, since you can't be sure that the unit value given is also a true code?

**Comment by brillox** [comment]
>>But perhaps the behaviour of the initializer should be reconsidered, since you can't be sure that the unit value given is also a true code?

Do you mean you should change teh behaviour of the initializer or that I should change the way i use it?

**Comment by mbaltus** [comment]
I mean the maintainers of the API should take a look at it and perhaps change the initializer.
But in the mean time you can of course change the value for the code after you've created the Quantity, if you feel it is incorrect.

**Comment by ewoutkramer** [comment]
This is what the constructor does:

        public Quantity(decimal value, string unit, string system= "http://unitsofmeasure.org")
        {
            Value = value;
            Unit = unit;
            Code = unit;
            System = system;
        }

so, I am setting the unit to both Unit and Code - this is indeed done as a service, since you will provide the correct (coded) unit from UCUM, but at least the user readable Unit will also be (by default) set to something useful.

**Comment by brillox** [comment]
Well our clients do find that confusing; however I have amended my code to use a prameterless constructor and build the component with the needed values

**Comment by ewoutkramer** [comment]
Keeping this open for a little longer to see what others think...

**Comment by brillox** [comment]
Guys as this is a space for more serious bugs  - I guess - there is a space where I can get some support for minor issues? Or it is fine for me to post questions like this?

I am using STU3 but in code when I try to validate the bundle using this code

```
var errors = new List<ValidationResult>();
var success = FhirValidator.TryValidate(myBundle, errors)
```

the FhirValidator is not recognised at all; I am adding the using directives for using Hl7.Fhir.Model;

**Comment by brillox** [comment]
Thanks @ewoutkramer  I appreciate it.

**Comment by ewoutkramer** [comment]
@brillox - These questions are best posed at chat.fhir.org in the "dotnet" stream - since then many more people will see the answers!

**Comment by ewoutkramer** [comment]
This class was renamed to DotNetAttributeValidation..... since there's now a "real" profile based FhirValidator, and I wanted to avoid confusion.

**Comment by brillox** [comment]
great thanks @ewoutkramer ; I have been on that chat but seemed to me that was not technical... I will use that.

Guys you are great!!

**Comment by ewoutkramer** [comment]
You're welcome!
