### ISSUE TITLE
Handling of _sort is incorrect according to https://www.hl7.org/fhir/search.html#_sort

### ISSUE THREAD

**Issue by tstolker** [ewoutkramer/fhir-net-api#389]
https://www.hl7.org/fhir/search.html#_sort describes that _sort is called as follows:
`GET [base]/Observation?_sort=status,-date,category`

The .NET API currently generates an incompatible DSTU2 format:
`GET` [base]/Organization?_sort:asc=_lastUpdated

This to me seems a high priority issue, can you please fix ASAP?

**Comment by mbaltus** [comment]
For DSTU2, the definition for _sort is different than the one for STU3, see http://hl7.org/fhir/DSTU2/search.html#sort.

> The _sort parameter takes one of two qualifiers, :asc and :desc, which specify ascending and descending sort order respectively. The default value is :asc

So it seems the API is correct.

**Comment by tstolker** [comment]
I am using the STU3 library...

**Comment by mbaltus** [comment]
Ah, okay! I misread your issue.

**Comment by ewoutkramer** [comment]
Yes, we missed a few STU3 features. As part of the other things @tstolker  noticed that are already in the issue list, I will go over this and update to STU3...

**Comment by ewoutkramer** [comment]
Fixed in cec48699
