### ISSUE TITLE
HttpUtil.Prefer lacks 'OperationOutcome' option

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#391]
http://www.hl7.org/implement/standards/fhir/http.html#2.21.0.5.2
Specifies minimal / representation / OperationOutcome as valid Prefer header values for create/update/patch/transaction. But OperationOutcome is missing from the enum.

Maybe combine this with #379

**Comment by ewoutkramer** [comment]
fixed in 74c17f8572b09c4dfd32af10e8e2a73b9dd2fb93
