### ISSUE TITLE
Error opening the solution in visual studio 2015

### ISSUE THREAD

**Issue by akashsamal** [ewoutkramer/fhir-net-api#397]
While opening the solution Hl7.Fhir in Visual Studio 2015, getting the error  : 
The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.

When I put the stated namespace in <Project> the problem is not getting solved. Not able to load the solution in Visual Studio. 

Till now I did following steps:
1. Open project on GitHub and Fork the project
2. Clone or Download -> Open in Desktop
3. From the file explorer trying to open solution, but not able to load projects inside solution.(load fails)

Can you please tell me the correct way of opening the project in visual studio? and using that in our own another solution?

**Comment by ewoutkramer** [comment]
Yes, you need VS2017, since it uses the newest netstandard tooling + new .csproj format!

**Comment by akashsamal** [comment]
Can it be opened in VS2017 express Edition?

**Comment by ewoutkramer** [comment]
I would say so, it even compiles and works under Visual Studio Code!

**Comment by ewoutkramer** [comment]
Hoping this resolved your issue!
