### ISSUE TITLE
[ERROR] Value is not exactly equal to fixed value '<system>' (at Patient.generalPractitioner[0].identifier[0].extension[0]) 

### ISSUE THREAD

**Issue by tstolker** [ewoutkramer/fhir-net-api#399]
I have defind a profile on reference that adds an extension on reference.identifier.
That extension has a url of http://ggz.koppeltaal.nl/fhir/StructureDefinition/reference-identifier-resource-type. Then I add that extension in an instance:
 "generalPractitioner" : [
                    {
                        "identifier" : 
                        {
                            "extension" : [
                                {
                                    "url" : "http://ggz.koppeltaal.nl/fhir/StructureDefinition/reference-identifier-resource-type",                                    
                                    "valueCode" : "Practitioner"
                                }],                            
                            "system" : "http://fhir.nl/fhir/NamingSystem/agb-z",                            
                            "value" : "99999999"
                        }
                    }], 
 
When validating ttgis instance against the profile, the message I get is:

[ERROR] Value is not exactly equal to fixed value 'http://ggz.koppeltaal.nl/fhir/StructureDefinition/reference-identifier-resource-type' (at Patient.generalPractitioner[0].identifier[0].extension[0]) 

What does this error mean? What is wrong?

**Comment by ewoutkramer** [comment]
Hi Theo, can I see the profile for the Patient, or is this unconstrained?  Can I find the StructureDefinition for the extension somewhere?

**Comment by ewoutkramer** [comment]
Theo has reported that this problem has been fixed in the 0.9x.5 version of the API.
