### ISSUE TITLE
[Snapshot] Cannot tighten cardinality constraint on parent a sliced element

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#407]
Although it's unclear whether the spec allows you to do so, it's conceivable you might want to do this:

* Create a profile on Patient, call it PatientA
* In PatientA, slice identifier, for example on system
* Create a profile on PatientA, call it PatientB
* Change the cardinality of the *unsliced* base to be 1..* instead of 0..*

There is a problem here in the sense that we will allow you to change and reslice the slices in PatientA, but it's unclear whether you can reach back to the base, to increase the cardinality of the whole element, presumably by doing:

    <element id="Patient.identifier"> 
        <path value="Patient.identifier" /> 
        <min value="1" /> 
    </element> 

in PatientB.

**Comment by ewoutkramer** [comment]
The error you will get is:

    [ERROR] Element 'Patient.identifier' defines a slice without a name. Individual slices must always have a unique name, except extensions. (...)

**Comment by ewoutkramer** [comment]
Fixed in c459045ff2d699be92d51ef3911dda1e6e38a793

**Comment by wmrutten** [comment]
FYI It's certainly possible and valid for a derived profile to further constrain a slice entry that is defined in a base profile. The normal rules apply, a derived profile can only further constrain the slice entry.
Specifically, a derived profile can further constrain the cardinality of the slice entry and/or add additional entries to the slicing discriminator.
The current version of the snapshot generator supports this. Older versions emitted a warning message, but this has been fixed recently.
