### ISSUE TITLE
DirectoryResolver should gracefully handle inaccesible folders & files

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#410]
Ioanna Singureanu reported a Forge error where opening/saving a profile to the My Documents folder generated a runtime exception "Access to the path C:\Users\Ioana\Documents\My Music" is denied.

I suggest that the API either gracefully handles inaccessible folders (e.g. insufficient access permissions, network drive is offline, ...) or alternatively allows clients to override the default behavior (= throw).

Note: many reported Forge issues concern resource resolving. I can take away some of the user's confusion/frustration by improving the Forge UI. But we should also try to make the API resolver implementations as resilient as possible.

**Comment by ewoutkramer** [comment]
Should be fixed now I have merged the PR mentioned in this issue
