### ISSUE TITLE
Incorrect validation warnings for slice names

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#413]
Chris Munro reported the following issue:

> I've noticed that even with &lt;sliceName value="Test"/>
> 
> I still get a warning of 
> [WARNING] Evaluation of FhirPath for constraint 'eld-16' failed: Invocation of 'binary.or' failed: Invocation of 'matches' failed: parsing "^[a-zA-Z0-9\-\_]+$" - Unrecognized escape sequence \_. (at StructureDefinition.differential[0].element[6])
> 
> This looks to be because in the spec there are escape characters (https://www.hl7.org/fhir/elementdefinition-definitions.html) :
> 
> eld-16: sliceName must be composed of proper tokens separated by "/" (expression : sliceName.empty() or sliceName.matches('^[a-zA-Z0-9\\/\\-\\_]+$'), xpath: not(exists(f:sliceName/@value)) or matches(f:sliceName/@value, '^[a-zA-Z0-9\\/\\-\\_]+$'))
> 
> and the way java/c# process the escaped character in the regular expression?

It appears that the API is stumbling over the regex escaping...? Note that C# escaping rules are different. In Forge, I validate eld-16  using the following regex: @"^[a-zA-Z0-9/\-_]+$"

**Comment by ewoutkramer** [comment]
This is not present in the C# code, the eld-16 fhirpath expression  has an invalid escape sequence \_, this is not allowed in the grammar.  I don't know why this shows up now - the grammar has not changed and we run all constraints in the spec - so a unit-test should have caught this.  Correct, Brian?

**Comment by ewoutkramer** [comment]
Easy fix would be to 
* Find out why the unit-test did not catch this [@brianpos]
* Alter the grammar to allow it
* Create a gforge task to fix this.

**Comment by ewoutkramer** [comment]
Actually, what we see might be garbled because of all the escaping - it's a regex escaped in a FHIRPath statement and then pasted into Zulip.... have to be careful to find out exactly where the mistake is...

**Comment by ewoutkramer** [comment]
Hmmmm.....cannot reproduce it in 0.93.5-b3 :-(   What I did is just validate a Patient StructureDefinition - and another StructureDefinition from out testset - this should have triggered it?

**Comment by wmrutten** [comment]
Did you put a sliceName on the StructureDefs?

Escaping is hard. Here's the fhirpath expression eld-16 on ElementDefinition from profiles-types.xml:
`sliceName.empty() or sliceName.matches('^[a-zA-Z0-9\\/\\-\\_]+$')`
Note the double "\\" chars. These are not visible in Chris' original message above.

What are the rules about fhirpath regex escaping?

**Comment by ewoutkramer** [comment]
Traced it down all from the parsed FHIRPath expression, into the expression tree, into the actual call to the .NET regex evaluator. Turns out the message comes from the .NET regex evaluator, not from the FHIR API. And the .NET regex evaluator is right, "\_" is /not/ a valid escape sequence in regexes. We need to fix the spec.
