### ISSUE TITLE
DirectorySource generates runtime exception for unknown/invalid files in target folder

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#415]
In some circumstances, the DirectorySource fails to scan the target folder because it contains an invalid/unknown file, throwing an ArgumentNullException:

Value cannot be null.
Parameter name: resourceType

**Comment by wmrutten** [comment]
JsonFileConformanceScanner.List() should check if rootResourceType is null.
This will be fixed in the next release.

**Comment by wmrutten** [comment]
Submitted a pull request with a bugfix: https://github.com/ewoutkramer/fhir-net-api/pull/414

**Comment by ewoutkramer** [comment]
Included this in 0.9x.5-beta4 and 0.9x.6-alpha2
