### ISSUE TITLE
SearchParamDefinition in the model don't have the Url property set

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#417]
SearchParamDefinition in the model don't have the Url property set

**Comment by ewoutkramer** [comment]
Hi Corina, what does that mean?  You mean that if you deserialize fhir xml/json into a SearchParameter POCO, the "url" element is not set, even though it is present in the xml (or json)?

**Comment by CorinaCiocanea** [comment]
I meant the generated SearchParamDefinition don't have the Url field set. But they have it now.
