### ISSUE TITLE
DirectorySource does not support json files

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#418]
the DirectorySource reads some metadata (ConformanceScanInformation ) about the files (even for json files) ... this is something it wasn't doing in the previous version
but afterwards when actually requesting the resource in the file, it uses a method called getResourceFromScannedSource that instantiates an XmlFileConformanceScanner, but my file is a json file => so an exception is thrown

**Comment by ewoutkramer** [comment]
Ouch. I obviously never actually finished implementing this (nor did I write a test for it)

**Comment by ewoutkramer** [comment]
Will fix for 0.92.5/0.93.5 beta 6

**Comment by ewoutkramer** [comment]
Fixed in 743f1ef1cdd873d645feb6b85452175946f59ae3
