### ISSUE TITLE
Operation when using GET throws error for non-empty body

### ISSUE THREAD

**Issue by mbaltus** [ewoutkramer/fhir-net-api#419]
The $everything operation is idempotent, so I would have expected this code to run:
`var result = client.TypeOperation<Patient>("everything", null, true);`

But it results in the exception:   "Cannot have a body on an Http GET"

In `internalOperationAsync` (FhirClient.cs) the Parameters resource is set to an empty resource instead of the 'null' I passed. Then further on in `EndpointOperation` (TransactionBuilder.cs), the now empty Parameters is added to `entry.Resource`. Perhaps you should check `useGet` at that point to see if you need to add the Parameters or not?

**Comment by ewoutkramer** [comment]
These empty parameters are starting to annoy me ;-)  We've had code on and off to turn null into an empty resource - I do remember for a good reason. So, obviously some other code does not like it ;-)

**Comment by marcovisserFurore** [comment]
A GET operation without parameters has been solved now. A GET operation with primitive type parameters does not work yet. That would be solved in another issue.

**Comment by ewoutkramer** [comment]
Fixed in b9e14e9c991b80156166f976a380ddb7fee70529
