### ISSUE TITLE
FamilyMemberHistory onsetAge serialize issue with Quantity base type

### ISSUE THREAD

**Issue by rettema** [ewoutkramer/fhir-net-api#425]
The Age property seems to cause incompatibility between the validator, serialization and the poco navigator

**Comment by ewoutkramer** [comment]
Found it. The STU3 codebase references the DSTU2 set of Quantity subtypes in PocoElementNavigator.cs  :-(  Must be merge error.

**Comment by ewoutkramer** [comment]
Fixed in 6e9f6115d272faf727f2dbc7fcf0a09c05fe1730
