### ISSUE TITLE
Validation: better message when not following resourcereferences

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#426]
The validator has a setting not to follow resource references.
If you turn that on, you get warning saying something like 'Could not resolve Patient/abc'.
This could confuse readers, since in many cases the system would be able to resolve it, but is prohibited to do so.
Suggestion for differentiating messages:
1. If the validator is allowed to follow references, but cannot resolve one: keep the current message
2. If following references is turned off: "Validation is set not to validate the resource referenced as Patient/123".

**Comment by ewoutkramer** [comment]
Obviously never understood the bug report ;-)

**Comment by ewoutkramer** [comment]
Fixed in #498
