### ISSUE TITLE
ResourceWriter alters resource by adding an empty Meta

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#434]
In `Serialize(object instance, Rest.SummaryType summary, bool contained = false, string root = null)`, the code temporarily adds a SUBSETTED tag when serializing a summary.  The code starts by adding a meta (if there is none), and after serialization alters the instance again to remove the tag.  However, if this tag was the only thing present in Meta, meta will be empty, resulting in an empty `<meta />` tag.

Preferably, we should not touch the original instance at all - a Clone() here is probably the better solution. In any case we should avoid leaving an empty `<meta />`

**Comment by brianpos** [comment]
A clone would suck for large resources like a ValueSet/CodeSystem/Big Questionnaire
especially done during serialization.
(but do agree we should do it better)

**Comment by ewoutkramer** [comment]
Mmm....yes, I mistakenly thought this would only be for "summarized" and so more "empty" resources, but this is of course not how it works internally - we'd have to clone the whole resource only to serialize parts of it.

**Comment by ewoutkramer** [comment]
Fixed in 6de3e2c89efedda2aa4b6a4fec64aae437dc65d0
