### ISSUE TITLE
Spark doesn't honor observation searches where subject is specified without the _id prefix

### ISSUE THREAD

**Issue by wdebeau1** [ewoutkramer/fhir-net-api#44]
This returns data:
http://spark.furore.com/fhir/Observation/_search?subject:Patient._id=1132446799

This doesn't:
http://spark.furore.com/fhir/Observation/_search?subject:Patient=1132446799

**Comment by ewoutkramer** [comment]
Moved this bug to the Spark issue list here: https://github.com/furore-fhir/spark/issues/25
