### ISSUE TITLE
Hl7.Fhir.STU3.Core incorrectly defines search parameter Observation.patient

### ISSUE THREAD

**Issue by CorinaCiocanea** [ewoutkramer/fhir-net-api#440]
In branches develop-stu3 and master-stu3 the **Observation.patient** search parameter is defines as *" new SearchParamDefinition() { **Resource = "Observation", Name = "patient"**, Description = @"", Type = SearchParamType.Reference, Path = new string[] { "Observation.subject", }, **Target = new ResourceType[] { ResourceType.Group, ResourceType.Patient, },** XPath = "f:ReferralRequest/f:subject | f:DocumentManifest/f:subject | f:Goal/f:subject | f:Consent/f:patient | f:DocumentReference/f:subject" *

According to the specs (https://www.hl7.org/fhir/observation.html) the patient only has the target Patient.
So, why do we define both Patient and Group?

**Comment by CorinaCiocanea** [comment]
I see the same happens for Observation.encounter - Target = new ResourceType[] { ResourceType.Encounter, ResourceType.EpisodeOfCare, }

**Comment by ewoutkramer** [comment]
This sounds familiar - I am sure I have looked at this before. Not too sure what it was, but obviously, there's a difference between the spec, and the input file we use for code generation.  I think it had something to do with search parameters that were defined across resources....  do you recall what it was, @brianpos ?

**Comment by brianpos** [comment]
I'll recheck tomorrow, but yes there is something with that.

**Comment by ewoutkramer** [comment]
@CorinaCiocanea told me it is fixed. Having heard no evidence of the contrart, I'm closing this issue. Re-open if still a problem.
