### ISSUE TITLE
Path in validation message is incorrect

### ISSUE THREAD

**Issue by mbaltus** [ewoutkramer/fhir-net-api#444]
Path in this message from the validator is incorrect, should be rest[0]:

[WARNING] Cannot resolve reference http://hl7.org/fhir/StructureDefinition/ValueSet (at CapabilityStatement.rest[2].resource[0].profile[0])
[WARNING] Cannot resolve reference http://hl7.org/fhir/OperationDefinition/ValueSet-expand (at CapabilityStatement.rest[2].operation[1].definition[0])

FHIR resource used in validation:
[capabilitystatement.xml.txt](https://github.com/ewoutkramer/fhir-net-api/files/1397543/capabilitystatement.xml.txt)

**Comment by ewoutkramer** [comment]
Fixed in #511
