### ISSUE TITLE
Custom Serializer processor

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#446]
Make the serializer extensible, so that serialization and deserialization can be post processed.

Specific implementation need: adding a light weight method to serialize annotations (IAnnotatable).

**Comment by brianpos** [comment]
want to be very careful that this doesn't get into the base serializers, and unit tests to ensure that it doesn't.

**Comment by ewoutkramer** [comment]
Fixed in e65355138488aeeaa128acbbdd73c8ec24aae916
