### ISSUE TITLE
 json-edge-cases contains malformed JSON

### ISSUE THREAD

**Issue by PBernhardt** [ewoutkramer/fhir-net-api#45]
I was reviewing the code in DSTU2 develop branch. RoundtripTest unit test failed with this error.

Converting json-edge-cases [.json->.xml] 
Test method Hl7.Fhir.Tests.Serialization.RoundtripTest.FullRoundtripOfAllExamples threw exception: 
System.FormatException: Cannot parse json: After parsing a value an unexpected character was encountered: :. Path '_active.['http://hl7.org/fhir/example-do-not-use#recordStatus'][0]', line 14, position 20.

I looked at the extracted JSON and confirmed the JSON improperly formed. 

UPDATE: this may be a non-issue - I see a working copy of a replacement in the testdata folder that hasn't been added to the zip file yet. I replaced locally, but see the test failing in other places.

**Comment by ewoutkramer** [comment]
Peter, there are several tests in the examples.zip that are incorrect and cause the roundtrip to fail. We're working with James and Grahame to fix the examples, so this should be resolved when never versions of examples.zip arrive....
