### ISSUE TITLE
Operation when using GET with primitive type does not work

### ISSUE THREAD

**Issue by marcovisserFurore** [ewoutkramer/fhir-net-api#454]
An GET operation (i.e. $everything) does not work with primitive type as parameters. So
`var result = client.TypeOperation<Patient>("everything", new Parameters().Add("start", new Date(2017, 10)), true);`

does not work. But it results in the exception:   "Cannot have a body on an Http GET"

**Comment by ewoutkramer** [comment]
This has already been fixed in #419.
