### ISSUE TITLE
Parsing URI parameters to create Query resources

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#46]
`ParseQueryFromUriParameters` does not really parse the parameters - it just creates a `Query` object containing the parameters 'as is'. This means that malformed parameters are not caught by `ParseQueryFromUriParameters`, that is somewhat undesirable.

**Comment by brianpos** [comment]
Can you please provide an example that is bad, and what you would like the function to do for you?
Thanks.

**Comment by michelemottini** [comment]
A malformed query parameter like `&_sort:de=family` is currently accepted and interpreted as an ascending sort. I'd say it would be better if `ParseQueryFromUriParameters` threw an exception or reported in some way the error.

**Comment by ewoutkramer** [comment]
I have made this stricter, but the logic (now in SearchParams.cs) does not know the type of parameters it is parsing, so it cannot say meaningful things about which modifiers are allowed, whether the param values are valid for the parameter type etc. It may still be desirable to have a kind of "informed" parser that uses the spec metadata to make more informed parsing decisions, but that's not a high priority currently.

**Comment by brianpos** [comment]
I'll add some code in here that also checks the ModelInfo.SearchParams to find standard search params and convert them to appropriate parameters.

**Comment by ewoutkramer** [comment]
I think we can conclude that we won't introduce typed search paramaters anytime soon?

**Comment by ewoutkramer** [comment]
We could make this work if you pass in an SeachParameter resource...

**Comment by ewoutkramer** [comment]
> I think we can conclude that we won't introduce typed search paramaters anytime soon?

That's right.
