### ISSUE TITLE
[Validation] Check support for both kind of extensions for regexes

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#461]
By accident, we have defined two extensions to supply a regex for validation of string values (https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13328).  

We should check whether we support this at all (I don't think so), and if we do - make sure we look for  both possible extensions.

**Comment by ewoutkramer** [comment]
See also https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=12665

**Comment by marcovisserFurore** [comment]
Pull request: #518 and #519
