### ISSUE TITLE
[Source] Create a SnapshotGeneratorSource

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#475]
This source would make sure all StructureDefinitions passed through have a snapshot. \

Modes:
* For all SDs that don't have one (always on)
* For SDs with snapshots generated by something else than the .NET generator
* Regenerate every time

**Comment by wmrutten** [comment]
Agreed.

Currently, the snapshot generator itself contains quite a bit of logic to detect and handle recursion. I'd like to refactor this logic and move it into a separate SnapshotGeneratorSource. This would somewhat simplify the (bloated) snapshot generator class.

Note: We need to carefully think about cache invalidation, e.g. using a (new, optional) event interface for sources.

**Comment by wmrutten** [comment]
Note: I've started implementation on my own Fork. Stay tuned...
