### ISSUE TITLE
[ERROR] Value is not exactly equal to fixed value '{"resourceType":"Identifier","system":"http://fhir.de/NamingSystem/gkv/kvid-10"}'

### ISSUE THREAD

**Issue by mbaltus** [ewoutkramer/fhir-net-api#476]
When validating an example resource, I get this error message:
[ERROR] Value is not exactly equal to fixed value '{"resourceType":"Identifier","system":"http://fhir.de/NamingSystem/gkv/kvid-10"}'

The system is fixed in the profile, but the value in the example resource is the same, so it should validate. There was a similar issue before:  #399.

See https://simplifier.net/BasisprofilDE/Example-coverage-de-gkv-1 for the example resource, and https://simplifier.net/BasisprofilDE/coverage-de-gkv for the profile.

**Comment by ewoutkramer** [comment]
I've heard this before (indeed als oin #399), but it aways seems to disappear when I zoom in on it ;-)  Is this on simplifier?  Theo reported this solved in 0.93.5.....

**Comment by mbaltus** [comment]
No, I don't think it's a Simplifier issue. I've tried it with the validation tool as well. Even with one compiled with the latest beta of the API.

**Comment by ewoutkramer** [comment]
This is a bug in the profile.  The errors are not about Coverage.identifier, but about Coverage.subscriber.identifier (amongst others).

If you look at Coverage.subscriber.identifier, you'll see it has its fixed value set to the Identifier

     <fixedIdentifier>
        <system value="http://fhir.de/NamingSystem/gkv/kvid-10" />
      </fixedIdentifier>

which is what causes the validation error.

**Comment by ewoutkramer** [comment]
Suggestion: use <patternIdentifier> or fix Coverage.subscriber.identifier.system (as done with Coverage.identifier)
