### ISSUE TITLE
ZipSource is extracting the content in a temp directory without a discriminator for the spec version

### ISSUE THREAD

**Issue by marcovisserFurore** [ewoutkramer/fhir-net-api#477]
The ZipSource is extracting the content on a location with a version of the package but without the version of the specification (DTU2 or STU3). When you are using the API for different versions of the spec at the same time, you will end up in problems of using the wrong specification.zip.  

So, the path should also contain the version of specification, like 
C:\Users\<user>\AppData\Local\Temp\FhirArtifactCache-0.94.0.0-**DSTU2**

**Comment by ewoutkramer** [comment]
Closing issue, fixed by PR #486
