### ISSUE TITLE
Encountered an unknown resource 'feed'

### ISSUE THREAD

**Issue by Bomberlt** [ewoutkramer/fhir-net-api#48]
When searching Patient by id:
`var sparkFhirClient = new FhirClient("http://spark.furore.com/fhir");`
`sparkFhirClient.SearchById<Patient>(id);`
FormatException was throw with message _At line 1, pos 2: Encountered an unknown resource 'feed'_

I have looked into this issue and found out, that [Atom support was dropped](https://github.com/ewoutkramer/fhir-net-api/commit/fb81aec176787dabe69995312ff57f0101d52c62). How could I search for entries without Atom support?

**Comment by ewoutkramer** [comment]
I think you are trying to use the DSTU2 FHIR libraries to contact a DSTU1 server.  Either use the DSTU1 FHIR libraries (found at http://www.nuget.org/packages/Hl7.Fhir), or try a DSTU2 server (e.g. http://fhir-dev.healthintersections.com.au/open)

Regards,

  Ewout

**Comment by Bomberlt** [comment]
Yes you are right, I have used fhir-net-api from master branch on DSTU1 server.

Sorry to bother you, but I got some questions:
So if I use DSTU1 server, I should use master-dstu1 branch?
And [nuget](http://www.nuget.org/packages/Hl7.Fhir) will be always on DSTU1 version?
From which branch nugets are built?
And what other branches is for? (ft-dicom, gh-pages)

**Comment by ewoutkramer** [comment]
>So if I use DSTU1 server, I should use master-dstu1 branch?
Yes.

So, there’s master-dstu1 and develop-dstu1. Master-dstu1 contains the source for the released (on nuget) DSTU1 package.  The branch “master” contains the source for the release DSTU2 package.
The “develop-dstu1” and “develop” branches contain updates we have made after we released the NuGet packages, so the “develop” branches are newer (but more untested).

>And nuget<http://www.nuget.org/packages/Hl7.Fhir> will be always on DSTU1 version?
>From which branch nugets are built?

There are 4 packages on NuGet:


·         FHIR and FHIR.Specification – These are the DSTU1 core libraries ((http://www.nuget.org/packages/Hl7.Fhir) + DSTU1 additional functionality libraries (http://www.nuget.org/packages/Hl7.Fhir.Specification)

·         FHIR.DSTU2 and FHIR.Specification.DSTU2 - These are the DSTU2 core libraries (http://www.nuget.org/packages/Hl7.Fhir.DSTU2) + DSTU2 additional functionality libraries (http://www.nuget.org/packages/Hl7.Fhir.Specification.DSTU2)

You probably only need the core libraries now, so NuGet has both, but the DSTU2 libraries are in “alpha”, so you’ll only see them in Visual Studio if you include the “prerelease versions”.


> And what other branches is for? (ft-dicom, gh-pages)
“ft-dicom” is called a feature branche, and contains some extra features we have not included in develop or master. Check this http://nvie.com/posts/a-successful-git-branching-model/ if you want to know more about how we do our branches.

“gh-pages” is special, this contains the documentation, and is published here: http://ewoutkramer.github.io/fhir-net-api/

Regards,

  Ewout

**Comment by Bomberlt** [comment]
Thank you very much for your comprehensive answer, Ewout. this explains a lot. I'm closing this issue now as everything is OK now.
