### ISSUE TITLE
[Validator] Validator does not validate datatype SimpleQuantity correctly 

### ISSUE THREAD

**Issue by ArdonToonstra** [ewoutkramer/fhir-net-api#481]
In a profile on datatype [dosage ](https://simplifier.net/NictizSTU3/zib-InstructionsForUse) the dose[x] is specified for SimpleQuantity and Range. However, it is not possible to validate examples with a doseQuantity, The validator message:

Element 'Dosage.dose[x]' : 'DoseQuantity' has an invalid type profile constraint 'http://hl7.org/fhir/StructureDefinition/SimpleQuantity'. The target represents a profile on 'Quantity' which is incompatible with the element type 'Quantity'. 
Diagnostics: http://nictiz.nl/fhir/StructureDefinition/zib-InstructionsForUse 
Location: Dosage.dose[x]

Example: https://simplifier.net/NictizSTU3/MedicationDispense-example-2/$validate
Profile: https://simplifier.net/NictizSTU3/zib-AdministrationAgreement
Profile datatype: https://simplifier.net/NictizSTU3/zib-InstructionsForUse

**Comment by ewoutkramer** [comment]
This is most probably a duplicate of #425 (which has been fixed recently) - but I will keep this around to double-check.

**Comment by ewoutkramer** [comment]
It is actually not, this message originates from the Snapshot generator, which probably has duplicate logic with the same error as fixed in #425 ;-)  I will take a look at it shortly.

**Comment by ewoutkramer** [comment]
So, Michel has fixed this obviously, but the next problem is that you cannot yet slice on type ;-)  Anyway, this issue has been fixed (and the validator now neatly reports that this kind of slicing is not supported).
