### ISSUE TITLE
Add more generic system for tracking issues and errors

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#483]
Currently, the Validator uses OperationOutcome (and its issue component) to keep track of warnings and errors as validation progresses.  There are, however, more components that may wish to keep a list of errors (instead of throwing exceptions) and some of these might not be POCO-aware (and thus may not use OperationOutcome.

Propose to add a model-independent system to track errors, in which step one is to define a generically useable Issue class that all components of the .NET API may use.

**Comment by wmrutten** [comment]
Great suggestion, also useful for the snapshot generator.
The API could then expose e.g. an extension method to project a list of Issues to an OperationOutcome resource. This may even allow us to provide backwards compatibility.

**Comment by wmrutten** [comment]
This is also touches upon #475 Create snapshot generating source
Any post-processing source may need to convey outcome information.
The `IResourceResolver` interface methods return the requested artifact, or null, or throw an exception.
So we need to find a (generic) way to return additional outcome info to the client.

**Comment by ewoutkramer** [comment]
I am now piloting a new interface, `IExceptionSource` that looks like below.

Basically, I am using normal exceptions - but instead of throwing them a component will raise an event, with a basic message, the severity, and any Exception as a payload.

Copied this approach from the System.Xml.Schema.ValidationEventArgs (used by the validating xml reader).

Ideas?

```csharp
    public interface IExceptionSource
    {
        event EventHandler<ExceptionRaisedEventArgs> OnExceptionRaised;
    }

    public class ExceptionRaisedEventArgs : EventArgs
    {
        public ExceptionRaisedEventArgs(string message, ExceptionSeverity severity) : this(message, severity, null)
        {
        }
        public ExceptionRaisedEventArgs(string message, ExceptionSeverity severity, Exception exception)
        {
            Exception = exception;
            Message = message;
            Severity = severity;
        }

        public readonly Exception Exception;
        public readonly string Message;
        public readonly ExceptionSeverity Severity;
    }
```

**Comment by wmrutten** [comment]
I'd also would like to be able to annotate runtime errors with information that uniquely identifies the originating source, such as a weak reference or a Guid/Autonumbering integer in combination with the datatype: `{ typeof(DirectorySource), 123 }`.
Strong reference may be dangerous, as this will keep the originating instance alive, which may not immediately be clear from the public interface and probably not what a user expects.
Examples:
* allow clients using a `MultiResolver` to determine which of the internal sources was responsible for generating the error. 
* Allow validator clients to detect and handle errors originating from another internal layer, such as the snapshot generator or resource resolver.

**Comment by ewoutkramer** [comment]
Done as part of #646, where this is introduced for parsing errors. Still needs to be propagated to other compositions of components like IResourceResolver though.
