### ISSUE TITLE
When searching for entry HTTP request uses wrong Accept header

### ISSUE THREAD

**Issue by Bomberlt** [ewoutkramer/fhir-net-api#49]
When searching for entry by id (or by query):
`var sparkFhirClient = new FhirClient("http://spark.furore.com/fhir");`
`sparkFhirClient.SearchById<Patient>(id);`

request sent to server is with Headers:
`User-Agent: .NET FhirClient for FHIR 0.4.0`
`Accept: application/xml+fhir;charset=utf-8`
`Host: spark.furore.com/fhir`
`Proxy-Connection: Keep-Alive`
while returned response from server is with header `application/atom+xml`.

**Comment by Bomberlt** [comment]
I found, that request is always formed with `Accept: application/xml+fhir` header.
[107](https://github.com/ewoutkramer/fhir-net-api/blob/a9b77a5fefe2ff972cdaba40b9aa0e19d5378afd/src/Hl7.Fhir.Core/Rest/FhirRequest.cs#L107) `request.Accept = Hl7.Fhir.Rest.ContentType.BuildContentType(acceptFormat.Value, forBundle: false);`.

I think `forBundle` should be `true` in this particular case.

**Comment by ewoutkramer** [comment]
In DSTU2, it’s no longer necessary to distinguish between bundle and non-bundle accept types, since they are all fhir resources now (and no longer Atom).  Is this the DSTU1 or DSTU2 code?

**Comment by Bomberlt** [comment]
This is DSTU1 code. Sorry for not mentioning it.
