### ISSUE TITLE
Resources temporary ids are not assigned when adding them to bundle

### ISSUE THREAD

**Issue by Bomberlt** [ewoutkramer/fhir-net-api#50]
When adding resource to a bundle there are no option to generate temporary id for it.

It would be nice if fhir-net-api library could create temporary ids for resources so it would be easier to send a transaction to FHIR server.

Btw, I'm using DSTU1 version.

**Comment by ewoutkramer** [comment]
This is a nice idea. Bundle will change a lot in DSTU2, and this is one of the functions I'd like to add when rewriting Bundle support.

**Comment by ewoutkramer** [comment]
This never got done -- we could add it to TransactionBuilder - but I am closing it since no one has asked for it in the past 4 years.
