### ISSUE TITLE
[FhirClient] SearchParameter multiple includes

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#501]
Generates an invalid format when converting to a query.
```
sp.Include.Add(value);
```
with multiple of these will generate _include=Practitioner,Location
which should be _include=Practitioner&_include=Location

**Comment by ewoutkramer** [comment]
There must be a mistake here?  The code clearly does not do it, and there's a unit test that tests the correct behaviour:

        [TestMethod]
        public void SerializeParams()
        {
            var q = new SearchParams();
            q.Query = "special";
            q.Count = 31;
            q.Summary = SummaryType.Text;
            q.Sort.Add(Tuple.Create("sorted", SortOrder.Descending));
            q.Sort.Add(Tuple.Create("sorted2", SortOrder.Ascending));
            q.Include.Add("Patient.name");
            q.Include.Add("Observation.subject");
            q.Elements.Add("field1");
            q.Elements.Add("field2");

            var output = q.ToUriParamList().ToQueryString();
            Assert.AreEqual("_query=special&_count=31&_include=Patient.name&_include=Observation.subject&_sort%3Adesc=sorted&_sort%3Aasc=sorted2&_summary=text&_elements=field1%2Cfield2", output);
        }

**Comment by brianpos** [comment]
It's when it is passed to the FHIR client, I'll.look into it further.

**Comment by ewoutkramer** [comment]
@brianpos : Ping!

**Comment by brianpos** [comment]
From memory, it's the processing of the named parameters that removes it. Don't recall which code path uses it. 
https://github.com/brianpos/fhir-net-web-api/blob/develop-r4/src/Hl7.Fhir.WebApi.AspNetCore/HttpHeadersExtensions.cs
