### ISSUE TITLE
Resource update requires absolute path in Resource Id field

### ISSUE THREAD

**Issue by Bomberlt** [ewoutkramer/fhir-net-api#51]
I'm trying to get Resource from server and then update it.

Method 2 works as intended. Method 1 does not  work on update, because Patient id is not an absolute path.
Error due to code in 
BundleXmlParser.cs [157](https://github.com/ewoutkramer/fhir-net-api/blob/master-dstu1/src/Hl7.Fhir.Core/Serialization/BundleXmlParser.cs#L157): `var id = SerializationUtil.UriValueOrNull(entry.Element(XmlNs.XATOM + XATOM_ID));`

Method 1:
```
[TestMethod]
public void TestSearchByPersonaCode()
{
  var client = new FhirClient("http://spark.furore.com/fhir");

  var pats =
    client.Search<Patient>(
      new[] { string.Format("identifier={0}|{1}", "http://esveikata.lt/Identifier/PersonalCode", "[value]") });
    var pat = pats.Entries.FirstOrDefault() as ResourceEntry<Patient>;
    client.Update<Patient>(pat);
}
```
Method 2:
```
[TestMethod]
public void TestRead()
{
  var client = new FhirClient("http://spark.furore.com/fhir");

  var pat = client.Read<Patient>("Patient/[value2]");
  client.Update<Patient>(pat);
}
```

Btw, I'm using DSTU1 version.

**Comment by ewoutkramer** [comment]
I think this is fixed in the current DSTU2, since much of this code has been rewritten. Will test.
