### ISSUE TITLE
Elements subclasses seem to have inconsistent naming

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#52]
Subclass naming seems inconsistent
```C#
MedicationPrescription.MedicationPrescriptionDosageInstructionComponent
```
Versus:
```C#
Patient.AnimalComponent
```

**Comment by brianpos** [comment]
This is now templated in the ft-t4-generation stream, and should be consistent with the Java implementations (I think).
Should we do anything further here?

**Comment by ewoutkramer** [comment]
Don't know, it was already aligned with the Java implementation, it cannot be inconsistent ;-)
Animal is a direct component of Patient, but I see that for deeper components, the name of the Resource is repeated, so it should have been either Patient.PatientAnimalComponent or MedicationPrescription.DosageInstructionComponent....

**Comment by brianpos** [comment]
Generated code is using what is in the xml file.
I know at least some came out different...

**Comment by brianpos** [comment]
This is now done as documented on the BackboneElement page specializations section
