### ISSUE TITLE
FhirPath does not resolve correctly for some elements

### ISSUE THREAD

**Issue by khronosX** [ewoutkramer/fhir-net-api#522]
Hi,

I am trying to resolve values using FhirPath and noticed that some elements are not resolving.

For example, this works:

```
StructureDefinition sd = new StructureDefinition();

sd.Abstract = true;

var values = sd.Select("StructureDefinition.abstract");
```

But this does not work:

```
StructureDefinition sd = new StructureDefinition();

sd.Snapshot = new StructureDefinition.SnapshotComponent()
{
    Element = new System.Collections.Generic.List<ElementDefinition>()
};

var element = new ElementDefinition();

element.Binding = new ElementDefinition.ElementDefinitionBindingComponent();

element.Binding.ValueSet = new FhirUri("abc");

sd.Snapshot.Element.Add(element);

var values = sd.Select("StructureDefinition.snapshot.element.binding.valueSetUri");
```
```StructureDefinition.snapshot.element.binding.valueSetUri``` is defined in ModelInfo for StructureDefinition 'valueset' search parameter.

Seems like a either a bug in FHIR path expression parsing or FHIR path expression itself? I have not had chance to debug it yet to see where the issue is. Has anyone else encounter the issue as well? I am using the latest 0.94 Nuget package.

**Comment by ewoutkramer** [comment]
Hi khronos,

This is by design (see http://hl7.org/fhirpath/#polymorphism-in-fhir), the path you are looking for is

`StructureDefinition.snapshot.element.binding.valueSet`, since that is the formal name of the element (the type is just a suffix visible in the serialization in json and xml)

**Comment by khronosX** [comment]
If that's the case, should ModelInfo be updated to reflect that? 

```new SearchParamDefinition() { Resource = "StructureDefinition", Name = "valueset", Description = @"A vocabulary binding reference", Type = SearchParamType.Reference, Path = new string[] { "StructureDefinition.snapshot.element.binding.valueSetUri", "StructureDefinition.snapshot.element.binding.valueSetReference", }, Target = new ResourceType[] { ResourceType.ValueSet, }, XPath = "f:StructureDefinition/f:snapshot/f:element/f:binding/f:valueSetUri | f:StructureDefinition/f:snapshot/f:element/f:binding/f:valueSetReference", Expression = "StructureDefinition.snapshot.element.binding.valueSet[x]" },```

If I want to use ModelInfo to be able to enumerate all supported search parameters and use FHIR Path to extract value out of a resource, the above entry will not work.

**Comment by ewoutkramer** [comment]
Now, that is interesting indeed. Is this DSTU2 or STU3?  What do you think @brianpos ?

**Comment by khronosX** [comment]
This is STU3. 

https://github.com/ewoutkramer/fhir-net-api/blob/develop-stu3/src/Hl7.Fhir.Core/Model/Generated/Template-ModelInfo.cs

**Comment by brianpos** [comment]
There are a few like this.
Haven't updated a tool to find them all yet, though the fhirpath tester should be able to validate them now.
In my server the ones I've identified I've updated in the modelinfo static before i use them in the server.

**Comment by ewoutkramer** [comment]
I will create an issue to make sure we continue finding and fixing these then.

**Comment by ewoutkramer** [comment]
Actually, #524 will do. We'll continue there.
