### ISSUE TITLE
FhirPath does not resolve correctly for some elements 

### ISSUE THREAD

**Issue by khronosX** [ewoutkramer/fhir-net-api#524]
Hi there,

This is related to issue #522. Since it was closed by the owner I couldn't reactivate the issue.

Some of the FHIR Path defined in ModelInfo.cs does not resolved correctly.

```new SearchParamDefinition() { Resource = "StructureDefinition", Name = "valueset", Description = @"A vocabulary binding reference", Type = SearchParamType.Reference, Path = new string[] { "StructureDefinition.snapshot.element.binding.valueSetUri", "StructureDefinition.snapshot.element.binding.valueSetReference", }, Target = new ResourceType[] { ResourceType.ValueSet, }, XPath = "f:StructureDefinition/f:snapshot/f:element/f:binding/f:valueSetUri | f:StructureDefinition/f:snapshot/f:element/f:binding/f:valueSetReference", Expression = "StructureDefinition.snapshot.element.binding.valueSet[x]" },```

```valueSetUri``` and ```valueSetReference``` are not valid property. It should be ```valueSet```.

This is in STU3 branch.

Thanks

**Comment by brianpos** [comment]
See my note on #522

**Comment by cknaap** [comment]
I searched the ModelInfo.SearchParameters on the develop-stu3 branch, but none of the Expression fields contain [x].
Has this already been corrected in the meantime?

**Comment by ewoutkramer** [comment]
This is still the case in the DSTU2 branch. Will make a fix.
