### ISSUE TITLE
More intuitive approach to running FP on an instance

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#528]
Currently, you have to be aware of the fact that you need a navigator - so you need to create the correct navigator (say, PocoNavigator) and then run FP on it.  Would be nice if we had something like 

```C#
interface INavigeable
{
    IElementNavigator GetNavigator()
}
```

then all FP and validation libraries could take INavigeable as input too, and the user does not have to worry about creating navigators.

**Comment by lorddev** [comment]
(please make sure you spell it "INavigable"

**Comment by ewoutkramer** [comment]
;-)

**Comment by ewoutkramer** [comment]
Actually, I see this has been fixed in a different manner, by providing extension methods on Base, thus allowing you to run FP directly on POCO objects.  That's fine too.
