### ISSUE TITLE
Improve out-of-the-box experience for Validation

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#529]
NuGet will store validation.zip in the nuget cache, VS will correctly add a linked entry to it in the project, but it will not end up in the /bin directory of the application, so the validator will not have the core structuredefinitions available.

Either tune NuGet to make the build include this in the output OR change the CoreZip resolver so it will locate the validation.zip in the nuget cache somehow.

**Comment by marcovisserFurore** [comment]
This has already been solved in commit https://github.com/ewoutkramer/fhir-net-api/commit/610f849035b37b42446a63384d8e777090dd60e8. 

I've tested this by creating a new console project in Visual Studio. Added the package Hl7.Fhir.Specification.STU3. After compiling the console project the specification.zip is located in the bin directory of the console project and can be located by ZipSource
