### ISSUE TITLE
MSBuild integrated package restore still enabled for Hl7.Fhir.Specification.Tests project

### ISSUE THREAD

**Issue by rlipenta** [ewoutkramer/fhir-net-api#54]
Encounter the following error when attempting to build a fresh clone from GitHub:

> Error	1	This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\fhir-net-api\src\\.nuget\NuGet.targets.	C:\fhir-net-api\src\Hl7.Fhir.Specification.Tests\Hl7.Fhir.Specification.Tests.csproj	218	5	Hl7.Fhir.Specification.Tests

Removal of the following block in the Hl7.Fhir.Specification.Tests.csproj file should resolve this issue:

>```   <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />
  </Target>```

It looks like there was an attempt on January 14th to remove MSBuild integrated package restore from the other projects in this repo - maybe this one was left out?

**Comment by ewoutkramer** [comment]
Don't know why this keeps coming up. Have removed this many times before, probably is re-inserted when Brian updates the cross-platform project in his visual studio.

**Comment by ewoutkramer** [comment]
VisualStudio has a tendency to keep inserting this. We have now tried to avoid this as much as possible. And then wait for vNext and its new NuGet management.
