### ISSUE TITLE
Hl7.Fhir.WebApi Question

### ISSUE THREAD

**Issue by BruceHunter** [ewoutkramer/fhir-net-api#541]
What is the purpose of Hl7.Fhir.WebApi? 

I'm only guessing, but this is to be used like a "Host" layer and inject a service layer that ties to our specific data back-end? (I'm thinking IdentityServer/IdentityManager as an example.)

The goal is to stand up .Net FHIR service tied to to a specific back-end structure.

Any help would be greatly helpful.

**Comment by brianpos** [comment]
Yes, that is what that layer is intended for. There is also an equivalent for.net core too.

**Comment by mthakershi** [comment]
Hello, when you say "equivalent for .net", is there a separate FHIR server project that is implemented on .NET core? I am running into issues while using the WebApi project to run it as a FHIR server. Is there a .net core alternative that is more mainstream or stable? Thanks again.

**Comment by brianpos** [comment]
Sorry, looks like the netcore version was only in my fork.

https://github.com/brianpos/fhir-net-api/tree/feature/netcore-webapi-stu3/src/Hl7.Fhir.NetCoreApi

And the project that shows the usage is here:
https://github.com/brianpos/fhir-net-api/tree/feature/netcore-webapi-stu3/src/Hl7.DemoFileSystemFhirServer
The key parts being `DirectoryResourceService` and `DirectorySystemService`
