### ISSUE TITLE
Date.ToDateTime failed to convert "1976-12-12"

### ISSUE THREAD

**Issue by lbcsy** [ewoutkramer/fhir-net-api#544]
Following code failed at ToDateTime():

private static void TestDateToDateTime()
		{
			var patient = new Patient() {BirthDate = "1976-12-12"};
			var dt = patient.BirthDateElement.ToDateTime();
			Console.Write(dt.Value);
		}

Hl7.Fhir.STU3 version 0.94.0

**Comment by ewoutkramer** [comment]
Fixed.
