### ISSUE TITLE
Support XML/JSON serialization to in-memory DOM

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#545]
If a client needs to perform some further processing on the generated serialization output, then currently it is necessary to first serialize to XML/JSON string, then deserialize the output back to an in-memory XML/JSON object model.

For example, the Forge XML view parses the serialized XML output string back into an XML DOM in order to perform syntax highlighting. Currently, this is quite a CPU- and memory-intensive operation.

Would be more efficient if the API would also support serialization to an in-memory DOM. This would allow clients to skip the intermediate string serialization altogether.

Also see: https://stackoverflow.com/a/1347364

**Comment by tstolker** [comment]
Hi Michel,

There is no need to first serialize; given that you can use client.LastBodyAsText.

Best regards,

Theo.

**Comment by brianpos** [comment]
Or use the streaming serializers with no string or the inavigable interface that the xsl can work on Ewout created.

**Comment by wmrutten** [comment]
I don't think that will help. In Forge, the edited profile is internally represented as a FHIR (StructureDefinition) PoCo. The application needs to display the model as formatted XML (for the preview tab). The rendering logic takes an XML DOM and generates a XAML DOM that is injected into the view. This operation needs to be fast and GC friendly. Therefore, Forge needs to efficiently serialize a FHIR PoCo to an XML DOM, i.e. from one object model to another. Preferably directly, without any intermediate steps. I'm proposing for the FHIR API to implement and expose such a serialization method. as it would improve efficiency in scenario's such as described. The article on SO explains how this can be implemented.
And I would also like to have serialization from FHIR PoCo to JSON DOM.

**Comment by wmrutten** [comment]
Brian explained how I can leverage the Xml/Json navigators, so I'm going to try that. Thanks B!
