### ISSUE TITLE
Does not handle retrieving the history for a Binary Resource

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#55]
The BodyAsResource routine calls IsBinaryResponse which determines if the content is Binary based on the URL, which in these cases is incorrect. (It should at least check that _history is not in there, and potentially if the _format parameter is on there too)
Test cases:
http://fhir-dev.healthintersections.com.au/open/Binary/_history
http://fhir-dev.healthintersections.com.au/open/Binary/1e404af3-077f-4bee-b7a6-a9be97e1ce32/_history
http://fhir-dev.healthintersections.com.au/open/Binary/example/_history

**Comment by ewoutkramer** [comment]
Yep, a honest and sincere bug.

**Comment by ewoutkramer** [comment]
Fixed

**Comment by ewoutkramer** [comment]
Oops. Still did not work for /_history/1. Another fix.
