### ISSUE TITLE
FHIR Validator Speed

### ISSUE THREAD

**Issue by dekkerc** [ewoutkramer/fhir-net-api#551]
I am currently using the C# FHIR Validation.Validator to validate that incoming FHIR objects are properly formatted. The issue I am coming across is the speed of the validator. I am wondering if there is any way to speed up the execution of this validator, or if there is another, faster method of validation that anyone has come across

**Comment by ewoutkramer** [comment]
Validation will be slow the first time around - it needs to go out and find all the type definitions (Which might be hundreds).  It's therefore useful to create a CachedResolver() once, keep a reference to it, and pass it to different instances of the validator.  Of course, you could also re-use the same validator for multiple validation operations.
