### ISSUE TITLE
Validator throws error trying to check non-existing code in coding

### ISSUE THREAD

**Issue by mbaltus** [ewoutkramer/fhir-net-api#559]
When validating a resource with a coding that just has a display value, the validator tries to call the terminoligy service with the non-existing code, and throws this error:

 `Terminology service call failed for binding at Observation.code: The argument 'code' is null or empty.`

This is the Observation I tried to validate:

```
<Observation xmlns="http://hl7.org/fhir">
	<status value="final" />
	<code>
		<coding>
			<display value="No code here, just a display" />
		</coding>
		<coding>
			<system value="urn:oid:1.2.3.4.5" />
			<code value="16" />
			<display value="Here's a code" />
		</coding>
	</code>
	<subject>
		<reference value="Patient/somepatient" />
	</subject>
</Observation>
```

Switching the order of the codings eliminates the error message.

**Comment by ewoutkramer** [comment]
Found the problem: if a CC had a Coding without any code the validator would catch it, but if one of the codes was empty, the validation of the CC would be forwarded to the terminology service (correct). However, the LocalTerminologyService could not handle Codings without a code (throw an explicit argument null).  Now made sure the LTS will return an OperationOutcome that the code was empty.
