### ISSUE TITLE
FhirPath cache without lock()

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#561]
The lock() in IValueProviderFPExtensions._cache takes a lot of time, as my profiler revealed.
Consider to replace it with an implementation based on ConcurrentDictionary, available in .NetStandard 1.1 and up, and .NET 4.0 and up.

**Comment by cknaap** [comment]
The same problem occurs in the CachedResolver.

**Comment by wmrutten** [comment]
API locking strategy is quite crude yet, there is definitely room for improvement.
Currently, CachedResolver.Cache<T>.Get immediately takes a lock. Possibly we can rewrite this method to an optimistic locking strategy?
