### ISSUE TITLE
Version on .NET Core?

### ISSUE THREAD

**Issue by johns397** [ewoutkramer/fhir-net-api#568]
Has there been an effort to get this to work on .NET Core (2.0?) instead of .NET Framework?   Also, the Nuget package seems to reference an older version of Newtonsoft, has that been updated?

(this question is for the STU3 version.)

Thanks,
   John

**Comment by johns397** [comment]
I've tried downloading the STU3 sources and compiling it with all the .csproj files changed to netcoreapp2.0 and almost everything compiles except for the Hl7.Fhir.Specification.Summary, I believe because "NET_FILESYSTEM" must not be defined in NET Core 2.0.   Also, I ran into a problem with the Hl7.Fhir.Core.Tests.Rest.FhirClientTests in that the CompressRequestBody was not supported, is this also because of .NET Core?

**Comment by brianpos** [comment]
I was pretty sure it already works with net core 2.
I have this bugger package added to my fhirfederator project here on GitHub which is an aspnetcore project.
If you find things not working, we're happy to look at a pull request

**Comment by ewoutkramer** [comment]
I don't mind going to netstandard 2.0, but that means no more support for windows 8, and windows phone (silverlight)?  Is that problematic?  Or should we switch to 1.2 and 2.0?

**Comment by kfrancis** [comment]
I'd suggest switching to 2, windows phone isn't supported anymore and Net45+ handles everything that you'll lose. We're not even considering supporting anything below netstandard 2.0, as with many others.

**Comment by johns397** [comment]
@brianpos - I tried it with the nuget STU3 package and I ran into problems, partially because of NET Core 2.0 but I think also because in our code we are using a newer version of Newtonsoft (11.?) so that conflicts.  I can try again to be sure.

@ewoutkramer - it would be nice to have a NET 2.0 Code (or soon 2.1 when MS releases 2.1) since most of this code doesn't have any UI that would need NET Framework code (I think).  I did run into problems though when I tried to compile all of this with netcoreapp2.0 specified in all the .csproj files as I mentioned above.  I think the main problem is the NET_FILESYSTEM handling which I assume it tries to compile the FHIR spec into a object model, but NET Core filesystem is not there.  (I saw somewhere a suggestion to use IFileProvider, but didn't go look further).   The other problem I mentioned with the CompressRequestBody  I believe came about because I had to get a newer version of the System.IO.Compression (4.1.0) nuget package.

**Comment by johns397** [comment]
Any updates on this?   I thought this was tagged for the Colonge milestone and I just saw your announcement about new "Colonia release" so I thought I'd check to see if there was any progress made on this?

**Comment by ewoutkramer** [comment]
The current nugets already work on .NET Core 1.x/2.x (in fact, all our products using this API are .NET Core 2.0, if I am not mistaken, @mharthoorn?), so you wouldn't need a recompile.

The dependency problems - I think we should aim at as low a version as possible - so I wouldn't update newtonsoft, unless we really need to.  By the same logic, I should probably use an older version of IO.Compression to fix your problems - if that does not have side-effects for us?

**Comment by brianpos** [comment]
No issues I know of (provided you permit newer for those doing newer)

**Comment by ewoutkramer** [comment]
Ok, so I think there's some confusion in this thread about running the APIs in .NET Core 2.0 (which you can already do) and porting it to netstandard 2.0. Let me emphasize one more our current libraries are built against netstandard 1.0 and 1.1 and thus can be run on Core 2.0 - no recompilation necessary.

Second, we'll have to investigate the move to netstandard 2.0.  Since the API surface of 2.0 is much more aligned with 4.5 etc. I expect this will actually reduce code.

Are there any volunteers wanting to give this a try?  I'll be quite busy the next months updating other parts of the API......

**Comment by IvanFarkas** [comment]
@ewoutkramer I'd like to help to port **HL7 FHIR** to **.NET Core 2.1.1** and **.NET Core 3.0**.

**Comment by ewoutkramer** [comment]
Hi Ivan, that would be welcome!  I expect it would reduce the number of `#ifdefs` in the source code, since the API surface is more complete.  Just trying out what happens if we upgrade the "targetFrameworks" from netstandard 1.1 to netstandard 2.0 would be interesting to undertake!

**Comment by IvanFarkas** [comment]
Absolutely.
Independent from the port process, is there a discount coupon I can use for the **[HL7 FHIR Fundamentals Course](http://www.hl7.org/events/fhir_fun.cfm)** that I can use?
I am in between jobs, and that would be a great help.
I am available to hire as a consultant or remote resource.
**[Qualifications](https://1drv.ms/b/s!AkknbEcxgYr0lmFNECQ8KuSjFyce)**

**Comment by IvanFarkas** [comment]
@ewoutkramer Upgraded to .Net Framework 4.7.1, .NET Standard 2.0, latest NuGet packages.
**Created [pull request](https://github.com/ewoutkramer/fhir-net-api/pull/639)**. (netstandard20-r4 -> master-r4)

**Comment by ewoutkramer** [comment]
Hi Ivan, thanks!  I don't know anything about discount coupons, but Sadhana (sadhana@hl7.org) would know...

**Comment by ewoutkramer** [comment]
Done as part of #699.
