### ISSUE TITLE
Prefer header not set for Update (PUT) calls

### ISSUE THREAD

**Issue by Joelmccarthy** [ewoutkramer/fhir-net-api#569]
**Expected behavior:** For Create (POST) calls, the `FhirClient` is implemented to set a Prefer header, as detailed in the [FHIR spec](https://www.hl7.org/fhir/http.html#2.21.0.5.2), which indicates to the server whether it should return the created Resource, OperationOutcome, or nothing. The header is set using the `FhirClient.PreferredReturn` property. If the client sets `Prefer: return=representation` (expecting the full Resource in the response), but the server ignores the header and returns an OperationOutcome, the Client will immediately perform a GET call to retrieve the full Resource (see `FhirClient.executeAsync<TResource>(Bundle tx, IEnumerable<HttpStatusCode> expect)`).

**Issue:** For Update (PUT) calls, the `FhirClient` works similarly, but does not set the Prefer header on the request. This means that, when `FhirClient.PreferredReturn=Prefer.ReturnRepresentation` (as is the default), the client fails to tell the server to return the full Resource. If the server returns OperationOutcome or nothing, the client will then immediately perform a GET to retrieve the resource. This effectively means that (given `FhirClient.PreferredReturn=Prefer.ReturnRepresentation` and a server that defaults to returning OperationOutcome if no Prefer header is set) the client will always perform two calls for every Update call, a PUT and then a GET.

**Fix:** I believe this could be fixed very simply in the `Hl7.Fhir.Rest.EntryToHttpExtensions.ToHttpRequest` method. The line that sets the Prefer header looks like this: 
`if (interactionType == TransactionBuilder.InteractionType.Create && returnPreference != null)`
`                request.Headers["Prefer"] = "return=" + PrimitiveTypeConverter.ConvertTo<string>(returnPreference);`. 
This will only set the header if the interaction type is 'Create'. So we can simply amend the if statement as follows to account for 'Update' as well:
`if ((interactionType == TransactionBuilder.InteractionType.Create || interactionType == TransactionBuilder.InteractionType.Update) && returnPreference != null)`.

**Temporary workaround:** For now, I am dealing with this issue by overriding the `FhirClient.BeforeRequest` method to add the Prefer header to 'PUT' calls, but it would be better to fix it in the client itself.

Is there any reason why the `FhirClient` is set up the way it currently is? If not, I believe this should be considered a bug that doubles the number of HTTP calls per Update call, with a fortunately quite simple fix.

**Comment by ewoutkramer** [comment]
Ah, yes, I think I noticed this too when working on the new FhirClient (#535).

**Comment by ewoutkramer** [comment]
Interestingly, this should be for create, update and _patch_. Although we have no support for patch yet in the API, I added it already so we won't forget it when we do add patch support in the future.
