### ISSUE TITLE
Spark FhirMediaType can be merged into Hl7.Fhir.Rest.ContentType

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#57]
https://github.com/furore-fhir/spark/blob/develop/Spark.Engine/Core/FhirMediaType.cs

**Comment by ewoutkramer** [comment]
@cknaap, is this still a good idea (but now for Vonk?)

**Comment by ewoutkramer** [comment]
No reply. Closing the issue.

**Comment by brianpos** [comment]
I've probably already dealt with this into the NetCoreApi amd Fhir.WebApi projects.
