### ISSUE TITLE
Unabel to resolve reference to profile x

### ISSUE THREAD

**Issue by dxh73** [ewoutkramer/fhir-net-api#580]
There appears to be an issue where the API is unable to resolve a reference to a profile, despite that url being resolvable via any web browser. 

Example from a patient.identifer element which incorporates an extension:

```xml
<identifier>
	<extension url="https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-NHSNumberVerificationStatus-1">
			<valueCodeableConcept>
				<coding>
					<system value="https://fhir.hl7.org.uk/STU3/CodeSystem/CareConnect-NHSNumberVerificationStatus-1"/>
					<code value="01"/>
					<display value="Number present and verified"/>
				</coding>
					</valueCodeableConcept>
					</extension>
		<system value="https://fhir.nhs.uk/Id/nhs-number"/>
		<value value="9912003888"/>
</identifier>
```

https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-NHSNumberVerificationStatus-1 is being reported as unable to resolve, yet this resolves perfectly fine in a browser.

Exact error is:

Unable to resolve reference to profile 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-NHSNumberVerificationStatus-1' (at Bundle.entry[3].resource[0].identifier[0].extension[0])

**Comment by wmrutten** [comment]
The FHIR API defines a "IResourceResolver" interface that abstracts the resolving.
The API also provides a set of concrete resolver implementations, e.g. DirectorySource for resolving resources from disk and WebSource for resolving resources from a remote server. A FHIR server would typically implement a custom database resolver. The actual resolving strategy is hidden from the consumer. Usually, profile references are resolved from a well-known (internal, controlled) location; production systems will typically be barred from performing remote requests.
To ensure that resolving succeeds, you could for example configure a WebSource to automatically resolve profiles from a FHIR server. Or you could download all relevant profiles to a local folder on disk, then use a DirectorySource to resolve references locally.
The unit tests in the API demonstrate how to configure and use the different resolvers.
