### ISSUE TITLE
Getting UnsupportedMediaFormat & body is null

### ISSUE THREAD

**Issue by shyam-dhanotiya** [ewoutkramer/fhir-net-api#581]
Hi, 

I am new to Fhir implementation.

I have created a FhirClient Object and calling Read & Create method . In case of read method it is calling the API but not coming back to caller.

In case of Fhirclientobject.Create method its throwing UnsupportedMediaFormat & body is null exception. Will share the code snippet if needed. 
Please help

**Comment by shyam-dhanotiya** [comment]
I am getting following exception in FhirClient => LastBodyAsTest 

{"Message":"The request entity's media type 'application/fhir+json' is not supported for this resource.","ExceptionMessage":"No MediaTypeFormatter is available to read an object of type 'Resource' from content with media type 'application/fhir+json'.","ExceptionType":"System.Net.Http.UnsupportedMediaTypeException","StackTrace":"   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)\r\n   at System.Web.Http.ModelBinding.FormatterParameterBinding.ReadContentAsync(HttpRequestMessage request, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)"}

**Comment by mbaltus** [comment]
Hi, I will take this up from our support email address so we don't clutter the issue list.
