### ISSUE TITLE
ArtifactSummary - move method LoadResource<T> to ISummarySource

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#584]
The current (prototype) design of the ArtifactSummary class provides LoadResource methods designed to allow clients to fetch the full resource from a given ArtifactSummary instance. However this violates the single responsibility principle, as the IResourceResolver interface is responsible for resolving and loading resources; the ArtifactSummary class itself cannot provide a generic Load implementation that will support any resource resolver.

Suggestion for improvement:
- Remove the ArtifactSummary.Load... methods
- Add Load() method(s) to the ISummarySource interface that accept an ArtifactSummary parameter
- ISummarySource initializes the Origin and Position properties of each ArtifactSummary parameter (with opaque values that are specific to the resolver implementation)
- ISummarySource.Load method(s) use the Origin and Position properties, initialized by the source itself, to resolve and load the full target resource.

**Comment by ewoutkramer** [comment]
Sounds reasonable.

**Comment by wmrutten** [comment]
Fixed in release 0.96
