### ISSUE TITLE
GET [base]/MedicationDispense/[id]

### ISSUE THREAD

**Issue by kfrancis** [ewoutkramer/fhir-net-api#586]
How can I do a Read() where the ID is part of the url segment and not a query string argument?

The following is what I would expect:
```c#
    var result = client.SearchById<MedicationDispense>(id);
```

But this produces `[base]/MedicationDispense/?_id={id value here}` rather than `[base]/MedicationDispense/{id value here}`.

Is there a different way to do this?

**Comment by mbaltus** [comment]
Yes, just as you said, perform a Read() instead of a Search().

`var result = client.Read<MedicationDispense>("MedicationDispense/{id value here}");`

**Comment by kfrancis** [comment]
This is what I receive as a result:

> Must be a FHIR REST url containing the resource type in its path
> Parameter name: location

**Comment by ewoutkramer** [comment]
No response - closing the issue.
