### ISSUE TITLE
Date Time format yyyy-MM-DDTHH:mm:ssZ

### ISSUE THREAD

**Issue by abdul2505** [ewoutkramer/fhir-net-api#598]
Hi, I am facing an issue,

I am creating an bundle object and setting the Metadata property "LastUpdated" as DateTimeOffset.Now;

When the FHIR JSON is output to response, it is showing as
    "resourceType": "Bundle",
    "id": "40127cc7-20c1-4dfc-99bc-01c06f88ebe0",
    "meta": {
        "lastUpdated": "2018-05-06T17:58:14.43+03:00"
    },

However, our client expects the lastUpdated format to be as "yyyy-MM-DDT:HH:mm:ssZ". But I get ms+UTCOff time instead of Z.

Please help us how we can achieve this lastUpdated to be of expected format while serializing the resource content to JSON. 

Your help is highly appreciated.

**Comment by brianpos** [comment]
This is not an issue with the API, this is what the server is returning to you.
What server are you using? The zone format is supported by FHIR, so the server isn't doing something wrong here.

**Comment by brianpos** [comment]
The FHIR client doesn't manipulate the date that you give it. If you want to use utc, then give the object utc DateTimeOffset.UtcNow;
The DateTimeOffset.Now returns a date that has the local machines timezone.

**Comment by abdul2505** [comment]
Thanks Brian. My problem is my FHIR Server doesn't the format the date field value to be as "yyyy-MM-DDTHH:mm:ssZ" but formatting it as "yyyy-MM-DDTHH:mm:ss:ms+03:00" . I need my FHIR server to format the date value as "yyyy-MM-DDTHH:mm:ssZ" on the value assigned to any datetime field. 

I should not use DateTimeOffset.UtcNow as I will have corresponding retrieved from my DB to be assigned to respective DateTime field of my response object.

**Comment by ewoutkramer** [comment]
But you can change the timezone - the timezone to be used is in the DateTimeOffset, so after getting it out of the database, you can convert the DateTimeOffset (or rather, you move the timezone) to Zulu, and then setting it on the POCO, right?

**Comment by brianpos** [comment]
I'd suggest stepping through the code to find where you're doing it. I don't believe the fhir client messes with it at all, in fact the native format in the object model underneath is a string.
So must be in your code.
(Your client code should really be able to handle that difference... may not always be your server providing the data)

**Comment by abdul2505** [comment]
Thanks Brian and Ewout for your responses. I think i am not been to clarify my concern till this point.
My General Requirement is that All Date time fields to be serialized in this format yyyy-MM-DDT:HH:mm:ssZ   Since we are using FHIRJsonSerializer to serialize the resource i have no control over setting the cutom Format. If i use default JsonFormatter i could achieve it by adding below to my WebAPIConfig.

IsoDateTimeConverter converter = new IsoDateTimeConverter
              {
                  DateTimeStyles = DateTimeStyles.AdjustToUniversal,
                 DateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'Z'"
              };
              config.Formatters.JsonFormatter.SerializerSettings.Converters.Add(converter);](url)


JSON RESULT BY FHIR JSON SERIALIZER , 
You can see the datetime fields are not in desired format.
 
   "resourceType": "Bundle",
    "id": "7bc339cc-2073-46ed-9224-16b53aeb27bf",
    "meta": {
        "lastUpdated": "2018-05-07T14:58:04.055+03:00"
     "entry": [
        {
            "fullUrl": "http://<baseURL>/Slot/1-10-20180508-0800-15",
            "resource": {
                "resourceType": "Slot",
                "id": "1-10-20180508-0800-15",
                "appointmentType": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v2/0276",
                            "code": "ROUTINE",
                            "display": "ROUTINE"
                        }
                    ],
                    "text": ""
                },
                "schedule": {
                    "reference": "schedule",
                    "display": "schedule/1-10-20180508-0800"
                },
                "status": "free",
                "start": "2018-05-08T08:00:00.00+03:00",
                "end": "2018-05-08T08:15:00.00+03:00",
                "overbooked": false,
                "comment": ""
            },
            "search": {
                "mode": "match"
            }
        },

**Comment by Farrukh85** [comment]
I think you want FMT_FULL to be set dynamically before serialization. so that you can have FMT_FULL =  yyyy-MM-DDTHH:mm:ssZ to  FMT_FULL = "yyyy-MM-dd'T'HH:mm:ss.FFFK".

**Comment by brianpos** [comment]
I wouldn't mess with that, just get your source value right going into the model. If you have a DateTime type in your DB, then you'll need to ensure that when you create it you set it know that it is a UTC time, and not a local time.
Getting timezones right when your DB doesn't know about them is hard, and you need to be careful.
(esp if you host in cloud DBs that aren't in your local timezone)

**Comment by Farrukh85** [comment]
It is being converted exclusively to format specified in FMT_FULL, what ever source he will set it will be serialized in this format. isent it??

 return XmlConvert.ToString((DateTimeOffset)value, FMT_FULL);

**Comment by abdul2505** [comment]
Thanks Farrukh. You got me right. 
When I am passing my required resource object to  FHIRJSONSerializer class, the output serialized FHIR JSON from serialize method should have the format for all date time field value should be as "dd-MM-yyyyTHH:mm:ssT" instead of default current format "yyyy-MM-ddTHH:mm:ss.FFFK"

Is there any way in FHIR.Net API to achieve this. 
Appreciate your kind help in this regards.

**Comment by abdul2505** [comment]
Thanks Ewout, your understanding is right. 

Please find my response for your points:

•	Do you have control over your timestamps, so you can convert them to Z. So, can you do ToUniversalTime(), or should the API - using some configuration - translate them to UTC for you?
<> Yes , we have control over assigning the time stamp to corresponding datetime field in the resource, hence we can use ToUniversalTime() while assigning the timestamp value.

•	If translated to UTC (either by you or API), it should display "Z" instead of "+00:00"?
<**Abdul**> Yes, when my FHIR resource is serialized using “FhirJsonSerializer” class, the serialized string should display Z instead of "+00:00". The current SerializeToString(Resource) method always display as “+00:00”

•	Or are other timezones ok (so +03:00), but if it is at +00:00, it should be displayed as "Z"?
<**Abdul**> Yes if it is Zulu time, then it should display as “Z”
  
And it would be helpful, if we have control over to set the format while serializing the resource. This way we can explicitly specify the datetime field to be displayed as accordingly to the expected format instead of default format as it is built in with FHIR.Net API.

**Comment by brianpos** [comment]
The string property that stores the value is what is serialized, not the date converted property (due to the partials). So I would expect that its the setter that you need mess with, not serializer

**Comment by abdul2505** [comment]
Yes Brian. You are right. 
I need to have the setter to convert the date time string to format "dd-MM-yyyyTHH:mm:ssZ" once I am serializing the resource object. Is there any way to achieve. Appreciate your kind help in this regards.

**Comment by ewoutkramer** [comment]
Looking at the standard format strings (https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-k-custom-format-specifier), there's no way to have +xx:xx/-xx:xx for non-UTC timezones, and Z for UTC - it would always show +00:00.   So, just making FMT_FULL a customizable string would not work, since you need to change the format string depending on the timezone of the `DateTimeOffset` being formatted.   The only solution I can see is adding a static global that you'd need to set.  And this seems such a corner case to me.... what's the problem with having +00:00 instead of Z, they mean the same thing, no?  Is this because the Z is more visually pleasing?

**Comment by abdul2505** [comment]
Thanks for your assistance Ewout. 

I was expecting something like this, we are able to  provide a custom dateformat when serializing to JSON using Netwonsoft. So here we specify the format of datetime field in serializer settings and the resultant json gives me all the datetime field value in this format "yyyy-MM-ddThh:mm:ssZ".
//
JsonConvert.SerializeObject(someObject, new JsonSerializerSettings() { DateFormatString = "yyyy-MM-ddThh:mm:ssZ" });
//

However, i couldn't see the similar option in FhirJsonSerializer class. 
As per your comment above it is that we do not have to mess with FMT_FULL to make it as a customizable string. So I understood it is not possible at this time. 

Many thanks and appreciate you and Brian for helping me in this regards. 
We shall close this thread. Thanks.

**Comment by StevenDevooght** [comment]
Hi,

We are integrating with a government FHIR server and they only allow datetimes in the "dd-MM-yyyyTHH:mm:ssZ" format. Is there already a possibility to change the JSON serialization behavior of datetimes?

**Comment by ewoutkramer** [comment]
No, since that time format is not allowed in FHIR. This government FHIR server is not FHIR compliant...

**Comment by ewoutkramer** [comment]
See http://hl7.org/fhir/datatypes.html#primitive, under "instance" or "date" etc.

**Comment by StevenDevooght** [comment]
Hi,

My original question was not correct. I clarified it.

**Comment by ewoutkramer** [comment]
No, you cannot change it - it is currently fixed to `public const string FMT_FULL = "yyyy-MM-dd'T'HH:mm:ss.FFFFFFFK";`
And the .NET platform will use "+00:00" instead of "Z" here.

We *are* working on a new version of the serializer that is more customizable and that is released this year, but that won't help you now.

Still, this should not be your problem, the FHIR serialization allows both "Z" and "+00:00", so the government's server should do too to be able to claim it is FHIR compliant....

**Comment by AshleyJButcher** [comment]
> No, you cannot change it - it is currently fixed to `public const string FMT_FULL = "yyyy-MM-dd'T'HH:mm:ss.FFFFFFFK";` And the .NET platform will use "+00:00" instead of "Z" here.
> 
> We _are_ working on a new version of the serializer that is more customizable and that is released this year, but that won't help you now.
> 
> Still, this should not be your problem, the FHIR serialization allows both "Z" and "+00:00", so the government's server must accept that to be able to claim FHIR conformance.




Was this new version released?, i am experiencing the same issue
