### ISSUE TITLE
FhirPath invocation in parrallel causes problems

### ISSUE THREAD

**Issue by marcovisserFurore** [ewoutkramer/fhir-net-api#599]
Running a FhirPath expression in parallel will sometimes result in an outcome of another thread. @cknaap  wrote an unittest to prove it (see PR #588)

**Comment by ewoutkramer** [comment]
@marcovisserFurore  and I think we found it!! 💪 🎉

**Comment by marcovisserFurore** [comment]
Solved in PR #600
