### ISSUE TITLE
Serializing a bundle with summary=true results in empty bundle 

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#60]
There is a need to serialize a bundle that contains the summaries of the resources in the bundle. But serializing a bundle with summary=true results in an empty bundle (the bundle it self is summary'd).
```csharp
XmlWriter writer = new XmlTextWriter(writeStream, Encoding.UTF8);
FhirSerializer.SerializeResource(bundle, writer, summary: true);
```

**Comment by ewoutkramer** [comment]
Which is kind of correct, since the Bundle's summary probably does not include its Entries ;-)  But that's pretty useless. This requires a specific special-case in the serialization of Bundles

**Comment by ewoutkramer** [comment]
I have added this special exception case to the serializer, so it will serialize all of bundle's elements, no matter what.
