### ISSUE TITLE
Serialization throws null ref exception on empty XML resource elements

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#602]
Where a contained resource is only the type, you get a null reference exception

```
    <resource>
      <OperationOutcome />
    </resource>
```

**Comment by ewoutkramer** [comment]
@brianpos - will you do pick this up for the next milestone?

**Comment by brianpos** [comment]
Sure, I'll be back on deck from the 19th I think 😊

**Comment by ewoutkramer** [comment]
Fixed by #646.
