### ISSUE TITLE
Slow performance of FHIR resource serializer

### ISSUE THREAD

**Issue by dtoring** [ewoutkramer/fhir-net-api#604]
Serializing the same data (same JSON output) using Json.net serializer is about four times faster than the FHIR resource serializer. Currently, FHIR resource serializer is using reflection methods GetValue() and SetValue() to do the job. Is there an immediate plan to generate getters/setters using pre-compiled expression trees for performance?

**Comment by ewoutkramer** [comment]
Yes, I actually have a branch (#450 ) ready for some time, but I found the performance gain to be negligible (contrary to my expectations, I must say).  Could so take a look at that PR to see whether this does what you want?

**Comment by ewoutkramer** [comment]
Well, it seems in this PR, the serializer isn't actually using the generated methods, but in any case, take a look - if this is a good start can work on it to see if it's worth doing!

**Comment by dtoring** [comment]
From my test results, using pre-compiled expression trees is 15% faster.
![capturepre](https://user-images.githubusercontent.com/36066150/40527432-68c38aaa-6027-11e8-9523-670f89bf055e.PNG)

**Comment by dtoring** [comment]
I'm using to string.

var serialized = string.Empty;
var stopWatch = new Stopwatch();

for (var x = 0; x < 10; x++)
{
     stopWatch.Restart();
     serialized = new FhirJsonSerializer().SerializeToString(bundle);
     stopWatch.Stop();
     File.AppendAllText("result.txt", stopWatch.ElapsedMilliseconds.ToString() + " \n"); 
}

**Comment by ewoutkramer** [comment]
Well, I don't mind pulling in the dynamically generated setters/getters, what do you think @brianpos?

**Comment by brianpos** [comment]
I don't have any objections, would have liked to run it a while myself, but that's not going to happen for a couple of weeks as I'm still on extended leave (in Austra at the moment).
