### ISSUE TITLE
FhirPath does not support polymorphism

### ISSUE THREAD

**Issue by marcovisserFurore** [ewoutkramer/fhir-net-api#606]
The following expression does not resolve to an element:

`Resource.meta.lastUpdated`

When I try to resolve `Patient.meta.lastUpdated` it does work. So polymorphism does not work in FhirPath.

The following unittest will prove this:

```
        [Fact]
        public void TestFhirPathPolymporphism()
        {
            var patient = new Hl7.Fhir.Model.Patient() { Active = false };
            patient.Meta = new Meta() { LastUpdated = new DateTimeOffset(2018, 5, 24, 14, 48, 0, TimeSpan.Zero) };
            var nav = new PocoNavigator(patient);

            var result = nav.Select("Resource.meta.lastUpdated");
            Assert.Single(result);
            Assert.Equal(PartialDateTime.Parse("2018-05-24T14:48:00+00:00"), result.First().Value);
        }
```

**Comment by brianpos** [comment]
Is this a valid fhirpath expression?

**Comment by ewoutkramer** [comment]
Unfortunately, yes - at least they are used in the search parameters.  It is not documented - that's why I had not implemented it, and it seems to make sense, but it surely is underdocumented....

**Comment by ewoutkramer** [comment]
Started a discussion in Zulip: https://chat.fhir.org/#narrow/stream/115-fhirpath/subject/Polymorphic.20roots.20in.20FHIRPath

**Comment by brianpos** [comment]
Ah, I've manually handled those. Will check them over.
