### ISSUE TITLE
Wrong target types for the STU3 AllergyIntolerance.patient search parameter

### ISSUE THREAD

**Issue by michelemottini** [ewoutkramer/fhir-net-api#609]
It is `Patient` and `Group` [here](https://github.com/ewoutkramer/fhir-net-api/blob/master-stu3/src/Hl7.Fhir.Core/Model/Generated/Template-ModelInfo.cs#L585) but according to [the specs](http://hl7.org/fhir/STU3/allergyintolerance.html#search) it should be just `Patient`

**Comment by ewoutkramer** [comment]
Indeed, we've discussed this before: #339.  Back then, I had closed the issue expecting a technical correction from HL7. Failing that, I think we'll need to manually correct this in our input files. Have re-openen #339 to get this going.

**Comment by michelemottini** [comment]
Thanks and apologies, I completely forgot that I already filed that issue
