### ISSUE TITLE
ResourceEntry<T>.SelfLink returns a URL address with an ending "/" character

### ISSUE THREAD

**Issue by kostas1** [ewoutkramer/fhir-net-api#61]
Our transactions kept failing until we noticed we're posting resource references with history tags ending with "/" character, for instance "Organization/123456/_history/123456/". 

That came from a SelfLink property on a ResourceEntry<Organization>. When browsing the server SelfLink has no "/" in the end.

Removing an ending "/" solved the problem, but this should be fixed at a library level.

Thanks.

**Comment by ewoutkramer** [comment]
Do I understand correctly that the API adds "/" to the SelfLink in some circumstances? Or would you like to be able to assign URLs ending with "/" to the SelfLink and have the API remove them for you?

**Comment by kostas1** [comment]
Former. Server returned XML:
<link href="Composition/1000010644/_history/1000026051" rel="self"/>
Library object ResourceEntry<Composition>.SelfLink:
"Composition/1000010644/_history/1000026051/"

That looks like an error.

**Comment by ewoutkramer** [comment]
Tested that this behaviour is fixed in DSTU2.
