### ISSUE TITLE
Invoice.PriceComponentComponent does not match R4 draft

### ISSUE THREAD

**Issue by mattiasflodin** [ewoutkramer/fhir-net-api#621]
There seems to be some mixup in the element types of Invoice.PriceComponentComponent. According to [http://build.fhir.org/invoice.html](http://build.fhir.org/invoice.html), factor should be of type decimal and amount should be of type Money. But in Invoice.cs in the develop-r4 branch, the types of these fields are swapped such that factor is of type Money and amount is of type decimal. The description of these elements in the docstrings also seem to have a similar mismatch.

**Comment by ewoutkramer** [comment]
@brianpos - this probably is because we haven't regenerated the R4 classes for some time?

**Comment by brianpos** [comment]
It was last generated for the May connectathon, and next planned build will be as the R4 closes out for the next ballot.

**Comment by ewoutkramer** [comment]
Ah, yes, I can see here (http://hl7.org/fhir/2018May/invoice.html) that it was reversed back then.  So, we'll need to regenerate the classes - which we will do after QA in august.

**Comment by ewoutkramer** [comment]
Fixed in 41a839a14c9f04b710439c2011d02adcfacea39d.
