### ISSUE TITLE
Serialization of Condition Fhir object

### ISSUE THREAD

**Issue by hemalkadakia** [ewoutkramer/fhir-net-api#623]
we are using WCF service and returning Condition object as our response DTO. 

We get an exception thrown from calling WCF operation. If we change our code to return Condition object as JSON string instead of an object then the same code works without any issues.

Does anyone know if there is an issue with Condition object?

thanks

**Comment by ewoutkramer** [comment]
I don't know exactly how WCF "auto-converts" between json and a FHIR POCO, but the standard datacontract serialization would not result in correct FHIR json or FHIR xml.

I have written an answer to a comparable question (just not for WCF) here: https://stackoverflow.com/questions/21117815/hl7-fhir-serialisation-to-json-in-asp-net-web-api/21137069#21137069

Hope that helps.

NB: Condition is no more special than any other resource - so there should be no problem (de)serializing it with the FHIR .NET API.
