### ISSUE TITLE
Validator incorrectly signals element containing just an extension as error 

### ISSUE THREAD

**Issue by mbaltus** [ewoutkramer/fhir-net-api#625]
In FHIR an element SHALL have a @value or a child element and the .Net validator errors on a construct like this.
```
<route>
   <extension url="http://hl7.org/fhir/StructureDefinition/iso21090-nullFlavor">
       <valueCode="NAV"/>
   </extension>
</route>
```

The official invariant in FHIR will not bark, because extension is a child element, but the .Net validator will.

See also discussion on Zulip: https://chat.fhir.org/#narrow/stream/4-implementers/subject/value.20or.20child.20or.20Null.3F

**Comment by ahenket** [comment]
Another example would be a masked identifier:

<identifier>
   <extension url="http://hl7.org/fhir/StructureDefinition/iso21090-nullFlavor">
       <valueCode="MSK"/>
   </extension>
</identifier>

or a positive infinity value in a range:

<valueRange>
    <low>
        <value value="1"/>
    </low>
    <high>
        <extension url="http://hl7.org/fhir/StructureDefinition/iso21090-nullFlavor">
            <valueCode value="PINF"/>
        </extension>
    </high>
</valueRange>

**Comment by ewoutkramer** [comment]
This is a bit confusing to me, since the error that @ahenket reported is about the validator returning "No code found in instance" in these cases, not "an element SHALL have a @value or a child element" (which comes from invariant ele-1).

**Comment by ewoutkramer** [comment]
So, I have probably created a duplicate here (#632)

**Comment by ewoutkramer** [comment]
I cannot reproduce @mbaltus behaviour, but I can totally reprodue the "no code found in instance" (#632). I will mark this as a duplicate.
