### ISSUE TITLE
Using FHIR.Net Object as Input Parameter to WebApi Method

### ISSUE THREAD

**Issue by JeffHumphry** [ewoutkramer/fhir-net-api#626]
I’m setting up an API to take incoming FHIR messages. For example, observations.

I noticed that I used the Model.Observation as an input parameter to my WebAPI method

        public HttpResponseMessage PostObservation(Observation observation)

most of the elements in the request JSON appear to be expecting some type of meta format:

Condensed example:

```
{  
   "subject":{  
      "referenceElement":{
        "value": "Patient/f201A"
      }
   }
}
```

Instead of the actual FHIR model, e.g.

```
{  
   "subject":{  
      "reference": "Patient/f201A"
   }
}

```
Do I need to include some type of attribute on my method to change the serialization?

I did review the links given in https://github.com/ewoutkramer/fhir-net-api/issues/186, but 1) I'm not sure how to put the pieces together, and 2) the examples look to deal with writing JSON into the response, not allowing for use of the FHIR.net objects as parameters to the request.

Thanks,
Jeff Humphry
Senior Software Architect | New Ocean Health Solutions
Eight Tower Bridge | 161 Washington Street, Suite 1110 | Conshohocken, PA 19428
610.952.9698 (m)

**Comment by mbaltus** [comment]
We solved this by parsing the incoming body to a FHIR object in the PostObservation method, instead of trying to receive it as an Observation parameter.
