### ISSUE TITLE
Is this a FHIR server?

### ISSUE THREAD

**Issue by mthakershi** [ewoutkramer/fhir-net-api#636]
Excuse my ignorance but is this a FHIR DSTU3 server? If yes, how can I build/host it? My workflow requires basic CRUD operations on certain entities like patient and care plan. Thanks for helping.

**Comment by brianpos** [comment]
The readme clearly notes that this is a client library with the models, serializers and rest interactions for working with a FHIR Server.
Some of us have used parts of it to create servers (Vonk/sqlonfhir/pyronet/spark), but this isn't a server project itself.

**Comment by mthakershi** [comment]
Thanks. What about the WebApi project that can be found at:
[https://github.com/ewoutkramer/fhir-net-api/tree/develop-stu3/src/Hl7.Fhir.WebApi]
Can this be used like a server?

**Comment by brianpos** [comment]
Yes, there is a demo of it https://github.com/ewoutkramer/fhir-net-api/tree/develop-stu3/src/Hl7.DemoFileSystemFhirServer
Not supported at all. Just an example.

**Comment by mbaltus** [comment]
If you need an out of the box FHIR server, you can also take a look at the [Vonk binaries](https://simplifier.net/vonk). Vonk is implemented using this API. If you have an existing database, and need a FHIR server to open up the data, [Vonk Facade](http://docs.simplifier.net/vonk/facade/facade.html) can be used.

**Comment by mthakershi** [comment]
I read through the Facade steps. I think I need Facade because I have an existing database that is in production. What I need is to be able to expose web API to authorized third-party systems to import/export data to/from our system. Do need a commercial license to use the Facade?

**Comment by mbaltus** [comment]
Hi! That is a question for the Vonk team actually. In the docs you will find the correct contact information.
But yes, if you use Vonk in production, you will need a production license. For testing, you can download a temporary evaluation license.

**Comment by mthakershi** [comment]
Sure. I will check it out. So I derive the following points so far:
1. The WebApi project isn't professionally supported. It is not a production candidate. Right?
2. There is no open source version of Spark/Vonk that supports current FHIR releases?

**Comment by mbaltus** [comment]
I can only answer 2:
Spark is open source, supporting FHIR DSTU2.
Vonk is not open source, supporting FHIR STU3.
