### ISSUE TITLE
Extensions permit any fhir datatype

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#652]
There is only a subset of valid types that can be used in extensions, however due to the extensible type just uses `element` as its type, any can be used.
This should preferably be a compile error, or at least an invalid cast exception.

**Comment by brianpos** [comment]
Just to give you an example of something that should not parse or be able to be generated from a model.
```
    <extension url="http://healthconnex.com.au/hcxd/HealthcareService/CoverageArea">
        <valueConceptDefinitionComponent>
            <code value="wh-c" />
            <display value="Whitehorse (C)" />
        </valueConceptDefinitionComponent>
    </extension>
```

**Comment by ewoutkramer** [comment]
The validator catches it, but the POCO model can't: any choice element is of type Any, and thus accepts any instance.  Since the C# has no facilities in its type system to define subsets at the point of use, I don't see how we can fix this....
