### ISSUE TITLE
FhirJsonSerializer loses accuracy on serializing DateTimeOffset (last 4 digits in ticks)

### ISSUE THREAD

**Issue by mustiks** [ewoutkramer/fhir-net-api#657]
Steps to reproduce:
` var patient = new Patient {Meta = new Meta{LastUpdated = DateTimeOffset.UtcNow}};`
 `           var json = new FhirJsonSerializer().SerializeToString(patient);`
 `           var res = new FhirJsonParser().Parse<Patient>(json);`
 `            Assert.IsTrue(patient.IsExactly(res));//failed`

patient.Meta.LastUpdated Ticks = 636687161278451357, 
but res.Meta.LastUpdated Ticks = 636687161278450000

**Comment by ewoutkramer** [comment]
@marcovisserFurore - sounds familiar?

**Comment by marcovisserFurore** [comment]
Solved by serializing DateTimeOffset the seven most significant digits of the seconds fraction; that is, it represents the ten millionths of a second in a date and time value.
