### ISSUE TITLE
Search parameters constants for resources

### ISSUE THREAD

**Issue by 33monkeys** [ewoutkramer/fhir-net-api#66]
It would be possible to add a search parameters constants for all resources.
For example:
class Patient: Resource {
...
public const address = "address";
...
public const given = "given";
...
}

and using it like Search.By(Patient.given, "Kramer")

**Comment by ewoutkramer** [comment]
Yes, this is a very good idea, and actually, it is done almost like this in HAPI for FHIR. We should copy that idea (and add some metadata about the parameter as well, so we have not only the name, but also the path and the search parameter type for example)

**Comment by brianpos** [comment]
Hmm, this content is in the modelinfo static class, still think we should have a static search Parma name const strings? (and accessor to get at the searchparam instance)

**Comment by ewoutkramer** [comment]
We have a more try-out of a more elaborate fluent interface [here](https://github.com/ewoutkramer/fhir-net-api/tree/ft-fluent-search/src/Hl7.Fhir.Core/FluentSearch), but I never implemented it....

**Comment by ewoutkramer** [comment]
We'll stick to just the stuff in ModelInfo, not enough demand to justify generating code for the search parameters.
