### ISSUE TITLE
FhirXmlParser ctor - latest alpha breaks binary incompatibility?

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#675]
Halfway updating Forge to the latest 1.0.0-alpha1 release, while using an external library that was build against previous API version, I received a compiler error complaining about a missing parameter-less constructor on FhirXmlParser.

Currently, FhirXmlParser exposes a ctor with an optional settings parameter:

`public FhirXmlParser(ParserSettings settings=null) : base(settings) {   }`

Apparently, the external library originally called a default ctor `FhirXmlParser()`, however this no longer exists in the latest version. And the new ctor is not *binary* compatible with the old default ctor. Of course, re-compiling the library against the latest API fixes the issue.

Suggestion: re-introduce the original default ctor and remove the default value from the new ctor:

```
public FhirXmlParser() : base() {   }

public FhirXmlParser(ParserSettings settings) : base(settings) {   }
```

And probably also for the underlying (public!) base class `BaseFhirParser`.

This provides the same behavior as the current logic, while maintaining binary compatibility to older API releases. This way, existing applications/libraries compiled against older API releases will keep functioning when bound at runtime to the new API release.

**Comment by ewoutkramer** [comment]
We are currently (and maybe never) aiming for binary compatibility.
