### ISSUE TITLE
Validator: Error on missing code while the code element is not mandatory

### ISSUE THREAD

**Issue by LilianMinne** [ewoutkramer/fhir-net-api#678]
The following example (based on the https://simplifier.net/HL7Norwayno-basis/no-basis-Patient profile) validates correctly: https://simplifier.net/velferdsteknologi2/patient-example-duplicate-2
But when the (not mandatory) code element is removed from the no-basis-bydel extension the validator complains that the code element is not present.

**Comment by ewoutkramer** [comment]
Duplicate of #559.
