### ISSUE TITLE
Immunization Date is string rather than DateTime

### ISSUE THREAD

**Issue by PBernhardt** [ewoutkramer/fhir-net-api#69]
Can work with string if necessary, but this is inconsistent with serialization strategy for other DateTime properties, which serialize as nullable DateTime. Perhaps because this is a required property and can't and shouldn't be serialized as nullable? Same goes for Immunization.ExpirationDate.

**Comment by ewoutkramer** [comment]
All FHIR date/datetimes are string since they can be partial (i.e. 1996-03), and as such cannot be represented by the native .NET DateTime type.  If you found inconsistencies here, I'd be interested to see some concrete examples so I can check the java POCO generator code!

**Comment by PBernhardt** [comment]
Wow, I've been staring at code for too long, Ewout. You're right, dates are getting serialized as strings. We're mapping internally to DateTime in some places. Apologies for raising a non-issue.
