### ISSUE TITLE
Update ArtifactSummaryGenerator from obsolete IElementNavigator to new IElementNode

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#692]

**Comment by wmrutten** [comment]
Challenges:

* `ArtifactSummaryGenerator` wants to harvest type of the root node
  But `ISourceNode` does not provide type info - maybe "sniff" element name?
* `ArtifactSummaryHarvester` delegate requires `IElementNavigator`
  esp. requires conditional move MoveToNext(elementName)
  How to efficiently port to IEnumerable<ISourceNode>?
  Need to clone the enumerator in order to restore original position in case of mismatch

**Comment by ewoutkramer** [comment]
Fixed in #733.
