### ISSUE TITLE
Add (x)path location information to validation errors

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#7]

**Comment by brianpos** [comment]
This is more likely fhirpath locations now...

**Comment by brianpos** [comment]
I believe this is now ok as you've done the fhirpath location right?

**Comment by ewoutkramer** [comment]
Well, this is about the dotnet attributes, not the profile validator.  The dotnet validation attributes have no knowledge of the (fhirpath/xpath) location, since all they know about is the POCO's, and poco instances (and elements in the instance) don't know anything about path.

Have no clue how to do this....

**Comment by brianpos** [comment]
Do we even want need that stuff now?
Should we ditch it?
If we were to keep it, i can see how we'd implement the fhirpath given a property. (or at least have a fair idea, and could give it a whirl)

**Comment by ewoutkramer** [comment]
I don't know whether we need it now we have profile validation, maybe @cknaap can comment.  The validation attributes itself are useful - if you have a control bound to them, they will show the error message (Forge uses this), just don't know whether we still need the path.

**Comment by ewoutkramer** [comment]
No one reacts, closing this issue.
