### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VyacheslavMik** [ewoutkramer/fhir-net-api#715]
Hello. You have bug in this line https://github.com/ewoutkramer/fhir-net-api/blob/3d1f21fe66b542ee3eb5c209b956175c213b9f25/src/Hl7.Fhir.Core/Serialization/ParserSettings.cs#L55

**Comment by ewoutkramer** [comment]
Oops, thanks!

**Comment by ewoutkramer** [comment]
Fixed by #719.
