### ISSUE TITLE
Accidental Removal of the DateTime extension methods

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#724]
https://github.com/ewoutkramer/fhir-net-api/blob/5a58d95812e040e94a73a6298e6fc2718fcd8ad0/src/Hl7.Fhir.Core/Support/DateExtensions.cs#L20

The addition of the DateTimeOffset extension methods is a nice addition to support folks that use that type internally and need to convert, but don't want to remove the existing capability

**Comment by ewoutkramer** [comment]
This is not accidental - these methods expect the API to magically do the right thing when passing in a DateTime.  The FHIR spec demands datetimes to have a timezone, and DateTime - unless a DateTimeKind was set, does not provide that information.  So however we implement these methods, they will do the wrong thing for some group of users.

What we can do, to keep supporting `DateTime`, is add additional overloads that take a `TimeSpan` parameter, so something like:

`public static string ToFhirDate(this System.DateTime, TimeSpan offset) => ....;`

However we do it, we need to ensure that the caller can no longer hide from the fact that we need a timezone.

**Comment by brianpos** [comment]
How about if we pass the local or UTC option, and through if not set.
I really want this to be consistent for others that use it. Otherwise they just end up going .ToString and wonder why it's weird.

**Comment by brianpos** [comment]
I'll dummy something up and try it out.

**Comment by ewoutkramer** [comment]
> How about if we pass the local or UTC option,

That "or" is exactly the point. There's no way to chose the "correct" one.

**Comment by brianpos** [comment]
Then I think this is the right thing to do.
Make it a compiler error, but just so that they need to provide which zone is to be used.
Can't force external models to not use date time, but can force declaration of assumption at the boundary.
I like it.

**Comment by ewoutkramer** [comment]
Yes, that's exactly the idea.
