### ISSUE TITLE
ElementType no longer exists

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#725]
Debugger display doesn't work as the property has been renamed
https://github.com/ewoutkramer/fhir-net-api/blob/5a58d95812e040e94a73a6298e6fc2718fcd8ad0/src/Hl7.Fhir.Core/Introspection/PropertyMapping.cs#L20

**Comment by ewoutkramer** [comment]
`ElementType` was renamed to `ImplementingType` and `ReturnType` was removed. Sorry, I was assuming no one uses these (unfortunately) not-internal classes - and I was continuously getting confused about which property did what. 

I should revert that change before we get to beta stage and later.

This is where it all happened:

https://github.com/ewoutkramer/fhir-net-api/commit/b954533907528fa82eab1d0c6d9730ffc99c6b71#diff-4bb0b1977f5f1b432705dc2b34a49860

**Comment by brianpos** [comment]
Pull request will be coming for this.

**Comment by ewoutkramer** [comment]
I think @brianpos - you are preparing a PR to correct this - do you have an ETA for this PR?  If you cannot get the "big" PR you are preparing done quickly, is it worth just sending the fix for this one?

**Comment by brianpos** [comment]
Still going, have been sidetracked with day job.
The change is in my public fork, so you could cherry pick that change.

**Comment by ewoutkramer** [comment]
Picked into R4, but not yet in DSTU2/STU3.  Let's keep it that way as to not break the older releases again.
