### ISSUE TITLE
Patient example: unassigned variables

### ISSUE THREAD

**Issue by ChesedPrather** [ewoutkramer/fhir-net-api#728]
http://docs.simplifier.net/fhirnetapi/model/patient-example.html

Can you clean up the example Patient setup:
1. Initializes variable name and variable nickname but never assigns them.  
2. Initializes variable address but that is never used either. 

Thanks.

**Comment by ewoutkramer** [comment]
@mbaltus - can you take a look at this?

**Comment by mbaltus** [comment]
Yes, I will update the documentation this week. You may close the issue.
