### ISSUE TITLE
API should support low-trust environment

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#734]
@mbaltus reported that the API packages are incompatible with https://dotnetfiddle.net/ (an online C# playground). DotNetFiddle refuses to load the Core package, reporting a security violation on override method `FhirOperationException.GetObjectData`.

Other libraries have reported a similar issue:
https://github.com/axuno/SmartFormat.NET/issues/104

Explanation:
Method `Exception.GetObjectData` is marked with the [SecurityCritical] attribute (in the dotNet runtime).
Hl7.Fhir.Core.FhirOperationException overrides this method and also specifies the [SecurityCritical]  attribute, as required. However in a low trust environment, all explicit security attribute declarations are ignored. Consequently, the override is no longer valid.

Fortunately, dotNet runtime provides an alternative to overriding GetObjectData that also works in low-trust environments:
https://stackoverflow.com/questions/14124874/how-do-i-implement-exception-getobjectdata-in-net-4-in-a-library-assembly-that

I propose that we update the implementation to the alternative approach.

**Comment by ewoutkramer** [comment]
Since I did this only for the FhirOperationException (probably, this was the first exception I added to the API and was following the rules strictly) - is it not better to remove the overload completely?  I forgot why I added it in the first place.

**Comment by wmrutten** [comment]
See #737

**Comment by ewoutkramer** [comment]
We fixed this - and after a bug fix in dotnet fiddle, our library actually works there!

**Comment by wmrutten** [comment]
Awesome!

@mbaltus take notice!
