### ISSUE TITLE
Has anybody used FHIR.NET with EPIC and the full OAUTH process?

### ISSUE THREAD

**Issue by JoeGradecki** [ewoutkramer/fhir-net-api#739]
I see the examples for passing the authorization token but not for all of the initial back and forward....Any guidance would be helpful as the OAuth process isn't child's play

**Comment by mbaltus** [comment]
The Fhir API has nothing to do with the OAuth process directly, and the examples are meant to show you how to set extra HTTP headers on your request when you use the FhirClient. I think this question can best be asked in [the Google group](https://groups.google.com/forum/#!forum/fhir-dotnet) or on [the Zulip platform](https://chat.fhir.org).
