### ISSUE TITLE
Qualifying a search _sort parameter causes OperationOutcome to be returned

### ISSUE THREAD

**Issue by alamyot** [ewoutkramer/fhir-net-api#74]
qualifying a sort with :asc or :desc causes an OperationOutcome to be returned e.g.: "Invalid sort parameter '_sort:asc'"

**Comment by ewoutkramer** [comment]
It seems the server you are targeting is receiving the right search parameter (so no bug in the API), but is simply not supporting the _sort parameter?

**Comment by alamyot** [comment]
Yesterday you commented on Skype
"I have fixed it. It's in the develop branche on GitHub now. I'll push a new version (0.50.1) soon with the fix to NuGet.". I believe the client was generating "_sort:desc=_sort:desc"

**Comment by ewoutkramer** [comment]
Yes, that error has been fixed. I believe it is the server you are reaching out to that now causes this error to be returned, since that server (HAPI) does not support this search parameter (hence it returns an OperationOutcome resource)
