### ISSUE TITLE
_sort=_score not supported

### ISSUE THREAD

**Issue by alamyot** [ewoutkramer/fhir-net-api#75]
As per the DSTU documentation: To sort by relevance, use "_sort:asc=_score".

This causes an OperationOutcome to be returned: "unknown sort parameter '_score'" even if the qualifier is removed e.g.

http://fhirtest.uhn.ca/baseDstu2/Patient?_count=10&name=jones&_sort=_score&_format=JSON

**Comment by ewoutkramer** [comment]
It seems the server you are targeting is receiving the right search parameter (so no bug in the API), but is simply not supporting the _sort=_score parameter value?

**Comment by Bomberlt** [comment]
@alamyot you can try sending same message using some REST client, for example [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm). If the problem is same, seems like it's a server issue.
