### ISSUE TITLE
FhirClient.Search throws ArgumentNullException

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#755]
Library: **Hl7.Fhir.STU3, Version 1.0.0-alpha3**

When providing an invalid `string[]` parameter list to FhirClient.Search, it throws an ArgumentNullException.
```csharp
    var parameters = new string[] { "test" };
    var result = client.Search("Observation", parameters);
```
It should return a more developer friendly error. 
For example ArgumentException "argument should be of the form ```<key>=<value>```

**Comment by ewoutkramer** [comment]
Fixed by #767
