### ISSUE TITLE
How to authenticate FhirClient?

### ISSUE THREAD

**Issue by Aurimas86** [ewoutkramer/fhir-net-api#76]
Let's say FHIR api got OAuth2 authentication on. Using OAuth2Client, I can receive authentication token. How could I use that token with FhirClient or is there another way to authenticate?

Btw, I can authenticate to HttpClient like this:

var client = new HttpClient();
client.SetBearerToken(response.AccessToken);

**Comment by ewoutkramer** [comment]
The FhirClient has two events and two overridable methods that you can use to hook into the request/response cycle:

    public event BeforeRequestEventHandler OnBeforeRequest;
    public event AfterResponseEventHandler OnAfterResponse;

     protected virtual void BeforeRequest(HttpWebRequest rawRequest) 
     protected virtual void AfterResponse(HttpWebResponse webResponse, ...)

As you can see, these give you access to the underlying .NET webrequest/response objects so you can set the required headers and parameters.

Let me know if you need more than these hooks!
