### ISSUE TITLE
Spark .NET FHIR Read API is not returning the latest resource

### ISSUE THREAD

**Issue by santoshjami** [ewoutkramer/fhir-net-api#764]
Hi - 

I am using FHIR Spark DSTU2 .NET API

When I do the following API call on the server:
http://localhost:49911/fhir/Patient/982/?_format=html

This gives me the record for Patient 982 with versionId spark10214
But in the database, there is a latest version spark10215 for the same above Patient.

    var fhirClient = CreateClient();
    Patient fhirPatient = fhirClient.Read<Patient>("Patient/982);
This above snippet is returning the Patient from mongodb, but the document returned is 1 version old (spark10214)

I use this following code:

    Bundle patientBundle = fhirClient.SearchById<Patient>(safeEMRId);
    Patient fhirPatient = (Patient)patientBundle.Entry[0].Resource;
This above snippet returns the latest Patient resource (spark10215)

Is there a defect in the FHIR Read<> API call, or is it anything to do with mongodb?

I am observing this wrong behavior with resources that have lot of versions (history).
For other Patients, it looks fine. Any known issue with code / database?

Attaching the screen shot for reference.
![fhir-restapi-notlatestversion](https://user-images.githubusercontent.com/18682959/48673829-34ee4c00-eb0b-11e8-8457-cc55141ec411.png)

**Comment by kennethmyhra** [comment]
Guessing this is a Spark issue, could be there is some mismatch between the collections resources and searchindex

Can you run the following queries:

* For collection resources:` { resourceType: "Patient", id: "982", "@state": "current" }`, locate and post the contents of field @VersionId 
* For collection searchindex: `{ internal_resource: "Patient", internal_justid: "example" }`, locate and post the contents of fields internal_forResource and internal_selflink

**Comment by santoshjami** [comment]
Thanks Ken for responding back.
Attaching the screen shots of both the queries that you mentioned above.

For the Patient resource with id 982, I find 2 versions and both are in current state. Is this an issue?

Thanks
Santosh Jami
![resources-query-current-state](https://user-images.githubusercontent.com/18682959/48778066-e327fc00-ec99-11e8-8102-ed0c13d7e310.png)
![searchindex-query-internal_justid](https://user-images.githubusercontent.com/18682959/48778068-e3c09280-ec99-11e8-83db-c89d79d77088.png)

**Comment by kennethmyhra** [comment]
searchindex looks OK if 10341 is now the latest?
resources you need to set @current field to "superceded" of the non-current resource, guessing 10284.

Do you have other resources with the same problem or is this the only one?

**Comment by santoshjami** [comment]
I have identified Patient resource so far with this discrepancy.
There are multiple Patients which need this fix. When a new version of the resource (Patient / Document / DiagnosticReport) get created, would the logic not drive setting the older version to "Superceded"?
Does this indicate this is a bug in the Spark API?

How do I set all the old versions of the Patient resources to Superceded? Please suggest.

**Comment by kennethmyhra** [comment]
It definitely should, I will have to do some tests on my side, my impression is that you are posting a Bundle with Patient, Document, DiagnosticReport effectively using the Transaction operation on the API?

Will have to do some research on setting old versions to superceded as well, might not be as trivial.

**Comment by ewoutkramer** [comment]
Can we transfer this issue to the Spark repo?

**Comment by kennethmyhra** [comment]
Absolutely

**Comment by kennethmyhra** [comment]
@santoshjami let's continue the resolving of this issue here: https://github.com/FirelyTeam/spark/issues/132
