### ISSUE TITLE
StructureDefinition.id validation allows spaces

### ISSUE THREAD

**Issue by abelenthoven** [ewoutkramer/fhir-net-api#78]
Issue exported from the Forge issue list: Appearantly, it's possible to enter a StructureDefinition.id containing spaces or other unallowed characters. Forge could stop this, but as Forge uses the API validation it might be better to include it there.

**Comment by ewoutkramer** [comment]
DotNetAttributeValidation.Validate() should catch this. Did you call this to validate the StructureDefinition? What did you use to "validate" the contents of this element?
