### ISSUE TITLE
Extend the enum AllergyIntoleranceCategory

### ISSUE THREAD

**Issue by Javier13** [ewoutkramer/fhir-net-api#792]
Hi. I would like to know if it is possible to extend a enum, for example AllergyIntoleranceCategory with own values.

Thanks

**Comment by ewoutkramer** [comment]
No, that is not possible.  There are good reasons for this.  The C# library has enums only for those valuesets in FHIR that are part of a "required" binding. This means that the codes in the enums are the *only* codes that are allowed in FHIR for that element (in this case AllergyIntolerance.category).  So, even if you would extend the enum (you could of course always add members yourself in the C# code), the resulting XML and JSON would no longer be FHIR compliant.  So, we do not support this.

If you need to communicate additional categorical information, you can always use [extensions](https://www.hl7.org/fhir/extensibility.html).
