### ISSUE TITLE
public static ResourceFormat GetResourceFormatFromContentType(string contentType) throws nullpointer exception if contentType has non-alphanumeric characters

### ISSUE THREAD

**Issue by poadhika** [ewoutkramer/fhir-net-api#794]
ContentType.GetResourceFormatFromContentType throws null pointer exception if contentType has non-alphanumeric characters.  

So if you try ContentType.GetResourceFormatFromContentType("\"application/blah") it will throw null pointer exception.

**Comment by ewoutkramer** [comment]
Fixed by PR #795
