### ISSUE TITLE
"Resource type name may only appear at the root of a document" for contained and entry

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#806]
I would find it convenient if this worked. It currently ends in an error:

System.InvalidOperationException : Invocation of 'builtin.children' failed: Resource type name may only appear at the root of a document

```csharp
        [Fact]
        public void SelectInNestedResource()
        {
            var bundleWithPatient = new Bundle { Entry = new List<Bundle.EntryComponent>() { new Bundle.EntryComponent { Resource = new Patient { Id = "pat1" } } } }.ToTypedElement();
            bundleWithPatient.Select("Bundle.entry.resource").First().Select("Patient.id").First().Value.Should().Be("pat1");

            var resourceWithContained = new Patient { Contained = new List<Resource> { new Observation { Id = "obs1" } } }.ToTypedElement();
            resourceWithContained.Select("Patient.contained").First().Select("Observation.id").First().Value.Should().Be("obs1");
        }
```

**Comment by brianpos** [comment]
This is correct FHIR Path, the repeating the top level resource name doesn't work with bundles (unless you're repeating the bundle name itself)
You can drop the `Bundle.` from the start, and also the `Patient.` from `Patient.contained`

**Comment by ewoutkramer** [comment]
Asked Bryn and Grahame for their opinions.

**Comment by ewoutkramer** [comment]
So, Patient.contained.Observation.id is indeed incorrect FHIRPath, so it's OK the API rejects it.
