### ISSUE TITLE
If-Match value should be surrounded by quotes

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#82]
Except when using * (star)
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by ewoutkramer** [comment]
That is incorrect. The If-match header contains an E-Tag, which may look like "23" (strong ETag) or W/"23" (weak ETag), so the FhirClient cannot automatically surround the value in the header with quotes, the caller has to set the IfMatch element correctly, using quotes when necessary.
