### ISSUE TITLE
FhirJsonSerializer.IgnoreUnkownElements does not seem to work

### ISSUE THREAD

**Issue by cknaap** [ewoutkramer/fhir-net-api#821]
API 1.1.0-beta1
```csharp
        [Fact]
        public void IgnoreElements()
        {
            var patient = SourceNode.Resource("Patient", "Patient", SourceNode.Valued("id", "pat1"));
            var jsonBare = patient.ToTypedElement(_schemaProvider).ToJson(new FhirJsonSerializationSettings { IgnoreUnknownElements = false });
            jsonBare.Should().Contain("pat1", "Successful serialization expected");

            patient.Add(SourceNode.Valued("unknownElement", "someValue"));
            var jsonUnknown = patient.ToTypedElement(_schemaProvider).ToJson(new FhirJsonSerializationSettings { IgnoreUnknownElements = true });
            jsonUnknown.Should().NotContain("unknownElement", "Successful serialization expected, without unknownElement");
        }
```
The second serialization fails with "Message: Hl7.Fhir.ElementModel.StructuralTypeException : Encountered unknown element 'unknownElement'".
I expected it to succeed since I set IgnoreUnknownElements to true.

**Comment by ewoutkramer** [comment]
It's not a bug, but an omission in the documentation ;-)   Parsing is lazy, so only triggered when the serializer actually starts serializing the TypedElement.  So, the errors comes from the parser rather than the serializer.  If you pass a settings object to the ToTypedElement() with ErrorMode = Ignore, this unit-test will work.

We will have to improve the error messages so it becomes clear this is an error on the parsing side, not on the serializer side, though.

**Comment by ewoutkramer** [comment]
It would be wise to review the errors in SourceNode implementations, the TypedNode and the serializer, to make sure the context is known.

**Comment by ewoutkramer** [comment]
`http://docs.simplifier.net/fhirnetapi/parsing/itypedelement-serialization.html` and/or `http://docs.simplifier.net/fhirnetapi/parsing/itypedelement.html#handling-structural-type-errors` should probably be expanded to have more details about this.

**Comment by ewoutkramer** [comment]
The itypedelement.html#handlings-structural-type-errors page now has this final paragraph:

> Detecting type errors is done lazily, so in order to detect all errors, one would have to do a complete visit of the tree, including forcing a read of the primitive data by getting the Value property. There is a convenience method VisitAll() that does exactly this. Additionally, there is a metehod VisitAndCatch() that will traverse the whole tree, returning a list of errors and warnings.

**Comment by ewoutkramer** [comment]
Also, we'll improve the error message, see PR#844.

**Comment by ewoutkramer** [comment]
And even more complete: #821
