### ISSUE TITLE
DocumentReference author

### ISSUE THREAD

**Issue by slartibartfast3000** [ewoutkramer/fhir-net-api#825]
Hi 

DocumentReference.author property seems to be missing in the nuget build hl7.fhir.r4.core v4.0.30319 0.96.1.0

Cheers

**Comment by ewoutkramer** [comment]
Hi @slartibartfast3000 - we have recently ran a full update of R4 support, bringing it up to date with the final released specification.  There's an alpha-build (nightly) available on this NuGet feed: https://www.myget.org/F/fhir-net-api/api/v3/index.json

We are planning a beta-release somewhere in the next week or so to the normal NuGet.
