### ISSUE TITLE
unable to install Hl7.Fihr.DSTU2 package together with Hl7.Fihr.STU3 (multi-version support)

### ISSUE THREAD

**Issue by yaron-gilboa** [ewoutkramer/fhir-net-api#834]
hi,

i need to write a Fihr client that should connect to multiple # of Fihr servers, of any version. 
I was trying to install the DSTU2 nuget after installing STU3, however encountered some major conflicts (see below) and needed to remove it.

Is multi-version configuration supported? if so how can it be acheived?

`Error	CS0433	The type 'AdministrativeGender' exists in both 'Hl7.Fhir.DSTU2.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' and 'Hl7.Fhir.STU3.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'	ChowApp	D:\Chow\Workspaces\ChowHealth\ChowApp\BL\Thrp\FihrService.cs	109	N/A
Error	CS0433	The type 'ContactPoint' exists in both 'Hl7.Fhir.DSTU2.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' and 'Hl7.Fhir.STU3.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'	ChowApp	D:\Chow\Workspaces\ChowHealth\ChowApp\BL\Thrp\FihrService.cs	103	N/A
Error	CS0433	The type 'ContactPoint' exists in both 'Hl7.Fhir.DSTU2.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' and 'Hl7.Fhir.STU3.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'	ChowApp	D:\Chow\Workspaces\ChowHealth\ChowApp\BL\Thrp\FihrService.cs	106	N/A
Error	CS0433	The type 'FhirClient' exists in both 'Hl7.Fhir.DSTU2.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' and 'Hl7.Fhir.STU3.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'	ChowApp	D:\Chow\Workspaces\ChowHealth\ChowApp\BL\Thrp\FihrService.cs	86	N/A
Error	CS0433	The type 'Patient' exists in both 'Hl7.Fhir.DSTU2.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3' and 'Hl7.Fhir.STU3.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d706911480550fc3'	ChowApp	D:\Chow\Workspaces\ChowHealth\ChowApp\BL\Thrp\FihrService.cs	89	N/A
`

**Comment by ewoutkramer** [comment]
You need to use aliases, as described here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias

However, this does not work perfectly in .NET Core yet, but this is a known issue - and has a temporary solution: https://github.com/NuGet/Home/issues/4989

**Comment by brianpos** [comment]
If you want to see another project that does this currently that you can try it out with, check this code here:
https://github.com/brianpos/FhirPathTester/blob/8f170d0faabf28516a491b040997089cf7662324/UWP/FhirPathTesterUWP.csproj#L235
