### ISSUE TITLE
Set PermissiveParsing to false in 1.x release, and to true in 2.x release

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#838]
We have discussed several times how to handle the new "strictness" of the parsers in the 1.x releases. E.g. empty values will now be caught, repeating elements must now be arrays in Json etc.  This triggers validation errors on data that was previously regarded as "valid" by the <1.x parsers.

There is a setting for this: PermissiveParsing (lacking in the Poco settings before 1.2 though) - but the default is false, causing incompatibility with the 0.9x releases.  Personally I think this is ok, since we have changed the major versionnumber, but we could have a static boolean that you can set once in your software to make sure all your components are doing one or the other.   The default for this flag in 1.x could than be "false", and we could set it to "true" in 2.x.  Software that wants to be lenient can then switch strictness on a application basis.

Disadvantages are that if you want to vary this behaviour (like in unit tests, or even in production software), you have to manipulate static globals - something that almost always means pain in the future somehow.

I'd love to hear some opinions on this before we move ahead....

**Comment by wmrutten** [comment]
I'd be very reluctant with adding global state. It complicates unit testing and could introduce issues in multi threaded scenarios.

Alternatively, we could implement support for (system-wide or user-specific) configuration files, cf. the built-in Settings classes, or Environment variables.

**Comment by ewoutkramer** [comment]
Discussed this again in the Standup call last monday.  We feel the default should be strict - but you should be able to switch it off. 

This is also going to be covered by #857 and #852, but the default will be strict.

**Comment by brianpos** [comment]
I still think this parsing validation is something you should have to opt into. This will be in my branch and continue to leave me in our own fork.

**Comment by ewoutkramer** [comment]
Profile Validation - sure, but these are basic structural checks.  You can try to continue parsing when these errors are found, but some of these errors will cause failure in higher layers - e.g. repeating elements that are not consecutive, json strings where decimals are expected.  Having these checks disabled by default will create incorrupt and incomplete data without the user getting any kind of notification.  So, there's definitely checks that need to be done - always.  

I am currently listing all errors to see which one are optional.  But even then the question remains - at the last standup the server writers agreed that having them on by default was the best strategy.  But we can debate that again!

**Comment by brianpos** [comment]
The specific one that irks me is the empty node validation rule. That's not misinterpreted format. It's the one that is hitting me a lot and others I've had feedback from. 
A decimal in quotes, I could possibly live with that rule.

**Comment by wmrutten** [comment]
Maybe we should consider a practical approach, specifically for dealing with empty value attributes.
Strictly speaking, this is illegal syntax. However in reality this occurs quite frequently and I am afraid it won't go away any time soon. Practically, empty values should not result in critical parsing failures, nor corrupt any higher level logic, if we allow to ignore such values (treat as missing).
