### ISSUE TITLE
Use the Conformance statement to determine server version before first actual call

### ISSUE THREAD

**Issue by ewoutkramer** [ewoutkramer/fhir-net-api#84]

**Comment by brianpos** [comment]
I would be cautions on this one, as knowing when the first call is could be difficult.

**Comment by ewoutkramer** [comment]
The Java client supposedly does this too.... is it more difficult than guarding all public calls with a verifyConformance() that makes sure it is only called once?

**Comment by grahamegrieve** [comment]
I call it when the client is created

Grahame


On Wed, Jun 3, 2015 at 5:01 PM, Ewout Kramer <notifications@github.com>
wrote:

> The Java client supposedly does this too.... is it more difficult than
> guarding all public calls with a verifyConformance() that makes sure it is
> only called once?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ewoutkramer/fhir-net-api/issues/84#issuecomment-108219020>
> .
>



-- 
-----
http://www.healthintersections.com.au / grahame@healthintersections.com.au
/ +61 411 867 065

**Comment by ewoutkramer** [comment]
I generally don't like constructors with side effects, so I'd have to do it on the first "real" call.  Interested to see why Brian think that may be hard.

**Comment by ewoutkramer** [comment]
Done.  FhirClient constructor has a parameter to disable checking if needed.
