### ISSUE TITLE
Error parsing valueSimpleQuantity

### ISSUE THREAD

**Issue by Sushant-Sardeshpande** [ewoutkramer/fhir-net-api#849]
Have an extension of type valueSimpleQuantity added to the MedicationAdministration resource and have a custom resource created that contains the MedicationAdministration resource along with MedicationRequest, Medication and a couple of other custom resources.

Added the FHIR client using API version 0.94.0 to our Web API. We have noticed that on the start of the service when calling this resource, it is parsed as expected, however on accessing a Patient resource and then again accessing this MedicationAdministration resource it throws a parsing error for valueSimpleQuantity (only if the extension is present)

Haven't done any explicit caching for the FHIR client.
Might I know the possible cause for this, thanks in advance.

**Comment by ewoutkramer** [comment]
Hi! valueSimpleQuantity is illegal as a name for an element.  You should use valueQuantity instead.

This is visible (although pretty subtly) on this page: http://hl7.org/fhir/STU3/datatypes.html.  Here, you can see SimpleQuantity is pink, signifying that this is not a "real" type, so cannot be used in the [x] of Extension.value[x].

It's different from DSTU2: http://hl7.org/fhir/DSTU2/datatypes.html and again different in R4 (http://hl7.org/fhir/datatypes.html)
