### ISSUE TITLE
Chained Parameter Query DSTU1

### ISSUE THREAD

**Issue by kkatsoulas** [ewoutkramer/fhir-net-api#85]
I use "Hl7.Fhir.Model.dll"

var uri = new Uri(_url);
var client = new FhirClient(uri);
var alergySubjectRef_location = String.Format("Patient/{0}", AlergySubjectRef); //Patient
var location = String.Format("{0}/AllergyIntolerance?subject={1}", _url, alergySubjectRef_location);
ResourceEntry entry = client.Read(new Uri(location));

My Server is DSTU1.
I get the error Message  
"At line 1, pos 2: Encountered a feed instead of a resource"

**Comment by kkatsoulas** [comment]
To be more specific. The url created is: "http://localhost:1396/fhir/AllergyIntolerance?subject=Patient/spark20".
I can get this resource from my browser...

**Comment by Bomberlt** [comment]
Possible duplicate of [#49](https://github.com/ewoutkramer/fhir-net-api/issues/49). Check your headers and try post that query to same server with other Accept headers.

**Comment by kkatsoulas** [comment]
I do not fill any Accept headers. Never did...
The entries I search for are more than one. This must be the reason why method client.Read does not work. I used Bundle entry2 = client.Search("AllergyIntolerance", query);
and it works fine!

But how can I convert my data from Bundle to ResourceEntry ?
Thank you!

**Comment by Bomberlt** [comment]
You can get bundle entries from .Entries property and than cast them to ResourceEntry to your needed type like that:
```c#
Bundle entry2 = client.Search("AllergyIntolerance", query);
var allergyIntolerances = entry2 .Entries.AsList();
var allergy = allergyIntolerances[0] as ResourceEntry<AllergyIntolerance>;
```

So if it works, you can close issue.

**Comment by kkatsoulas** [comment]
Thank you very much Povilas!
