### ISSUE TITLE
R4 Snapshot Generator - Fix ElementDefinition.Base component

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#853]
Update the Snapshot Generator for changes in FHIR R4 to `ElementDefinition.Base` component:

- base of root element base refers to itself (`.Base.Path = .Path`)
  STU3: DomainResource or Resource
- base of newly introduced element refers to itself (`.Base.Path = .Path`)
  STU3: empty

**Comment by ewoutkramer** [comment]
Fixed by #853
