### ISSUE TITLE
Encoded parameters problem

### ISSUE THREAD

**Issue by DomenicoImperi** [ewoutkramer/fhir-net-api#859]
Good morning,

I have a problem doing a Search on a CarePlan and I can not find a solution.

The CarePlan search is on a Patient with this reference:
Patient/XXX^^^&2.16.840.1.113883.2.9.4.3.2&ISO

the server expects the encoded parameter in this way:
CarePlan?subject=Patient%2XXX%5E%5E%5E%262.16.840.1.113883.2.9.4.3.2%26ISO
in fact, doing a browser test works.

Using the .NET FhirClient I get:
CarePlan?subject=Patient%2XXX%5E%5E%5E&2.16.840.1.113883.2.9.4.3.2&ISO
and it does not work, because the ampersand are not encoded.

I tried to encode the parameters but the final result is a double encoding
CarePlan?subject=Patient%252fXXX%255e%255e%255e%25262.16.840.1.113883.2.9.4.3.2%2526ISO
and it does not work.

Can you help me?

Hl7.Fhir.STU3.Core 1.1.2.0

**Comment by mbaltus** [comment]
Hello Domenico,

I cannot reproduce the problem - my search url encodes correctly, so could you send some details of your problem to fhirapi@fire.ly?
For example: do you use FhirClient.Search, and how do you supply the parameter?

Apart from that, the reference does not seem to conform to a FHIR id, which cannot contain ^ and &: "id: Any combination of upper or lower case ASCII letters ('A'..'Z', and 'a'..'z', numerals ('0'..'9'), '-' and '.', with a length limit of 64 characters."
