### ISSUE TITLE
FhirJsonParser not accepting empty strings

### ISSUE THREAD

**Issue by sajithv01** [ewoutkramer/fhir-net-api#873]
Able to serialise a resource containing empty string into a JSON data. But it fails to create a Resource from a JSON string ( JSON string contains some property as an empty string )

```
var serializer = new FhirJsonSerializer();
// data is a Resource of ResourceType = Patient
var content = serializer.SerializeToString(data);
```

from the above code, it generates a JSON string that contains an empty string for family (property in HumanName) as follows

```
"name": [
        {
            "family": "",
            "given": [
                "ABC"
            ],
            "prefix": [
                "Mr"
            ],
            "period": {
                "start": "18-02-2019 12.00.00 AM"
            }
        }
    ]
```

The issue has happened when it parses to Resource using the below code.

 ```
             var parser = new FhirJsonParser();
              // result is a JSON string 
              var resource = parser.Parse<Resource>(result);
```
Exception contains the following information
"The property 'family' has an empty string value, which is not allowed. (at line 1, 1555)"

This issue was found in version 1.1.3.0 and in 0.96.0 it is working.

**Comment by ewoutkramer** [comment]
That's right, empty strings are illegal in FHIR.  0.96.0 was too lax in this respect.  You can enable the old behaviour by setting the "PermissiveParsing" option in the settings!
