### ISSUE TITLE
Publishing a new version of the R4 NuGet package

### ISSUE THREAD

**Issue by alexdegroot** [ewoutkramer/fhir-net-api#876]
Thanks for the great effort into this library.
I was wondering whether it would be possible to push a new version of the R4 package to the public NuGet feed?
When checking capabilities on some test servers I get errors about the CatalogEntry not a valid enumeration inside 'ResourceType'. This is just because I'm using an old package which contains old sources.

Thanks!

**Comment by ewoutkramer** [comment]
Hi Alex, we have an alpha build currently, but are planning to get it to beta this week, so it will appear on NuGet if you check "prereleases".
