### ISSUE TITLE
FhirClient: Cannot parse xml

### ISSUE THREAD

**Issue by yunwwang** [ewoutkramer/fhir-net-api#89]
I developed a Fhir Vocab Server and a MVC web client using Nuget package 0.50.1. When I tested, I got error:
[FormatException: Cannot parse xml: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.]
   Hl7.Fhir.Rest.HttpToEntryExtensions.parseResource(String bodyText, String contentType) +419
   Hl7.Fhir.Rest.HttpToEntryExtensions.ToBundleEntry(HttpWebResponse response) +728
   Hl7.Fhir.Rest.Requester.doRequest(BundleEntryComponent interaction) +147
   Hl7.Fhir.Rest.Requester.Execute(Bundle transaction, IEnumerable`1 expect) +119
   Hl7.Fhir.Rest.FhirClient.InstanceOperation(Uri location, String operationName, Parameters parameters) +88

When I use Chrome Poster to post HTTP Request to server, I got correct xml response back.

What should I do to fix this problem?

**Comment by ewoutkramer** [comment]
Most of the time this happens when you create a client and go to the wrong endpoint, e.g.     “spark.furore.com” instead of “spark.furore.com/fhir”.  Also, you’d see this error message when the parser encounters XHTML (so the server actually returns an error or text), when the XML parser parses this as XML you’d get warnings about DTD in the XHTML.  Is any of these things the case?

Otherwise, please send me the xml you are receiving when you try to parse it, and I can try to reproduce the bug.

**Comment by ewoutkramer** [comment]
This is clearly a FAQ, and it mostly happens when the parser is "forced" to parse XHTML with DTD, not XML.  The FhirClient could do extra checks (content type? I think I do that) so give clearer error messages, so help developers resolve these problems.

**Comment by yunwwang** [comment]
That’s good suggestion. You are right that when I published to web server, the end point for Fhir server has /fhir. I will fix that and test again.

Thank you Ewout

Yunwei

**Comment by joeatterberry** [comment]
Hi Ewout,

I got this same error from a FHIR implementation that did not support returning OperationOutcome when a resource was not found.  According to the latest spec, populating OperationOutcome is not required.  Does the current C# library support 4xx errors where no body or OperationOutcome is populated?

Thanks.
Joe

**Comment by ewoutkramer** [comment]
Yes, there are holes there I think. I am going to look at this today.

**Comment by ewoutkramer** [comment]
I fixed this issue in commit 4b52157c044ad981926250b13484507c97918567. @joeatterberry, I will fix your bug as part of #64.

**Comment by joeatterberry** [comment]
Thank You so much, Ewout!
