### ISSUE TITLE
Quotes in HTML in JSON not escaped

### ISSUE THREAD

**Issue by riksmithies** [ewoutkramer/fhir-net-api#90]
This issue seen with the Spark server, but due to API code I believe.
When I store this:
 "text":  {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Nuclear, Neville. SSN:\r\n 444111234\r\n </div>"
  }
it comes back as this
"text":  {
    "status": "generated",
    "div": "<div xmlns="http://www.w3.org/1999/xhtml">Nuclear, Neville. SSN:\r\n 444111234\r\n </div>"
  }
The second version is missing the backslash before the quotes in the div.

**Comment by ewoutkramer** [comment]
Your double quotes examples don't have double quotes ;-)

This is what you sent before:
"text":  {
    "status": "generated",
    "div": "<div xmlns="http://www.w3.org/1999/xhtml">Nuclear, Neville. SSN:\r\n 444111234\r\n </div>"
  }
[11:24:47] Rik Smithies: the quotes inside the div are not escaped
[11:25:13 | Edited 11:25:57] Rik Smithies: so I cannot put this back unless I change to:
[11:25:14] Rik Smithies:  "text":  {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Nuclear, Neville. SSN:\r\n 444111234\r\n </div>"
  }

**Comment by ewoutkramer** [comment]
Ha!  GitHub strips them out...

**Comment by riksmithies** [comment]
oh yeah, I just pasted my prepared text and didn't notice. 

But, similarly - I also noticed that my rest client is converting the (correctly) escaped quote to an un-escaped one for the display. So this is not a bug in this API at all. 

My mistake then, sorry for the bother.
