### ISSUE TITLE
IArtifactSource should also return resource origin

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#92]
the `IArtifactSource.LoadConformanceResourceByUrl` method returns the deserialized resource. Often, the client also needs the resource origin, i.e. the location from which the resource was resolved. However currently the API does not return this information.

e.g. add overload with additional `out` parameter.

**Comment by wmrutten** [comment]
Suggestion: the API could return this information via Resource.UserData. This will transfer the meta information to the caller without breaking the API or affecting the serialized resource. Disadvantage of this approach is that the meta information is not easily discoverable.

**Comment by ewoutkramer** [comment]
This is now done exactly this way, using an Annotation of type OriginInformation
