### ISSUE TITLE
DSTU2 = Summary Parser doesn't include the value of a code type

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#93]
This is the summary output from a Questionnaire:
` <Questionnaire>
 <id value=" demo" />
 <meta>
 <versionId value=" 1" />
 <lastUpdated value=" 2015-08-13T22:38:03.423+10:00" />
 <tag>
 <system value=" http://hl7.org/fhir/v3/ObservationValue" />
 <code value=" SUBSETTED" />
 </tag>
 </meta>
 <status />
 <date value=" 2015-08-13T11:28:24.735Z" />
 </Questionnaire>`

The status property in the full mode is
`<status value=" published" />`

**Comment by ewoutkramer** [comment]
Hi Brian, this bugreport is unreadable for me.... Is this issue still current?

**Comment by brianpos** [comment]
http://sqlonfhir-dstu2.azurewebsites.net/fhir/Questionnaire/4c9f1415e6b244409510a0de1fa7df46/_history/31?_format=html&_summary=true
This is an example. Just remove the summary=true to see full values

**Comment by brianpos** [comment]
Also the code generated for the summary attribute must be messing something up along the way.
The Group Text property has the InSummary attribute in the code, however the spec page doesn't
http://hl7.org/fhir/questionnaire-definitions.html#Questionnaire.group.text

Have updated the Summary Unit Test to try and verify the issues that I spotted.
(It now fails, but should pass if the issues are resolved)

**Comment by brianpos** [comment]
I fixed the issue with the status property, but in updating the test, found a bigger problem where the IsSummary attribute isn't generated correctly for the Questionnaire Group component.
(Haven't looked into how wide this issue is. But is also an issue for AuditEventParticipantComponent Role property, so maybe all sub-components are not being generated correctly)

**Comment by brianpos** [comment]
Believe this is now resolved by the t4 template generated code now.
