### ISSUE TITLE
OperationOutcome is not set in FhirOperationException

### ISSUE THREAD

**Issue by KristofVerbiest** [ewoutkramer/fhir-net-api#94]
A FhirOperationException never contains the OperationOutcome even if the HTTP response contains such an outcome.

I took a look at the code and it seems that the HTTP response is parsed into an OperationOutcome but that outcome is not actually set in the exception.

This can be fixed in Hl7.Fhir.Rest.Requester.Execute by adding the outcome to the exception like this:

    if (response.Resource is OperationOutcome)
    {
        var outcome = response.Resource as OperationOutcome;
        var text = reportOutcome(outcome);
        throw new FhirOperationException(message + " OperationOutcome: " +  text, outcome);
    }

**Comment by brianpos** [comment]
Which version of the client was this?
_I'm happy to do this in the DSTU2 branch..._

**Comment by KristofVerbiest** [comment]
Hi Brian,
thanks for looking into this.

On the master branch you can see this on line 96 in the class I referred to.
Upon closer inspection this seems to be reworked on the developer branch and is probably fixed.

**Comment by ewoutkramer** [comment]
Yes, I did a big rewrite in a recent version, so it's the develop branch you'd need to verify this on. I will generate a new NuGet package this week, so the master will be aligned soon.

**Comment by ewoutkramer** [comment]
I pushed the latest version of te package. Can you verify this issue is fixed?

**Comment by KristofVerbiest** [comment]
I've verified this in the Master branch and it is OK now.
By the way thanks for including the HTTP status code in the exception - this is a great help.
