### ISSUE TITLE
Paging parameter for RESTFul API

### ISSUE THREAD

**Issue by pickymartin** [ewoutkramer/fhir-net-api#96]
Based on a sample link below with paging information (taken from https://www.hl7.org/fhir/http.html#paging):
<link rel="first" href="http://example.org/Patient?name=peter&stateid=23&page=1"/>

The paging parameter above is 'page'.  All reserved keywords seem to start with '_', should this also apply to the paging parameter so it would be "_page" instead?

Also, is there plan to add paging field to Hl7.Fhir.Model.Query?

**Comment by ewoutkramer** [comment]
Hi pickymartin.  The client is following the FHIR specification, which does not describe this parameter.  If you want to change this aspect of FHIR, you'll need to file an RFC for the FHIR spec. This can be done here: http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemAdd&tracker_id=677
