### ISSUE TITLE
Support for DAF Profiles

### ISSUE THREAD

**Issue by dougs016** [ewoutkramer/fhir-net-api#97]
We have started looking at FHIR within our organization and had a question regarding the Data Access Framework (DAF).  Is there a plan to support the DAF profiles within the API?

Thanks,
Doug

**Comment by ewoutkramer** [comment]
Hi Foug, What kind of explicit support are you expecting?  A DAF patient, is a Patient after all, or are you looking for specific class models where elements that are not used in DAF have been removed?
