### ISSUE TITLE
DSTU2: Summary serializer seems buggy

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#98]
The Valueset is defined to not have the concepts included in the summary, however when getting a summary, then these are included in the output.

http://sqlonfhir-dstu2.azurewebsites.net/fhir/ValueSet/f62b2b43533943acabdfde6c72434001/_history/1?_format=html&_summary=true

_Will create a unit test to verify this in the client._

**Comment by ewoutkramer** [comment]
If the definition of a Resource has no elements indicated as "in summary", it is assumed to mean *all* elements are in the summary. Grahame's excel reader has this logic built in, so the serializer sees all elements as "in summary"!
